cmake/external/googletest.cmake
Tests from the main repo are depenent on MOCK_METHOD() calls that aren't supported in 1.7.  Updating our google test dependency to fix integration test compilation errors (b159716156).
=> Updated Google Test dependency from 1.7 to 1.10

auth/tests/auth_test.cc, auth/tests/desktop/auth_desktop_test.cc, auth/tests/desktop/test_utils.h, auth/tests/desktop/user_desktop_test.cc, auth/tests/user_test.cc
- Fixed issues with auth listeners not being invoked before their invocation count was verified.
- Fixed an issue with Reauth test using an email credential with a anonymous user. 
- auth_test.cc - ensured the all new auth instances are created with signed out users, just in case the previous test failed and left one signed in.
=>  Mac unit test flake removal, part 1

.github/workflows/android.yml, app/google_api_resources/build.gradle, build_scripts/android/install_prereqs.sh, firestore/firestore_resources/build.gradle
Add Android as a GHA CI worfklow.  
- added android.yml to our workflows
- fixed an analytics build issue which now news to include play-services-base as an implementation dependency.
- there's a lint failure in a firestore dependency.  Disabling abortOnError for that gradle build target for now. I've added an internal issue to the backlog to circle back on this issue later.
=> Android GHA workflow

.gitignore, testing/integration_testing/build_testapps.json, testing/integration_testing/build_testapps.py, testing/integration_testing/config_reader.py, testing/integration_testing/export.plist, testing/integration_testing/provisioning.py, testing/integration_testing/requirements.txt, testing/integration_testing/restore_secrets.py, testing/integration_testing/xcode_tool.rb, testing/integration_testing/xcodebuild.py
Adds the tools needed to build and run C++ integration tests.
These derive from the corresponding tools in the internal repo, with some changes and exceptions:
- build_testapps.py and build_desktop_testapps.py have been merged into a single, simpler build_testapps.py.
- restore_secrets.py is a new script that decrypts the secret files in scripts/gha-encrypted and restores all the files/values that were stripped out when pushing the integration source code to Github. Except for the reverse ids in the Info.plists needed for iOS, which are not present yet.
- xcodebuild.py, provisioning.py and xcode_tool.rb are all for iOS, which is not yet supported until signing is figured out.
This also includes a change to .gitignore to ignore temporary Python files, as well as unencrypted secrets.
There …
=> Add tools for C++ integration tests

.github/workflows/integration_tests.yml
To manually trigger a workflow in a branch, a workflow with the same name needs to exist in master. This adds such a workflow.
=> Create dummy workflow for integration tests

.github/workflows/integration_tests.yml
Most of this workflow is copied verbatim from the workflow to build the SDK. The duplication means that most changes to the SDK build workflow will need to be mirrored into this one. 
There are two new parts for the integration tests:
- Manual dispatch with input parameters that can be specified when triggering.
- Two new steps ('Prepare for integration tests' and 'Build and run integration tests').
This PR is dependent on two other PRs:
https://github.com/firebase/firebase-cpp-sdk/pull/106
https://github.com/firebase/firebase-cpp-sdk/pull/103
This workflow is not set to run automatically. For now, it will only run on manual trigger. Which APIs to build/test, which platforms to build for, and which operating systems to run on can be specified when triggering. 
Parameterizing the operating …
=> Add integration test workflow

firestore/CMakeLists.txt
Fixes linker symbol missing errors discovered when building firestore's integration tests. This dependency absl_types is used just by the C++ part of Firestore and hence was not pushed to "firebase-ios-sdk" repo.
We were seeing errors like these,
undefined reference to `absl::lts_2020_02_25::variant_internal::ThrowBadVariantAccess()
=> adding absl_variant as a dependency

storage/integration_test/src/integration_test.cc
Fixes for the Storage integration test.  The test would timeout on Windows when attempting to sign in a user anonymously, though it would work for the first sign in attempt, just not subsequent ones.
I pulled in the auth teardown logic.
Additionally removed an unneeded check for app initialization in the teardown method.  This check is already being done by the sub-methods.
=> Fix for Windows Storage Integration Test timeout

database/integration_test/src/integration_test.cc
Added enforced auth signout on every test teardown.  Signout must be done after the database cleanup is done.
=> Fix Database integration test on Windows 

.github/ISSUE_TEMPLATE/--general-question.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/issue.md
Add a new "General Question" template
Also make sure new feature request issues are marked with "new" label
=> Update issue templates

.github/workflows/cpp-packaging.yml, build_scripts/android/build.sh, build_scripts/ios/build.sh
Add desktop build to C++ packaging workflow, using existing desktop python scripts. (This omits pre-packaging testing, as testing will be done on the *packaged* SDK.)
=> Add desktop builds to C++ packaging workflow.

firestore/CMakeLists.txt, firestore/integration_test/Podfile, firestore/integration_test/src/integration_test.cc
There are 3 reason causing the firestore ios integration testapp not build:
1. pod version (6.24.0 -> 6.32.2)
2. firestore library missing source files (at least for iOS Framework)
3. firestore api updated
Also, I believe we should update all /integration_test/Podfile as well. But that should be another PR. Is there a strategy to update /integration_test/Podfile after the /ios_pod/Podfile updated?
=> Fix firestore ios build

scripts/gha/build_desktop.py, scripts/gha/utils.py
Reverts firebase/firebase-cpp-sdk#155
There was too much happening behind the scenes in python scripts and that could make it harder to debug and follow the workflow. It also prevents users from manually running scripts contained inside the python script as some of the configuration files are created on the fly by python script. Reverting these changes and will be testing out another way of doing this - creating a pre-defined set of configuration files in our repo and using just those configuration files.
=> Revert "Feature/support non standard vcpkg configs"

messaging/integration_test/build.gradle
Updated Messaging Integration Test build.gradle file to require Android SDK 26. 
`src/android/java/LibraryManifest` declares minSDK version 26 as a dependency due to its new  use of JobIntentService. As of Android O, background services can no longer spawn other background services, they must instead create JobIntentServices, which can queue up work for the OS to perform when it is ready. 
=> Messaging IntegrationTest min Android sdk updated to v26

storage/integration_test/src/integration_test.cc
I believe this commit causing the iOS test fail: https://github.com/firebase/firebase-cpp-sdk/commit/3ece8b2f28ade78f6b8991833d01544ac31d4866# @DellaBitta 
And I was wondering if should we sync the changes into google3.
=> fix storage integration testapp for iOS 

admob/build.gradle, analytics/build.gradle, android_build_files/android_abis.gradle, app/build.gradle, auth/build.gradle, database/build.gradle, dynamic_links/build.gradle, firestore/build.gradle, functions/build.gradle, instance_id/build.gradle, messaging/build.gradle, remote_config/build.gradle, storage/build.gradle
The most recent versions of the NDK don't support the "mips", "mips64", and "armeabi" ABIs, but we still do ship those with the binary C++ SDK to support older devices. This change adds a check to our Android gradle build, which determines whether a custom NDK is being used (as we do in our packaging step), and builds those additional ABIs if the NDK version is the one we expect.
Our custom Android build script supports building with NDK r16b to enable all 3 STL variants as well as the aforementioned older ABIs.
This change also includes an option to build the armeabi-v7a-hard ABI, which was removed a few years ago and subsumed into armeabi-v7a, and thus shouldn't normally be required. (But if you do need armeabi-v7a-hard for some reason, you can use NDK r11c.)
=> Build all Android ABIs available in NDK r16b.

firestore/CMakeLists.txt
Added newly created source files in 6.16.0 to CMake. This fixes linker issues when building Firestore on Android, noticed while running integration tests.
=> adding newly added sources for android builds

.github/workflows/android.yml, .github/workflows/cpp-packaging.yml, .github/workflows/desktop.yml, .github/workflows/integration_tests.yml, .github/workflows/ios.yml, build_scripts/android/install_prereqs.sh
Replaced "set-env" commands across our workflows with the Github Environment files syntax.
Fixes a security flaw outlined in,
https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w
=> replace set-env commands with github env file

.github/workflows/cpp-packaging.yml
This adds a file hash for the firebase_cpp_sdk.zip package, which will allow us to verify the generated package later (i.e. when it is put up for download):
- Log a SHA256 hash of the generated firebase_cpp_sdk.zip package, and add the hash as a downloadable artifact as well.
- Add a file to the generated package with a hash for every file contained in the package. In the integration test step, code has been added to verify every file's hash if this file exists and error out if any don't match.
Also, if the workflow is run with certain inputs to customize its behavior, this is now logged:
- If a run is made against a specific commit ID, log the commit ID.
- If a run is just to test an existing packaged SDK (public or from a previous run), log its source.
- If a run is set to preserve …
=> Add hash for generated C++ SDK package so we can verify the file later

.github/workflows/cpp-packaging.yml, .github/workflows/desktop.yml, .github/workflows/ios.yml, build_scripts/other/package.sh
Sets Xcode version to 11.7.
Also fixes include path in the final package, which is mistakenly include/include/firebase. This PR corrects it to include/firebase.
=> Fix final package to be usable on Mac

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml
The setting of these env vars was recently updated to use the new syntax. This does not work as-is on powershell due to encoding, as documented here:
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
As a result, the gCloud tools were not working on Windows as an env var needed to work around a known gCloud bug was not being set.
To fix this, we set the env var using bash.
=> Fix gCloud steps in integration tests on Windows

scripts/gha/build_testapps.py, scripts/gha/integration_testing/build_testapps.json, scripts/gha/integration_testing/config_reader.py
The testapp builder duplicated some vcpkg logic: this removes that duplication, instead relying on build_desktop.py's "vcpkg_step_only" mode, and some logic from utils.py
This fixes a break caused by a change in the structure of the vcpkg response files which was not reflected in this duplicated logic, and will prevent similar breakages in the future.
=> Deduplicate vcpkg logic in testapp builder

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml
This pixel 4 device seems to be getting unusual and inconsistent gmscore issues not replicable on other devices, even on the same API level.
Switch to a different default device to avoid these, at least as a temporary workaround.
=> Use Pixel 3, API 28 instead of Pixel 4, API 29

auth/integration_test/src/integration_test.cc
The use of a single phone number caused issues when multiple clients were running in the integration test CI framework. causing the PhoneAuth attempts to globber one another.  
Added 9 more phone numbers, and made the choice of the phone number to be random based on the time.
=> Added more test phone numbers.

.github/workflows/android.yml, .github/workflows/desktop.yml
We're experiencing queuing on GHA from trying to use too many machine resources. A disproportionate chunk of this is coming from Windows and its excessive build permutations.
Android on Windows has been broken for a while - temporarily removed until fixed.
For desktop, remove 6 of the permutations, leaving the two required ones: Release-x64-static and Debug-x86-dynamic.
=> Remove several Windows test jobs from pull requests

.github/workflows/cpp-packaging.yml, CMakeLists.txt, build_scripts/desktop/package.sh
Using the latest binutils causes blastdoor to create invalid Mac libraries that crash the linker. Until this is fixed in binutils, use an older version that is known to work.
Because this older version does not support thread-local storage on Mac, disable thread-local storage in our usage of websockets via a define at build time. This does not cause a problem because we only use websockets via the Firebase scheduler, which runs all websockets requests in a single worker thread.
=> Use an older version of binutils on Mac

scripts/gha/desktop_tester.py, testing/test_framework/src/firebase_test_framework.cc
Currently the logging behaviour for "debug" level logs is set to show them at the end of the integration test, if there were any failures. If the integration test prematurely ends (crash, failed assertion, or timeout), this results in them not showing up at all. In practice, this often leads to a lack of relevant logs to understand why a test didn't complete.
To fix this, the overall log level is changed from info to debug. This ensures debug logs are logged immediately, so a prematurely ended test won't prevent them from appearing.
This includes a fix to the desktop_tester script to capture logs in the event of a process timeout: previously, result.stdout was used, which doesn't get populated if the process timed out (resulting in missing logs). Instead, we access output from the error. …
=> Change integration test log level to "debug"

app/tests/heartbeat_info_desktop_test.cc, app/tests/util_test.cc, cmake/external/firestore.cmake, database/CMakeLists.txt, testing/util_android_test.cc, testing/util_ios_test.mm
- Updated Firestore depenency in cmake external to a the checksum for 7.0.0.
- Fixed gmock header issues.
=> Firestore Dependency update & gmock include fix

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml
Desktop integration testing was separated from the build script, but not applied to the testing in the packaging workflow (or possibly lost during merge conflict resolution). This applies it, consistent with the integration_tests.yml workflow.
Also updates the setup-msbuild action to 1.0.2 as 1.0.1 no longer works (this is consistent with other usages of the action in these workflows).
The change to integration_tests.yml removes redundant references to github.workspace (no behaviour change).
=> Minor fixes to testing in the packaging workflow

app/CMakeLists.txt, app/src/heartbeat_date_storage_desktop.cc, app/src/heartbeat_date_storage_desktop.h, app/tests/heartbeat_info_desktop_test.cc, app/tests/util_test.cc, cmake/external/firestore.cmake, database/CMakeLists.txt, testing/util_android_test.cc, testing/util_ios_test.mm
- Replaced std mutex with our own app mutex in app/src/heartbeat_date_storage_desktop.cc.
- Removed heartbeat code from Android builds.
=> Fixes for packaging steps

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml
When ${{ github.workspace }} gets resolved, it has windows separators in it, which are getting lost when passed as a flag to the Python script.
i.e. what starts as
D:\a\firebase-cpp-sdk\firebase-cpp-sdk
turns into
afirebase-cpp-sdkfirebase-cpp-sdk
Wrapping the value in quotes prevents these slashes from being lost.
=> Fix builds of windows integration tests caused by messed up path

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml
A small quality of life improvement. When opening the page to a failed job, Github Actions will automatically expand the last failing step. We can exploit this to automatically expand the summary step by forcing it to fail, which is the preferred starting point for figuring out what failed. Since we don't want to fail otherwise successful jobs, we only execute the summary step if a prior step failed. The summary is only needed when something fails.
This eliminates some navigation, as well as the knowledge burden of knowing to navigate to the summary step to get an overview of what went wrong.
=> Automatically expand summary step in failed jobs

.github/workflows/cpp-packaging.yml
Set the C++ Packaging workflow to run integration tests by default. Log a message if tests are skipped.
(We also check for a blank value because when running on merge or cron, all input params are blank.)
=> Run packaging integration tests by default

scripts/merge_libraries.py
This PR fixes Windows packaging by forcing the calls to "ar" to specify a --target, in the cases where there was previously an ambiguous target.
This also slightly speeds up packaging on Windows as it won't have to run every binutils command twice when an ambiguous format occurs.
=> Fix C++ Windows packaging

cmake/external/leveldb.cmake, cmake/external_rules.cmake
This fixes a linker error in Realtime Database on Windows.
Also, if we are using leveldb from Firestore, force it to use this same version by copying over our leveldb.cmake into Firestore in the post-external-download step.
=> Update to a newer version of LevelDB that no longer uses std::call_once on Windows.

build_scripts/desktop/get_variant.sh, release_build_files/CMakeLists.txt, release_build_files/readme.md
Also add a note to the readme for this and the previous Linux legacy/c++11 ABI change.
Finally, simplified the get_variant script a bit by having it force lower-case before checking build variant segments.
Note on binary compatibility: https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017
=> Rename the VS2015 directory to VS2019, since we now build the Windows libraries using VS 2019.

CMakeLists.txt, firestore/CMakeLists.txt
Force -D_WIN32_WINNT=0x0600 to be defined if building Firestore C++ for Windows.
This fixes the build of Firestore on Windows with the newly-added source files.
=> Add a define to Firestore C++ to work around a grpc Windows compile error.

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml, scripts/gha/build_testapps.py
The following changes have been made to make the build_testapps.py script easier to use.
1. Renamed "sdk_dir" to "packaged_sdk", and "root_dir" to "repo_dir", to be more intuitive.
2. packaged_sdk now set to None by default, instead of the current directory. This provides a more reliable way to tell if the intent is to build from source or from a packaged sdk.
3. --use_vcpkg flag removed. When building from source, vcpkg will be used, and when building from a packaged sdk, it will not. This is the intended behaviour: the flag was not providing a real option, just an opportunity to make mistakes when running the tool.
=> Simplify build_testapps.py flags

.github/workflows/cpp-packaging.yml, app/CMakeLists.txt, build_scripts/desktop/package.sh, cmake/external_rules.cmake, scripts/gha/build_desktop.py, scripts/merge_libraries.py
Specifying an explicit binutils format fixes an issue in Windows builds where some libraries would be autodetected, but then would create invalid output libraries since the target format wasn't specified.
This was causing a linker issue with absl in Firestore with vector deleting destructors not being found, because certain absl libraries were not created valid by merge_libraries. In particular, Windows libraries are now set to be output in pe-bigobj-x86-64/pe-bigobj-i386 format, since Firestore in particular has >65K sections and requires bigobj. There's no harm in making all the other libraries the same format.
This PR also adds a couple of flags to build_desktop.py:
- It adds support for performing a verbose build during packaging, in case it's needed for further debugging. 
- Adds a …
=> Allow packaging step to specify an explicit binutils format, and add some configuration options to build_desktop

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml
Current action is deprecated. Replacing with the new, non-deprecated one. 
Removes the following warning currently being spammed on the packaging and integration test workflows:
_Thank you for using setup-gcloud Action. GoogleCloudPlatform/github-actions/setup-gcloud has been deprecated, please switch to google-github-actions/setup-gcloud._
=> Replace deprecated action for setup-gcloud

app/CMakeLists.txt
FlatBuffers_Library_SRCS is not always set, so just list the source files directly.
=> Explicitly list the Flatbuffer source files

.github/workflows/integration_tests.yml
The OpenSSL build on Windows, for Windows, was failing to execute due to the VM image missing an OpenSSL installation and its runtime DLLs.
Added a build step to the GHA worfklow to use Choco to install openssl.
The database integration test still fails, but now due to a logical error that we should fix independently.
=> Add OpenSSL install step for windows builds

database/integration_test/src/integration_test.cc, firestore/integration_test/src/integration_test.cc, storage/integration_test/src/integration_test.cc
To avoid a race condition with signout/signin on Windows, refactor the tests a bit to minimize the number of times they initialize App and Auth. They now use a shared App and Auth instance for (pretty much) the entire run of the integration test, and only create a Database/Storage/Firestore instance for each test.
This also speeds up the tests significantly as they aren't waiting for a sign-in for every single one of the 30+ tests.
=> Refactor the RTDB, Storage, and Firestore integration tests a bit

database/integration_test/src/integration_test.cc, firestore/integration_test/src/integration_test.cc, storage/integration_test/src/integration_test.cc
This prevents us from leaving a ton of defunct anonymous users in the project for no reason.
=> Modify integration tests so that they delete the anonymous user they created.

admob/integration_test/src/integration_test.cc
The test is flaky and a proper fix is not forthcoming any time soon.
Any users affected by this issue can work around it by deleting BannerViews in the same thread in which they are created, so to get the tests green we are disabling this test until it can be properly fixed.
=> Temporarily disable the multithreaded delete test in the AdMob integration test.

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml
FTL is experiencing internal issues on certain iOS devices. For Googlers, this is b/178654295.
From experimentation, this appears to affect iOS 12+. This change picks iphone8, iOS 11.4. The default device for FTL is iphone8, 11.2. 11.2 is deprecated, so we pick 11.4.
Test run: https://github.com/firebase/firebase-cpp-sdk/actions/runs/518690509
=> Change iOS device used by integration tests to iphone8, version 11.4

admob/integration_test/src/integration_test.cc
The AdMob SDK crashes if you call Initialize and Terminate too quickly on a non-main thread. This happens in the integration test when skipping the interactive tests (e.g. when running on FTL).
=> Add a workaround for an AdMob race condition to integration test.

admob/integration_test/CMakeLists.txt, analytics/integration_test/CMakeLists.txt, app/integration_test/CMakeLists.txt, auth/integration_test/CMakeLists.txt, database/integration_test/CMakeLists.txt, dynamic_links/integration_test/CMakeLists.txt, firestore/integration_test/CMakeLists.txt, functions/integration_test/CMakeLists.txt, installations/integration_test/CMakeLists.txt, instance_id/integration_test/CMakeLists.txt, messaging/integration_test/CMakeLists.txt, remote_config/integration_test/CMakeLists.txt, storage/integration_test/CMakeLists.txt
Changed the search paths for the google-services.json file in
CMakeLists.txt files to use full paths instead of relative paths.
According to the CMake documentation, the `if (EXISTS ...)` condition is
only well defined for full paths. This might work on some platforms but
it failed in my tests on Windows.
=> Fixed issue with integration tests finding google-services.json

firestore/integration_test/CMakeLists.txt, remote_config/CMakeLists.txt
=> Remove extra inclusion of pb_common.c and pb_decode.c, to avoid multiple symbol definitions.

.github/workflows/cpp-packaging.yml
Several enhancements to reduce transient failures in the packaging step, and just make the workflow cleaner in general:
1. Delete build artifacts sooner, after they are no longer needed, to reduce the number of artifacts final-merge-packages has to download.
2. Update to the latest upload-artifact and download-artifact versions, which add better HTTP retry logic.
3. Switch to a newer version of the delete-artifact action that allows wildcards.
=> Improve how we deal with artifacts

admob/CMakeLists.txt, analytics/CMakeLists.txt, app/CMakeLists.txt, auth/CMakeLists.txt, database/CMakeLists.txt, dynamic_links/CMakeLists.txt, firestore/CMakeLists.txt, functions/CMakeLists.txt, installations/CMakeLists.txt, instance_id/CMakeLists.txt, messaging/CMakeLists.txt, remote_config/CMakeLists.txt, storage/CMakeLists.txt
=> Enable bitcode for iOS build.

remote_config/src/desktop/remote_config_desktop.cc
Previously was set to  "configns:firebase", now set to "firebase", which fixes a sporadic "Invalid Argument" error from the server.
=> Change invalid default remote config namespace

instance_id/integration_test/src/integration_test.cc, messaging/integration_test/src/integration_test.cc, remote_config/integration_test/src/integration_test.cc, storage/integration_test/src/integration_test.cc, testing/test_framework/src/firebase_test_framework.cc, testing/test_framework/src/firebase_test_framework.h
Allows you to retry Futures more than once, for handling transient failures.
Implemented in Remote Config integration test (for Fetch) and IID integration test (for DeleteId).
Also (not related to RunWithRetry), increase message timeout in Messaging test to help avoid flakes, and add a small delay in Storage's pause callback.
=> Deflake tests by adding RunWithRetry and changing test timeouts

cmake/external/firestore.cmake
This is the same as the version currently imported in google3 (see CL 359815696).
=> Bump Firestore version to 7.7.0

cmake/external/firestore.cmake
Using firestore version that has a fix for compiler errors seen on newer versions of gcc (sign-compare).
https://github.com/firebase/firebase-ios-sdk/commit/5f6febab5e133960ca8fc6d2639ea460253bc43a
=> update firestore version

storage/integration_test/src/integration_test.cc
This delay broke the Storage integration test on mobile, though it helps with flakes on desktop.
=> Remove the extra delay in storage integration test on mobile.

scripts/gha/print_matrix_configuration.py
Single source of truth for extracting Github workflow matrix values across all the workflows in our repo.
Usage examples
```
python scripts/gha/print_matrix_configuration.py -k os
python scripts/gha/print_matrix_configuration.py -w android -k os
python scripts/gha/print_matrix_configuration.py -w android -e 1 -k os
python scripts/gha/print_matrix_configuration.py -w integration_tests
--overrides os user_os1,user_os2 python_version 3.8 -k os
```
=> Python script to extract matrix values used in github workflows.

database/integration_test/src/integration_test.cc, database/src/desktop/core/event_registration.cc, database/src/desktop/core/event_registration.h, database/src/desktop/core/repo.cc, database/src/desktop/database_desktop.cc, database/src/desktop/database_desktop.h, database/src/desktop/query_desktop.cc, database/src/desktop/query_desktop.h, release_build_files/readme.md
Fixed a crash that can occur as a result of a race condition when
rapidly removing and deleting a listener.
When a listener is added or removed, it doesn't get added or removed
immediately. Instead, a transaction is scheduled to run at some point in
the future. If the developer adds and removes a listener in quick
succession and then deletes it, those scheduled callbacks might not run
until after the listener has already been deleted, resulting in calling
a member function of a now garbage pointer and crashing.
The solution is to immediately mark a listener as having been removed
from the main thread (as well as scheduling it to be removed from the
background thread, as it was already doing). Any new event that come in
on a listener that has been marked removed will be ignored. The …
=> Fixed race condition when removing listeners.

installations/src/android/installations_android.cc, remote_config/src/android/remote_config_android.cc
Inside android callback functions, the data_handle pointer needs to be delete.
=> Fix a memory leak in android task/callback pattern

release_build_files/Android/firebase_dependencies.gradle
Our public readme is slightly out of sync with the android dependency versions. This should fix the versions.
PiperOrigin-RevId: 356600386
=> Updating android dependencies versions for firebase-cpp-sdk.

remote_config/src/common.cc, remote_config/src/common.h, remote_config/src/include/firebase/remote_config.h
Changes FirebaseRemoteConfig to be used as an instanced class. Because static and instance methods cannot share the same signature, all the deprecated functions have been moved to a different class, FirebaseRemoteConfigDeprecated, so that users have an easier fix.
PiperOrigin-RevId: 356606757
=> Update the Unity Remote Config API

firestore/CMakeLists.txt, firestore/src/android/firestore_android.cc, firestore/src/android/jni_runnable_android.cc, firestore/src/android/jni_runnable_android.h, firestore/src/tests/android/jni_runnable_android_test.cc, firestore/src_java/com/google/firebase/firestore/internal/cpp/JniRunnable.java
Although there are no immediate uses of this class, it will be used by an upcoming unit test to verify the behavior of deleting a C++ Firestore instance on the main event thread (b/168628900).
PiperOrigin-RevId: 359263007
=> Firestore: Add JniRunnable, a Java Runnable class whose run() method invokes a C++ function.

firestore/src/android/exception_android.cc, firestore/src/android/exception_android.h, firestore/src/tests/firestore_test.cc, firestore/src/tests/query_test.cc, firestore/src/tests/validation_test.cc
See go/firestore-exceptions for details.
PiperOrigin-RevId: 357237099
=> Firestore: Translate Java exceptions to C++ exceptions of the right type

.github/workflows/integration_tests.yml, scripts/gha/print_matrix_configuration.py
Update our CI to run on FTL tests on iOS 12.4.
- Our minimum supported iOS version is now 12, so updating the CI from 11.7.
- The nightly build defaulted to iOS version "12" which is not available on the iphone8 FTL device. This caused or cron jobs to fail. Setting this to "12.4".
=> Updating Integration tests to FTL iOS Version 12.4

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml, database/integration_test/src/integration_test.cc, scripts/gha/trigger_workflow.py
This change updates the integration_tests workflow so that it can download a packaged SDK from GHA and build the integration tests against it, instead of against the SDK source.
With that change, we no longer need to duplicate the integration test code in the C++ packaging workflow.
Instead, the C++ packaging workflow directly invokes the integration_tests workflow at the end via the GitHub REST API.
(Note that because you cannot invoke another workflow with the same GITHUB_TOKEN that your workflow is already using due to a limitation in GitHub actions, the packaging workflow fetches a new GitHub App token to use for the request.)
=> Allow integration_tests workflow to run against a packaged SDK.

.github/workflows/android.yml, .github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml, build_scripts/android/install_prereqs.sh
There have been many workflow runs which have failed to download the NDK. I'mt not sure if this is due to its size or if the GHA Vms have a bad connection, etc, but more often than not when theres a failed download, it's the NDK.
Adding steps to cache the NDK to the Integration, Packaging and Android workflows. The NDK cache is based on the host OS and is based on the path of the android/install_prereqs.py script.
Includes some indentation changes to the Android Prereqs script, but no logical changes.
=> Deflake: Cache NDK Downloads

firestore/src/android/field_path_portable.cc, firestore/src/android/field_path_portable.h, firestore/src/android/firestore_android.cc, firestore/src/android/transaction_android.cc, firestore/src/common/field_path.cc, firestore/src/include/firebase/firestore/field_path.h, firestore/src/ios/user_data_converter_ios.cc, firestore/src/tests/validation_test.cc
Also fix transactions on Android to throw immediately when C++
exceptions are enabled. While this doesn't have much of an effect on
C++ users, this will make it possible for the Unity client to
synchronously throw in these cases, which is expected in C#.
Cloned from CL 355019084 by 'g4 patch'.
Original change by mcg@mcg:fig-export-firestore-change-286-4f589224b545:4324:citc on 2021/02/01 13:52:36.
PiperOrigin-RevId: 359824564
=> Firestore: Expand validation_test to cover other platforms

firestore/CMakeLists.txt, firestore/src/common/hard_assert_common.cc, firestore/src/common/hard_assert_common.h, firestore/src/ios/credentials_provider_desktop.cc, firestore/src/ios/document_change_ios.cc, firestore/src/ios/document_snapshot_ios.cc, firestore/src/ios/field_value_ios.cc, firestore/src/ios/firestore_ios.cc, firestore/src/ios/promise_factory_ios.h, firestore/src/ios/promise_ios.h, firestore/src/ios/query_ios.cc, firestore/src/ios/source_ios.h, firestore/src/ios/transaction_ios.cc, firestore/src/ios/user_data_converter_ios.cc, firestore/src/tests/util/integration_test_util.cc
Cloned from CL 357750787 by 'g4 patch'.
Original change by mcg@mcg:fig-export-firestore-92888e3fee62:4342:citc on 2021/02/16 10:30:15.
PiperOrigin-RevId: 360506827
=> Firestore: Migrate hard assertions to common infrastructure too

performance/example_usage.cc, performance/src/android/firebase_performance.cc, performance/src/android/http_metric.cc, performance/src/android/performance_android_internal.h, performance/src/android/trace.cc, performance/src/http_metric_test.cc, performance/src/include/firebase/performance.h, performance/src/include/firebase/performance/http_metric.h, performance/src/include/firebase/performance/trace.h, performance/src/ios/firebase_performance.mm, performance/src/ios/http_metric.mm, performance/src/ios/trace.mm, performance/src/performance_common.cc, performance/src/performance_common.h, performance/src/performance_test.cc, performance/src/trace_test.cc, performance/src_ios/fake/FIRHTTPMetric.h, performance/src_ios/fake/FIRHTTPMetric.mm, performance/src_ios/fake/FIRPerformance.h, performance/src_ios/fake/FIRPerformance.mm, performance/src_ios/fake/FIRPerformanceAttributable.h, performance/src_ios/fake/FIRTrace.h, performance/src_ios/fake/FIRTrace.mm, performance/src_java/fake/com/google/firebase/perf/FirebasePerformance.java, performance/src_java/fake/com/google/firebase/perf/FirebasePerformanceAttributable.java, performance/src_java/fake/com/google/firebase/perf/metrics/HttpMetric.java, performance/src_java/fake/com/google/firebase/perf/metrics/Trace.java, performance/stubs/http_metric_stub.cc, performance/stubs/performance_stub.cc, performance/stubs/trace_stub.cc
=> Added experimental Firebase Performance library code.

firestore/src/android/firestore_android.cc, firestore/src/tests/firestore_integration_test.cc, firestore/src/tests/firestore_integration_test.h, firestore/src/tests/firestore_test.cc, firestore/src_java/com/google/firebase/firestore/internal/cpp/FirestoreTasks.java
This is a port of cl/361792354:
Call `Terminate()` from `~FirebaseFirestore()` so that the cached Java instance will be cleared.
=> cl/361792354: Call `Terminate()` from `~FirebaseFirestore()` so that the cached Java instance will be cleared.

firestore/src/tests/android/promise_android_test.cc
This is a port of cl/362275804. The changelist in google3 fixed some build logic that caused some tests to be excluded from continuous runs. That allowed `promise_android_test.cc` to get stale and fail to build. This PR fixes the build error in `promise_android_test.cc` that was discovered by the build fix. The build fix itself is not relevant for GitHub.
=> Port cl/362275804: Fix build error in promise_android_test.cc

firestore/src/android/jni_runnable_android.cc, firestore/src/android/jni_runnable_android.h, firestore/src/tests/android/jni_runnable_android_test.cc, firestore/src_java/com/google/firebase/firestore/internal/cpp/JniRunnable.java
This is a port of cl/361876089:
JniRunnable: Fix a deadlock when Detach() is called from Run().
The deadlock occurred because Detach() attempted to acquire a write lock on a ReentrantReadWriteLock, which waits for all read locks to first be released; however, the Run() invocation on the call stack holds one of these read locks and therefore the read lock count will never reach zero causing the acquisition of the write lock to block forever.
This fix replaces the ReentrantReadWriteLock with standard Java synchronization. This implementation has the limitation that concurrent invocations of `run()` will be serialized with the advantage of a simple implementation. A more complicated version that allows concurrent invocations of `run()` is in a previous commit in this PR and is also recorded …
=> Port cl/361876089: JniRunnable: Fix a deadlock when Detach() is called from Run()

installations/src/installations_internal.h
The Installations header uses the platform information to include the correct sub header, so it needs to include the platform header itself.
=> Add platform include to installations header

.github/workflows/cpp-packaging.yml
Packaging workflow is currently failing due to running out of space while packaging Windows debug libraries. This fixes that by removing unneeded artifacts before the packaging begins.
=> Delete artifacts during packaging to save space.

.github/workflows/check-labels.yml, .github/workflows/integration_tests.yml, auth/src/ios/auth_ios.mm, scripts/gha/print_matrix_configuration.py
This PR adds some label-based triggers for integration tests, which allow the integration tests to be requested on a PR by setting the "tests-requested" label.
There are two modes for requesting tests, "quick" and "full":
"quick" tries to be clever and figure out a subset of APIs (and even platforms) to test. This heuristic is really simple right now (it just looks at directory names and, for platform, filenames) and if there is *any* ambiguity it will just run the normal suite of tests.
"full" just runs all the tests. Currently this is set to use an expanded test matrix, though this could be changed in the future.
The test workflow handles updating the labels and posting/updating a comment with the status of the integration tests as they run. All of the jobs that mess with labels and …
=> Trigger integration tests by setting a "tests-requested" label.

.github/workflows/integration_tests.yml, scripts/gha/summarize_test_results.py
Each test phase now uploads its results summary as a temporary artifact. A new summarize script looks at those artifacts and prints out a table and/or a github log entry at the end of the test run, if any builds or tests failed.
=> Improve integration test results reporting.

.github/workflows/integration_tests.yml
Test Result: https://github.com/firebase/firebase-cpp-sdk/actions/runs/709015656
=> fix bug: disable test on simulator

release_build_files/NOTICES
Performed a survey of external dependencies, those that we we use as submodules + those downloaded during our build process, and gathered their copyright and distribution notices.  Placed them in a single file in the build release file directory for distribution in our C++ SDK build archive.
Note: I removed the googletest notice as I don't believe we ship binaries that include the test sources.
=> Add 3rd Party Notices File for Packaged Releases

auth/src/ios/credential_ios.mm
To fix https://github.com/firebase/quickstart-unity/issues/954
=> Change GKLocalPlayer to be runtime referenced

firestore/integration_test_internal/src/firestore_test.cc
TestSnapshotsInSyncListenerFiresAfterListenersInSync and TestListenCanBeCalledMultipleTimes were flaky for three reasons.
Reason 1: The Semaphore was incorrectly initialized to zero, causing the subsequent call to Wait() to return immediately (instead of blocking, waiting for the call to Post()). The Semaphore should have been initialized to 1 to achieve this desired behavior.
Reason 2: The `std::vector<std::string> events` object was being accessed concurrently from multiple threads without any protection (e.g. from a Mutex), causing a race condition. I don't think that this race condition contributed to crashes; however, it is technically undefined behavior and is prudent to fix.
Reason 3: Both the Semaphore and the vector could potentially be used by the listener even after these …
=> Port cl/365835301: Fix flaky tests in firestore_test.cc.

cmake/external/nanopb.cmake, firestore/CMakeLists.txt
Add the new Firestore nanopb proto header path to the build.
Update NanoPB package to match Firestore version.
=> Fix Firestore 7.10.0 build in C++ SDK, and match NanoPB versions.

cmake/external/firestore.cmake, firestore/CMakeLists.txt, scripts/gha/summarize_test_results.py
This fixes a Windows build error in Firestore's core library.
Also fix log summarization (as a minor change) on Android.
=> Switch to a Firestore commit that fixes a Windows build error.

firestore/CMakeLists.txt
On Windows, absl's time_internal library does some stuff to achieve having a weak symbol. This completely fails in our binary builds.
Our binary builds don't care about zone_info_source_factory being a weak symbol. This change makes absl time_info no longer broken on Windows.
(Also, don't bother setting NOMINMAX on firestore_core directly - it already has it set internally.)
=> Prevent absl_time_zone from using weak symbols on Windows.

testlab/src/android/testlab.cc, testlab/src/android/util.cc, testlab/src/android/util.h, testlab/src/common/common.cc, testlab/src/common/common.h, testlab/src/common/scenario_result.fbs, testlab/src/desktop/testlab_desktop.cc, testlab/src/desktop/testlab_macos.h, testlab/src/desktop/testlab_macos.mm, testlab/src/include/firebase/testlab.h, testlab/src/ios/custom_results.h, testlab/src/ios/custom_results.mm, testlab/src/ios/testlab.mm
Added example implementation of Firebase Test Lab Game Loop library.
=> Added example implementation of Firebase Test Lab Game Loop library.

database/src/desktop/core/child_event_registration.cc, database/src/desktop/core/repo.cc, database/src/desktop/core/value_event_registration.cc, database/src/desktop/data_snapshot_desktop.cc, database/src/desktop/data_snapshot_desktop.h, database/src/desktop/database_reference_desktop.cc, database/src/desktop/persistence/persistence_manager.cc, database/src/desktop/query_desktop.cc, database/src/desktop/util_desktop.cc, database/src/desktop/util_desktop.h, database/tests/CMakeLists.txt, database/tests/desktop/core/sync_point_spec.fbs, database/tests/desktop/core/sync_point_spec.json, database/tests/desktop/core/sync_point_spec_test.cc
The new test suite is driven by the same master set of test cases that
drive SyncPoint tests on the iOS and Android implementation.
All tests are run twice, once at the root, and once again at a deeper
level, to ensure that the depth of the changes made does not matter.
Some tests currently fail. It's not clear if these are legitimate bugs
in the test suite, or if there are some bugs in the DB implementation.
For the time being, these tests are skipped using `GTEST_SKIP();` and
are annotated with whether they result in an assert being triggered or
just a failure due to unmet expectations. Fixes for these failing tests
will be made in follow-up PR's.
=> Added a new test suite for SyncPoints

ios_pod/Podfile
The previous version of Crashlytics (3.x) was missing some headers required for Unity builds.
=> Use Firebase/Crashlytics instead of Crashlytics.

android_build_files/android_abis.gradle
This fixes the following cryptic build error if the "ANDROID_NDK_HOME" environment variable is not set:
```
java.lang.NullPointerException: Cannot invoke method contains() on null object
```
=> Fix NPE in android_abis.gradle if ANDROID_NDK_HOME is not set

app/src/future_manager.h, app/src/include/firebase/internal/future_impl.h, app/src/include/firebase/util.h, app/src/reference_counted_future_impl.h, app/tests/CMakeLists.txt, cmake/future_lib.cmake
Googlers, see go/fix-data-races-in-firebase-future-c++-class
=> Remove playbilling

.github/workflows/checks.yml, scripts/format_code.py
In `scripts/format_code.py` the format code path correctly ignored Objective C headers.   However in no-format code path reported that some Objective C headers required formatting.   This PR fixes that discrepancy.
Additionally reordered the workflow steps so that the format check is the first check returned.   I felt like there's a usability problem with the label checks failing which isn't a hard failure, and it being the first reported result.  People clicking through to the Github Action log should see the actionable hard failures first.
=> Fix noformat_file / format_file discrepenency on iOS headers

.github/workflows/cpp-packaging.yml
STLPort is no longer included in the C++ SDK.
=> Remove STLPort from C++ packaging workflow.

.github/workflows/integration_tests.yml, scripts/gha/summarize_test_results.py
Add an input parameter to the integration tests workflow that allows you to specify a PR number (and optionally a commit hash within that PR) to run tests on.
This lets admins manually trigger integration tests on an external PR.
=> Allow running integration tests on an external PR

firestore/integration_test_internal/src/firestore_test.cc
This test was disabled after being ported from google3 because it was failing. It doesn't appear to fail anymore so I've re-enabled it. This PR is part of a larger effort to re-enable tests that were disabled after migrating to GitHub (Googlers can see b/183294303 for full context).
=> Re-enable FirestoreIntegrationTest.AuthWorks on MacOS

firestore/integration_test_internal/src/firestore_test.cc
This test was disabled after being ported from google3 because it was failing. It doesn't appear to fail anymore so I've re-enabled it. This PR is part of a larger effort to re-enable tests that were disabled after migrating to GitHub (Googlers can see b/183294303 for full context).
=> Re-enable FirestoreIntegrationTest.FirestoreCanBeDeletedFromTransaction

firestore/integration_test_internal/src/android/snapshot_metadata_android_test.cc
For some reason, the call to `env.FindClass()` was failing because it couldn't find the class. So I updated the code to use our new, modern JNI wrapper and it all worked. I'm not sure why but I'm happy with the result.
=> Fix Firestore's snapshot_metadata_android_test

testing/test_framework/src/firebase_test_framework.cc
Android and iOS do not have a way to take command-line arguments as input, and therefore there is no way to specify useful arguments like `--gtest_test_filter` when developing/debugging a specific test. This PR modifies `firebase_test_framework.cc` to at least provide an easy way to hardcode googletest arguments during development.
=> Provide an easy way to edit the googletest arguments in integration tests

app/src/app_android.cc, release_build_files/readme.md
This PR fixes a bug in `GetPlatformAppByName()` if an exception is thrown by the Java method call. The issue is that if an exception is thrown then the return value from `CallStaticObjectMethod()` is `NULL`... *except* on KitKat, where it appears to return garbage instead. This garbage value was being returned and the caller was incorrectly treating it as a valid object reference. The fix is to check if an exception was thrown and explicitly returning `NULL` in that case, instead of relying on the return value from `CallStaticObjectMethod()` being `NULL`.
This bug surfaced in the integration test `FirestoreIntegrationTest.CanPageThroughItems` which was crashing on KitKat. The root cause was that it was using a custom app name and the call to `GetPlatformAppByName()` was returning garbage …
=> Fix GetPlatformAppByName() crash on KitKat when the app was not found

.gitignore, scripts/gha/build_testapps.py
1. ios intermediary build folder change to "ios_build", which is already in .gitignore
2. add "testing/test_framework/external" to .gitignore
note: there are few test files not ignored, plans to resolve them in another ticket:
**/integration_test/Info.plist
**/integration_test/scr/integration_test.cc
=> Update gitingore for integration test

firestore/integration_test_internal/src/bundle_test.cc
The following two tests are being disabled:
- BundleTest.LoadBundleWithDocumentsAlreadyPulledFromBackend
- BundleTest.LoadedDocumentsShouldNotBeGarbageCollectedRightAway
=> Disable more bundles tests that fail in Windows CI

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml, scripts/gha/print_matrix_configuration.py
This change updates the Integration Test and Packaging workflows to use windows-2016 GHA runners.
Details:
GHA is rolling out a new version of windows server 2019 tools (windows-2019 / windows-latest alias) which produce a [C4255 warning](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4255?view=msvc-160) in BoringSSL.
BoringSSL is configured to error on all warnings, and so our current CI is broken until we can figure out the best way to properly patch the BorginSSL cmake configuration.
=> Fix BoringSSL Windows CI targets failing with windows-latest

messaging/AndroidManifest.xml, messaging/src/android/java/com/google/firebase/messaging/JobIds.java, messaging/src/android/java/com/google/firebase/messaging/cpp/RegistrationIntentService.java
There appears to be a hard-to-reproduce hang that in the
RegistrationIntentService, which is probably related to it being an
IntentService instead of a JobIntentService.
=> Converted RegistrationIntentService to a JobIntentService

generate_xml_from_google_services_json.py, release_build_files/readme.md
Made several fields in plist files optional. Most notably the
DATABASE_URL, because that was causing problems for users building for
iOS, but also the other fields like the STORAGE_BUCKET.
=> Database URLs are no longer necessary.

auth/integration_test/Podfile, auth/integration_test/integration_test.xcodeproj/project.pbxproj, auth/integration_test/integration_test.xcodeproj/project.xcworkspace/contents.xcworkspacedata, auth/integration_test/integration_test.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, auth/integration_test/integration_test_tvos/Assets.xcassets/AccentColor.colorset/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json, auth/integration_test/integration_test_tvos/Assets.xcassets/Contents.json, auth/integration_test/integration_test_tvos/Base.lproj/LaunchScreen.storyboard, auth/integration_test/integration_test_tvos/Base.lproj/Main.storyboard, auth/integration_test/integration_test_tvos/Info.plist, auth/integration_test/src/integration_test.cc, testing/test_framework/src/firebase_test_framework.h
Added a integration_test_tvos target to the auth integration test xcode project.  
Additonally added a SKIP_TEST_ON_TVOS to `testing/test_framework/src/firebase_test_framework.h` and used it to skip the phone auth test on tvOS.  Phone Auth is not supported on thhat platform.
To test this,
Make sure to have a valid GoogleService-Info.plist.
pod install
open integration_test.xcworkspace
Drag and drop firebase.xcframework and firebase_remote_config.xcframework
=> Auth Integration Test Project for tvOS

.github/workflows/cpp-packaging.yml, .github/workflows/desktop.yml, .github/workflows/integration_tests.yml, CMakeLists.txt, cmake/external/boringssl.cmake, scripts/gha/print_matrix_configuration.py, scripts/git/patches/boringssl/0001-disable-C4255-converting-empty-params-to-void.patch
This change fixes the boringSSL sources so that they no longer causes warnings on `windows-latest` runners.  
- Switched the boringSSL dependency to a git checkout instead of a tarball download.
- Created a git patch to alter boringSSL's cmake files, adding C4255 as a warning that shall be suppressed.
- Updated GHA configuration to use windows-latest again.  This was previously changed to windows-2016 since those tools didn't report C4255 as a warning. See #444 for more information about these reverted changes.
Other tests:
- [Packaging Test Run](https://github.com/firebase/firebase-cpp-sdk/actions/runs/922541062)
=> Git Patch BoringSSL to disable Windows build warnings/errors

scripts/format_code.py
This PR modifies `format_code.py` to print a unified diff of incorrectly-formatted files when both `-noformat_file` and `-verbose` are specified. This can make it easier to correct formatting problems based on the output from GitHub Actions without having to run `clang-format` yourself. This is especially useful if the version of `clang-format` on the GitHub Actions runners differs from that on your local machine, as they may produce different results.
Here is an example output of `format_code.py`:
```
$ python3 scripts/format_code.py -noformat_file -verbose -f example.cc                  
Found 1 file(s). Checking their format.
- Requires reformatting: "example.cc"
------ BEGIN FORMATTING DIFF OF example.cc
---
+++
@@ -1,9 +1,9 @@
+#include <string>
#include <vector>
-#include <string> …
```
=> format_code.py changed to print the diff when not formatting files inline

testing/sample_framework/src/ios/ios_app_framework.mm
The method `[FTAViewController viewDidLoad]` was incorrectly calling `[UIApplication openURL]` on a non-main thread. This resulted in the "main thread checker" in xcode always flagging this as an issue. It's also technically undefined behavior.
This PR fixes the bug by scheduling the `[UIApplication openURL]` to run on the main thread instead of calling it directly in a worker thread.
=> Fix FTAViewController incorrectly calling openURL off the main thread.

scripts/format_code.py, testing/test_framework/src/firebase_test_framework.h
There is a collection of generally-useful `static` methods in the `FirebaseTest` class that have `protected` visibility. These methods are generally useful even outside of subclasses, such as by "helper" functions defined in anonymous namespaces.
This PR increases the visibility of these `static` methods to `public` so that they can be used even outside of subclasses.
In the future, it may instead make sense to even move these static methods to free functions since there is no need that they be nested inside of `FirebaseTest`.
=> Increase the visibility of the static methods in FirebaseTest

.github/workflows/integration_tests.yml
Windows BoringSSL builds are now larger due to #454. The checkout & build partition **(D:)** hits capacity when attempting to install the Google Cloud SDK, which is what we use to upload the final integraion_test build artifacts to storage.
This change moves the arhives destined for GCS to the **C:** drive, then installs the Cloud SDK after they're off of **D:**.  The migration of the integration tests only occurs on Windows, for now.
Some notes:
- We can’t set the build_testapps.py’s  --output_directory flag to directly output to the **C:** directory because python’s relpath operations fail when working across different drives.
- The **github.workspace** env var can be changed to override check-out & installation paths, but the [GHA team notes potential unknown side …
=> Prevent Windows GHA CI disk exhausation

database/integration_test/Podfile, database/integration_test/integration_test.xcodeproj/project.pbxproj, database/integration_test/integration_test.xcodeproj/project.xcworkspace/contents.xcworkspacedata, database/integration_test/integration_test.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, database/integration_test/integration_test_tvos/Assets.xcassets/AccentColor.colorset/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json, database/integration_test/integration_test_tvos/Assets.xcassets/Contents.json, database/integration_test/integration_test_tvos/Base.lproj/LaunchScreen.storyboard, database/integration_test/integration_test_tvos/Base.lproj/Main.storyboard, database/integration_test/integration_test_tvos/Info.plist
integration_test XCode project update to support tvOS.
- added a tvOS target to the project.
- updated Podfile to include tvOS pods.
To test:
- cp your `GoogleService-Info.plist` to the `database\integration_test` directory.
- run `pod install` from `database\integration_test`. If you encounter errors run `pod repo update` and then attempt the `pod install` again.
- open `integration_test.xcworkspace`
- Drag and drop `firebase.xcframework`, `firebase_auth.xcframework` and `firebase_firestore.xcframework` with tvOS support into`Frameworks`.
All tests pass on simulator.
=> Database Integration tests on tvOS

remote_config/integration_test/src/integration_test.cc, remote_config/src/desktop/remote_config_desktop.cc, remote_config/src/include/firebase/remote_config.h, remote_config/src/remote_config.cc
To address issue https://github.com/firebase/quickstart-unity/issues/1067, fix a few bugs in remote config cpp sdk desktop.
1. Respect the ConfigSettings.minimum_fetch_interval_in_milliseconds in both FetchAndActivate() and Fetch()
2. Allow ConfigSettings.minimum_fetch_interval_in_milliseconds value to be 0 and applied as valid fetch interval.
3. Add integration test to verify.
=> [RemoteConfig] Fix the fetch interval bug

.github/workflows/cpp-packaging.yml, .github/workflows/desktop.yml, CMakeLists.txt, app/src/app_common.cc, app/src/app_common.h, scripts/gha/build_desktop.py
This allows the library to determine whether the library was built on
github or not.
=> Added build source to user agent string.

firestore/integration_test/src/integration_test.cc, firestore/integration_test_internal/src/integration_test.cc, firestore/src/common/document_change.cc, release_build_files/readme.md
Fix a bug where accessing `firebase::firestore::DocumentChange::npos` from a non-Android platform results in a linker error:
```
Undefined symbols for architecture x86_64:
"firebase::firestore::DocumentChange::npos", referenced from:
firebase_testapp_automated::FirebaseFirestoreBasicTest_TestDocumentChangeNpos_Test::TestBody() in integration_test.cc.o
ld: symbol(s) not found for architecture x86_64
```
Here is the declaration of `npos`:
https://github.com/firebase/firebase-cpp-sdk/blob/7ae9569eb9aa8628d7206bdf9553b2f639b02462/firestore/src/include/firebase/firestore/document_change.h#L66-L72
The fix is to add a *definition* of `npos` into the corresponding .cc file
=> Fix "Undefined symbols" linker error when DocumentChange::npos was used

remote_config/integration_test/src/integration_test.cc
Unblock integration test failure temporarily.
=> Disable remote config test interval for ios.

auth/src/include/firebase/auth/credential.h, firestore/src/include/firebase/firestore/collection_reference.h, firestore/src/include/firebase/firestore/document_reference.h, firestore/src/include/firebase/firestore/query.h, firestore/src/include/firebase/firestore/write_batch.h
Due to a bug (https://bugzilla.gnome.org/show_bug.cgi?id=735376) with
the version of doxygen we use to generate reference documentation,
forward declaration of template types results in them being
misclassified as singletons instead of classes. Omit the forward
declarations from Doxygen doc generation until we can update the version
of Doxygen that we use.
=> Workaround for issue with Doxygen doc generation.

firestore/integration_test_internal/AndroidManifest.xml, firestore/integration_test_internal/src/firestore_integration_test.cc, testing/sample_framework/src/android/android_app_framework.cc
Android: via extra `adb shell start ... -e USE_FIRESTORE_EMULATOR true`.
Desktop/iOS: set env var `USE_FIRESTORE_EMULATOR`.
=> Make it possible to run firestore tests against emulator

auth/src/include/firebase/auth/user.h
The behavior of ReauthenticateAndRetrieveData errors differ per platform. The preexisting comments documented the iOS behavior only, which was confusing for users of other platforms. 
This PR clarifies that errors on Android and Desktop platforms may cause the user to be signed out.
=> Update Auth ReauthenticateAndRetrieveData comments

scripts/gha/integration_testing/gameloop_android/app/build.gradle
Android gameloop app's gradle updated in this [PR](https://github.com/firebase/firebase-cpp-sdk/commit/845c94765f216dc32c941e5746591b893aeabee0#diff-f20a1dc9cbd9ce5c49bb9510d8e044e73ca9c758021c46707bb9fb70ce430d2b), resulting in Android Emulator test failed.
Should exclude gameloop app's from the updating.
=> Revert Android test tool dependency

installations/integration_test/src/integration_test.cc, messaging/integration_test/src/integration_test.cc, storage/integration_test/src/integration_test.cc, testing/test_framework/src/firebase_test_framework.h
Refactor a few tests to use [`RunFlakyBlock`](https://github.com/firebase/firebase-cpp-sdk/blob/acac90f7939f30a48c24ba5aa8d69fffe1ef6927/testing/test_framework/src/firebase_test_framework.h#L204):
- FirebaseInstallationsTest.TestGettingTokenTwiceMatches (copied logic from TestGettingIdTwiceMatches)
- FirebaseInstallationsTest.TestDeleteGivesNewTokenNextTime (copied logic from TestDeleteGivesNewIdNextTime)
- FirebaseMessagingTest.TestSendMessageToTopic
Additionally, to make the RunFlakyBlock tests more readable, this PR adds some FLAKY_EXPECT_* macros for equality and boolean values, as well as FLAKY_WAIT_FOR_COMPLETION. Refactored a Storage test to use these.
=> Deflake a few flaky tests

storage/integration_test/src/integration_test.cc
Add retry logic via RunFlakyBlock to TestPutFileAndGetFile.
=>  Add flaky test handling for Storage test

.github/workflows/integration_tests.yml, scripts/gha/summarize_test_results.py
Add back the logic: Test result report shows error if summary logs are missing.
If there are missing logs, then the error is **always** present at the **first line** of the table.
e.g.
| Failures | Configs |
|----------|---------|
| missing_log | [BUILD] [ERROR] [Windows] [boringssl]<br/> |
| firestore | [TEST] [ERROR] [Android] [windows] [emulator_target]<br/> |
=> Test result report missing logs

scripts/gha/github.py, scripts/gha/it_workflow.py
Existing http request flakiness in step "Update PR label and comment": https://github.com/firebase/firebase-cpp-sdk/runs/2945372323?check_suite_focus=true#step:18:23
Should be fixed now.
Add timeout (5s) to all GitHub REST API requests.
Add retry (3 times) to all query and update requests.
=> GitHub REST API: add timeout and retry 

scripts/gha/integration_testing/gameloop_android/app/src/androidTest/java/com/google/firebase/gameloop/GameLoopUITest.kt, scripts/gha/test_simulator.py
Retry (maximum 3 times) on error, e.g. integration test ended unexpectedly .
Won't retry if tests failed.
=> Add retry to iOS/tvOS/Android test on virtual device

analytics/integration_test/src/integration_test.cc, auth/integration_test/src/integration_test.cc, installations/integration_test/src/integration_test.cc, messaging/integration_test/src/integration_test.cc, storage/integration_test/src/integration_test.cc, testing/test_framework/src/firebase_test_framework.h
This PR adds  RunFlakyTestSection, which lets you use regular EXPECT macros.
(This touches some internal googletest stuff, so it may break in the future if we update to a later googletest version.)
Rather than using RunFlakyTestSection directly, you should use the following two macros:
FLAKY_TEST_SECTION_BEGIN();
FLAKY_TEST_SECTION_END();
This PR also cleans up existing tests to use this new method.
=> Clean up all flaky tests to be much more straightforward.

firestore/CMakeLists.txt, firestore/src/common/firestore_exceptions_common.h, firestore/src/main/firestore_exceptions_main.h
This simplifies the Unity build (the SWIG part of the build has issues with directly including a header that comes from the iOS repo).
=> Add a "wrapper" header that includes `firestore_exceptions.h` from the iOS repo

messaging/integration_test/src/integration_test.cc
Sometimes it can take a while to get the token, and the first attempt fails.
=> Add flaky retry logic for waiting for token in Messaging.

.github/workflows/integration_tests.yml
Fix for bug in https://github.com/firebase/firebase-cpp-sdk/runs/3089608121
=> After a branch is deleted, force quick tests to run the full suite.

firestore/integration_test_internal/src/bundle_test.cc
They are flaky because Android SDK does not guarantee all progress callbacks are *complete* before the task resolves.
Whether or not it should guarantee this is another topic.
=> Fix flaky bundle tests.

.github/workflows/integration_tests.yml, scripts/gha/print_matrix_configuration.py
This is a quick fix that integration test workflow exclude tvOS build & test for certain apis (e.g. admob, analytics, messaging, etc.)
"admob,analytics" not trigger tvos: https://github.com/firebase/firebase-cpp-sdk/actions/runs/1046072350
"analytics,auth" trigger tvos: https://github.com/firebase/firebase-cpp-sdk/actions/runs/1046073504
Note that the `build_testapps` script also need to handle this type of exclusion. But I will fix it in a separate PR.
=> Integration test workflow exclude tvOS build & test for certain apis

firestore/CMakeLists.txt, firestore/src/include/firebase/firestore/field_value.h, release_build_files/readme.md
Firestore has been building with INTERNAL_EXPERIMENTAL=1 for quite some time. These methods should always be exposed. Test coverage for them is available in field_value_test.cc and numeric_transforms_test.cc.
=> Remove unnecessary guard around FieldValue::Increment.

scripts/gha/test_simulator.py
Test on Simulator/Emulator crash when missing test log:
https://github.com/firebase/firebase-cpp-sdk/runs/3102595029?check_suite_focus=true#step:6:2642
`test_validation.validate_results_cpp` doesn't handle None type.
`test_validation. validate_results` handle None type, use this function instead.
=> [Bugfix] Test on Simulator/Emulator crash when missing test log

firestore/integration_test_internal/src/util/integration_test_util.cc
In the `TestFriend::CreateTestFirestoreInternal()` method defined in [integration_test_util.cc](https://github.com/firebase/firebase-cpp-sdk/blob/edad366983e6f4e7d8a1c3823d95c48c791a8853/firestore/integration_test_internal/src/util/integration_test_util.cc#L25) the expression `sizeof(FirestoreInternal)` is `116`.
In contrast, in [firestore_android.cc](https://github.com/firebase/firebase-cpp-sdk/blob/edad366983e6f4e7d8a1c3823d95c48c791a8853/firestore/src/android/firestore_android.cc#L243) the expression `sizeof(FirestoreInternal)` is `128`.
Before `bundle_listeners_mutex_` and `bundle_listeners_` were added to `FirestoreInternal` in https://github.com/firebase/firebase-cpp-sdk/pull/394 the expression `sizeof(FirestoreInternal)` was `112`.
So we were basically getting lucky that the ODR …
=> Fix ODR violation of FirestoreInternal on Android in integration_test_util.cc

testing/test_framework/src/firebase_test_framework.cc
According to https://man7.org/linux/man-pages/man2/execve.2.html, 
> The argv array must be terminated by a NULL pointer.  (Thus, in the new program, argv[argc] will be NULL.)
However, it appears that the `argv` specified to `common_main()` is not terminated in this way, at least on Android. This causes googletest's `ParseGoogleTestFlagsOnly()` function to read past the end of `argv`.
https://github.com/google/googletest/blob/8d51ffdfab10b3fba636ae69bc03da4b54f8c235/googletest/src/gtest.cc#L6634-L6649
This doesn't usually lead to issues; however, when run with Address Sanitizer this causes a crash since it is technically referencing unallocated memory.
This PR works around this by explicitly adding a null terminator to `argv`.
Googlers can see b/192351260#comment11 for more details.
=> Ensure that argv specified to googletest has a null terminator.

CMakeLists.txt
Fix for #523, error building for Android when source path contains regex meta characters (e.g. +).
=> Fix regex replacement to properly quote meta characters.

firestore/integration_test_internal/src/cleanup_test.cc, firestore/src/common/futures.h, firestore/src/include/firebase/firestore/document_change.h, firestore/src/include/firebase/firestore/document_reference.h, firestore/src/include/firebase/firestore/document_snapshot.h, firestore/src/include/firebase/firestore/field_path.h, firestore/src/include/firebase/firestore/field_value.h, firestore/src/include/firebase/firestore/listener_registration.h, firestore/src/include/firebase/firestore/query.h, firestore/src/include/firebase/firestore/query_snapshot.h, firestore/src/include/firebase/firestore/write_batch.h, release_build_files/readme.md
Also improve the error message contained in the invalid futures returned from invalid objects.
Addresses b/172570071 and b/157227167.
=> Add `is_valid` methods to the public API classes that can be in an invalid state

firestore/integration_test_internal/src/bundle_test.cc
Fix a heap-use-after-free bug in [`BundleTest.CanDeleteFirestoreFromProgressUpdate`](https://github.com/firebase/firebase-cpp-sdk/blob/8f6bb51314f2710e120a19c372d3ca6b365c5f4d/firestore/integration_test_internal/src/bundle_test.cc#L168-L198).
Here is the relevant code from the test that is problematic:
```
172 std::promise<void> db_deleted;
173 std::vector<LoadBundleTaskProgress> progresses;
174 Future<LoadBundleTaskProgress> result =
175     db->LoadBundle(bundle, [this, db, &progresses, &db_deleted](
176                                const LoadBundleTaskProgress& progress) {
177       progresses.push_back(progress);
178       // Delete firestore before the final progress.
179       if (progresses.size() == 3) {
180         DeleteFirestore(db);
181         db_deleted.set_value();
182 …
```
=> Fix a use-after-free bug in BundleTest.CanDeleteFirestoreFromProgressUpdate

.github/workflows/integration_tests.yml, scripts/gha/it_workflow.py, scripts/gha/test_lab.py, scripts/gha/test_simulator.py
1. Reset Android Emulator on test errors (fix [error](https://github.com/firebase/firebase-cpp-sdk/runs/3160571123?check_suite_focus=true#step:7:1595))
2. Create directory if not exist (fix [error](https://github.com/firebase/firebase-cpp-sdk/runs/3160481427?check_suite_focus=true#step:10:17))
3. Insert two newline after markdown table (fix [report](https://github.com/firebase/firebase-cpp-sdk/issues/464#issue-919307237))
4. Print out full integration test logs as required.
=> Reset Android Emulator on test errors

firestore/src/main/collection_reference_main.h, firestore/src/main/converter_main.h, firestore/src/main/create_credentials_provider.h, firestore/src/main/create_firebase_metadata_provider.h, firestore/src/main/credentials_provider_desktop.h, firestore/src/main/document_change_main.h, firestore/src/main/document_reference_main.h, firestore/src/main/document_snapshot_main.h, firestore/src/main/field_value_main.h, firestore/src/main/firebase_metadata_provider_desktop.h, firestore/src/main/firestore_main.h, firestore/src/main/listener_main.h, firestore/src/main/listener_registration_main.h, firestore/src/main/promise_factory_main.h, firestore/src/main/promise_main.h, firestore/src/main/query_main.h, firestore/src/main/query_snapshot_main.h, firestore/src/main/set_options_main.h, firestore/src/main/source_main.h, firestore/src/main/transaction_main.h, firestore/src/main/user_data_converter_main.h, firestore/src/main/util_main.h, firestore/src/main/write_batch_main.h
This will help avoid ODR violations like the one fixed by #559.
=> Cause Firestore build error if non-Android headers get included in an Android build

firestore/integration_test_internal/CMakeLists.txt, firestore/integration_test_internal/src/android/promise_android_test.cc, firestore/integration_test_internal/src/android/promise_factory_android_test.cc, firestore/integration_test_internal/src/firestore_test.cc, firestore/integration_test_internal/src/source_test.cc, firestore/src/android/firestore_android.h, firestore/src/android/promise_android.h, firestore/src/android/promise_factory_android.h
This fixes a crash on Android that occurs if the `Firestore` instance is deleted from an "OnCompletion" handler attached to a `Future` returned from `RunTransaction()`. The issue is that in the bowels on the code that manages `Future` objects it will end up using a deleted `FirestoreInternal` object when the completion completes. The fix is to null out the `FirestoreInternal` pointer when it is deleted and avoid using it thereafter.
This fix also fixes a crash that was occurring in `SourceTests`. Those tests are re-enabled by this PR.
=> Fix ReferenceCountedFutureImpl to avoid using FirestoreInternal after its deletion.

firestore/CPPLINT.cfg
The new `CPPLINT.cfg` just disables some noisy checks:
* `runtime/references` - This category produces warnings like `Is this a non-const reference? If so, make const or use a pointer: TestData& test_data`
* `build/c++11` - This category produces warnings like `<mutex> is an unapproved C++11 header.`
=> Add firestore/CPPLINT.cfg

.github/workflows/checks.yml
All PRs merging to `main` must either modify `release_build_files/readme.md` or contain the label `skip-release-notes`.
=> Add check for release notes update.

storage/integration_test/src/integration_test.cc
These two Storage tests perform network operations (PutBytes and Delete) and should use RunWithRetry.
=> Deflake TestInvalidatingReferencesWhenDeletingStorage and App

database/integration_test/src/integration_test.cc
The iOS SDK's .info/connected implementation sometimes fails, so add some flaky retry logic (but only when running on iOS).
=> Add retry to RTDB .info/connected test on iOS.

auth/src/android/common_android.cc, auth/src/include/firebase/auth/types.h
Add `ERROR_UNSUPPORTED_PASSTHROUGH_OPERATION` and `ERROR_TOKEN_REFRESH_UNAVAILABLE` error codes.
Note: Also fixed a typo in the C++ error code mapping for `ERROR_USER_CANCELLED`.
Corresponding Android change in cl/385610798.
=> Define new error codes for passthrough errors.

firestore/src/main/transaction_main.cc
Fix the following build error in the downstream Unity SDK builds for iOS:
```
Undefined symbols for architecture arm64:
"firebase::firestore::util::internal::StringFormatPieces(char const*, std::initializer_list<absl::string_view>)", referenced from:
std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > firebase::firestore::util::StringFormat<char const*>(char const*, char const* const&) in libFirebaseCppFirestore.a(firestore_main.o)
firebase::firestore::TransactionInternal::ValidateReference(firebase::firestore::DocumentReference const&) in libFirebaseCppFirestore.a(transaction_main.o)
void firebase::firestore::util::ThrowInvalidArgument<>(char const*) in libFirebaseCppFirestore.a(transaction_main.o)
ld: symbol(s) not found for architecture arm64
clang: …
```
=> Replace HARD_ASSERT with SIMPLE_HARD_ASSERT to fix absl linker breakage.

firestore/src/main/firestore_main.cc, firestore/src/main/transaction_main.cc
This a follow-up fix to #616 which additionally replaces `ThrowInvalidArgument` with `SimpleThrowInvalidArgument` to avoid absl-related linker errors in the Unity SDK for iOS.
The "style" of the changes made in this PR were based on those made in other files, such as:
https://github.com/firebase/firebase-cpp-sdk/blob/cebf363f7b25a7c8f200d1381159784df7ee52b3/firestore/src/main/query_main.cc#L196-L206
Googlers can see cl/289114361 for the introduction of `SimpleThrowInvalidArgument` for context.
=> Replace ThrowInvalidArgument with SimpleThrowInvalidArgument to fix iOS absl linker error in Unity SDK

.github/workflows/update-dependencies.yml
update-dependencies will be triggered by other projects (e.g. firebase-ios-sdk once https://github.com/firebase/firebase-ios-sdk/pull/8654 goes in). This adds an optional comment that will be included in the created PR, to make it clear what triggered the update.
=> Add a comment field, for when update-dependencies is triggered by others.

.github/workflows/integration_tests.yml, scripts/gha/it_workflow.py, scripts/gha/print_matrix_configuration.py
Combined "check_trigger" job and "prepare_matrix" job into "check_and_prepare" job.
Added "trigger" env variable. Apply "expanded_matrix, minimal_matrix, auto_diff" with different triggers accordingly.
Removed "auto_diff" from manual trigger, because the logic doesn't work. (Always override by inputs.)
Add presubmit(push) trigger, which run linux firestore with ccache. 
presubmit check: [without ccache](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1236217489) 35 mins vs [with ccache](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1236567562) 18 mins
To understand different [triggers](https://g3doc.corp.google.com/firebase/testing/g3doc/sdk/games-cpp.md?cl=head#ci-triggers).
TODO: Will add branch_protection_rules "build-desktop-ubuntu-latest-openssl" and …
=> Add presubmit trigger with ccache in linux firestore

scripts/gha/print_matrix_configuration.py, scripts/gha/test_simulator.py
Updated the FTL Android device. Now messaging pass the tests.
Wait longer for Android emulator booting. 
Test on Emulators all passed. (less flaky): 
https://github.com/firebase/firebase-cpp-sdk/actions/runs/1243299829
https://github.com/firebase/firebase-cpp-sdk/actions/runs/1243298994
https://github.com/firebase/firebase-cpp-sdk/actions/runs/1243097033
=> De-flake integration tests on Android devices

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml
${{ github.event.pull_request.merged }}'s value could be: true, false, empty. When it's empty, there is an error.
fix bug: https://github.com/firebase/firebase-cpp-sdk/runs/3631754439?check_suite_focus=true#step:3:41
Also change the "sdk" flag value to more descriptive "nightly-packaging"
=> Fix integration test check step

.github/workflows/integration_tests.yml
1. Removed synchronize trigger check (desktop/linux/Firestore emulator) logic from integration test workflow
2. Reverted the logic: now label trigger cancel other workflows
=> Remove synchronize trigger check from integration test workflow

admob/CMakeLists.txt, admob/integration_test/src/integration_test.cc, admob/src/android/ad_request_converter.cc, admob/src/android/ad_request_converter.h, admob/src/android/admob_android.cc, admob/src/android/admob_android.h, admob/src/android/banner_view_internal_android.cc, admob/src/android/banner_view_internal_android.h, admob/src/android/interstitial_ad_internal_android.cc, admob/src/common/admob_common.cc, admob/src/common/banner_view.cc, admob/src/common/banner_view_internal.h, admob/src/include/firebase/admob/banner_view.h, admob/src/include/firebase/admob/types.h, admob/src/ios/FADAdSize.h, admob/src/ios/FADAdSize.mm, admob/src/ios/FADBannerView.mm, admob/src/ios/FADRequest.h, admob/src/ios/FADRequest.mm, admob/src/ios/banner_view_internal_ios.h, admob/src/ios/banner_view_internal_ios.mm, admob/src/ios/interstitial_ad_internal_ios.mm, admob/src/stub/banner_view_internal_stub.h
Updated the AdSize and AdRequest structures:
- Converted them to classes.
- AdRequest now has methods to manipulate the content url, keywords and network extras.  
- Extras are are now collections with mediation class names keys.  The class names now dynamically resolved to jclasses on on Android and GADSize objects on iOS, as these objects are required as part of the Admob phone SDK API when setting extras.
- AdSize now provides methods for Adaptive sizes, and includes constants for common ad sizes.
Banner and Interstitial ads were updated to use these new structures.
Updated Itests
- Some unit testing is done on these structures.
- Added pauses between banner ad move commands as they were moving too quickly for Android phones to properly render them (they flashed as blank black boxes.) …
=> Admob - AdSize and AdRequest updates

messaging/src/android/cpp/messaging.cc, release_build_files/readme.md
When firebase::messaging::Terminate is called while there are still pending tasks left a null pointer exception is causing an ANR on Andriod.
FutureData is destroyed before calling util::Terminate which in turn will try to cancel all pending callbacks. This will call cancel() in JniResultCallback.java which will lock a mutex and callback into C++ using the JniResultCallback_nativeResult function. Depending on the task canceled it will call into different callbacks in messaging.cc and some of them as for example CompleteStringCallback are using FutureData which has already been destroyed. This will cause the thread to stop and the mutex in JniResultCallbak.java to remain locked. The next message that either completes or fails will now end up in a dead lock causing an ANR.
The proposed fix …
=> Fix crash in Messaging on Android when Terminate is called while tasks are still pending.

app/src/include/google_play_services/availability.h
Fix app build for ```Android``` against prebuilt Firebase C++ SDK.
Android NDK 21 says: ```fatal error: 'app/src/include/firebase/future.h' file not found```
Building was tested on my local computer.
Look at the files in ```app/src/include/firebase/``` directory.
File doesn't contain ```app/src/include/``` prefix inside ```#include``` paths.
Also removing the prefix ```app/src/include/``` from line ```25``` of ```app/src/include/google_play_services/availability.h``` has solved my build problem.
=> Fix app build for Android against prebuilt version

.github/workflows/integration_tests.yml, scripts/gha/integration_testing/gameloop_android/build.gradle, scripts/gha/test_simulator.py
Test on Emualtor sometimes failed when install Android app. https://github.com/firebase/firebase-cpp-sdk/runs/4078767834?check_suite_focus=true
```
Install testapp: adb install /Users/runner/work/firebase-cpp-sdk/firebase-cpp-sdk/testapps/firestore/iti-debug.apk
cmd: Failure calling service package: Broken pipe (32)
adb: failed to install /Users/runner/work/firebase-cpp-sdk/firebase-cpp-sdk/testapps/firestore/iti-debug.apk: cmd: Failure calling service package: Broken pipe (32)
Performing Streamed Install
```
This article suggests delete the old emulator and create a new one :
https://medium.com/@aedwin905/solved-failure-calling-service-package-broken-pipe-32-3b860c7e04bb
Also saw some errors when downloading emulator, uninstalling apps.
Thus, I made the following changes:
1. For critical …
=> Fix test on emulator workflow failures

.github/workflows/cpp-packaging.yml, scripts/gha/github.py, scripts/gha/trigger_workflow.py
Trigger workflow move github api cod to github.py
***
[Packaging workflow](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1451270647) triggers [Integration test workflow](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1451505808).
***
***
=> Trigger workflow move github api cod to github.py

app/src/include/firebase/future.h, app/src/include/firebase/internal/future_impl.h, release_build_files/readme.md
The `FutureBase` class has two data members that can be accessed concurrently from multiple threads without any synchronization: `api_` and `handle_`. This data race was detected by the thread sanitizer.
Although there are no known customer reports of crashes resulting from this data race, a recent continuous integration run crashed in Firestore with a null pointer dereference in the following stack trace:
```
firebase::FutureBase::Release()
firebase::FutureBase::~FutureBase()
firebase::Future<void>::~Future()
firebase::firestore::FirestoreIntegrationTest_FirestoreCanBeDeletedFromTransaction_Test::TestBody()
```
The test in question is `FirestoreCanBeDeletedFromTransaction`: https://github.com/firebase/firebase-cpp-sdk/blob/9efb188a6f3c69d26c0d298a1c8a5fd17ebff960/firestore/integration_tes …
=> Fix a data race that could manifest as null pointer dereference in FutureBase::Release()

admob/CMakeLists.txt, admob/integration_test/src/integration_test.cc, admob/src/android/admob_android.cc, admob/src/android/rewarded_ad_internal_android.cc, admob/src/android/rewarded_ad_internal_android.h, admob/src/common/admob_common.cc, admob/src/common/banner_view.cc, admob/src/common/full_screen_ad_event_listener.cc, admob/src/common/full_screen_ad_event_listener.h, admob/src/common/interstitial_ad.cc, admob/src/common/interstitial_ad_internal.cc, admob/src/common/interstitial_ad_internal.h, admob/src/common/rewarded_ad.cc, admob/src/common/rewarded_ad_internal.cc, admob/src/common/rewarded_ad_internal.h, admob/src/include/firebase/admob.h, admob/src/include/firebase/admob/rewarded_ad.h, admob/src/include/firebase/admob/types.h, admob/src/ios/rewarded_ad_internal_ios.h, admob/src/ios/rewarded_ad_internal_ios.mm, admob/src/stub/rewarded_ad_internal_stub.h, admob/src_java/com/google/firebase/admob/internal/cpp/ConstantsHelper.java, admob/src_java/com/google/firebase/admob/internal/cpp/InterstitialAdHelper.java, admob/src_java/com/google/firebase/admob/internal/cpp/RewardedAdHelper.java, app/CMakeLists.txt
- Implemented RewardedAd on Android, and created stubs for iOS and Desktop builds.
- Revamped C++ JNI function signatures to have much shorter names, and to reuse functions common to interstitial and rewarded ads.
- Created a new internal base class for full screen event listeners to share its implementation across RewardedAds and InsterstitialAds.  This allows us to reuse some JNI callback functions.
- Grouped those integration tests which require user interaction so that they execute one after the next, and front load them to the start of the itest flow (after a few quick sanity checks).  This should make running the manual tests easier.
***
**[iTest …
=> RewardedAds for Android

release_build_files/readme.md
I had originally thought that the issue was specific to Android, because the bug only surfaced on Android; however, it indeed affects all platforms.
=> Remove "Android" tag from the release notes entry for #747

admob/integration_test/src/integration_test.cc, admob/src/common/admob_common.cc, admob/src/include/firebase/admob/types.h
Simply rename the constant to match AdMob naming conventions.
***
CI Tests only.
***
***
=> Rename Admob LeaderBoard AdSize to Leaderboard

admob/CMakeLists.txt, admob/integration_test/src/integration_test.cc, admob/src/ios/FADRewardedAdDelegate.h, admob/src/ios/FADRewardedAdDelegate.mm, admob/src/ios/rewarded_ad_internal_ios.h, admob/src/ios/rewarded_ad_internal_ios.mm
Updates the iOS implement to be able to display rewarded ads.
***
Local testing with the itests on an iOS device.
[iTest Ci](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1482768470)
***
***
=> AdMob Rewarded Ads on iOS

messaging/src/android/cpp/messaging.cc, release_build_files/readme.md
In the unity quick start forum there is a bug report about messaging also crashing during startup. https://github.com/firebase/firebase-unity-sdk/issues/73 . I have not been able to reproduce this but as it looked a lot like the shutdown crashes I thought I would have a quick look. 
During the initialisation() function it calls SetTokenRegistrationOnInitEnabled() which in turn trickles down to a GetToken() call and if the Task is quick enough (i.e if we don't have an internet connection maybe?) it will trigger the CompleteStringCallback before FutureData::Create has been called.
Creating the FutureData before calling SetTokenRegistrationOnInitEnabled() is a "potential" fix as I have not seen the actual crash myself.
***
> Describe …
=> Messaging crash during initialization

firestore/src/main/credentials_provider_desktop.cc, firestore/src/main/credentials_provider_desktop.h
FIxes https://github.com/firebase/firebase-cpp-sdk/issues/729
=> Don't redeclare inherited state in CredentialsProviderDesktop

.github/workflows/cpp-packaging.yml, scripts/gha/build_desktop.py
Remove intermediate build files during desktop packaging step.
***
Packaging workflow run.
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can …
=> Reduce disk space usage when packaging the built SDK

scripts/gha/print_matrix_configuration.py
Current `android-latest` devices not responding. https://github.com/firebase/firebase-cpp-sdk/runs/4298317233?check_suite_focus=true
Update FTL `*-latest `devices to the latest. Also, updated the `android-target` device.
***
Tested manually: https://github.com/firebase/firebase-cpp-sdk/actions/runs/1495928800
Also, tested with label: see comment below.
***
***
=> Update FTL devices to run tests

.github/workflows/update-dependencies.yml
When updating the iOS SDK dependency, it should also grab Analytics header files, which are used for generating constants.
***
Running the Update Dependencies workflow.
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase …
=> Add Analytics header update to iOS SDK update.

.github/workflows/cpp-packaging.yml, .github/workflows/desktop.yml, .github/workflows/integration_tests.yml, release_build_files/readme.md, scripts/gha/print_matrix_configuration.py
GitHub Mac runners are dropping Xcode 12.2 support. Xcode 12.4 is the minimum Xcode 12 version available.
Also updates the integration test workflow to respect the xcode version.
***
Running cpp-packaging and integration_tests workflows.
***
*** …
=> Change Xcode version from 12.2 to 12.4 to ensure GitHub support.

release_build_files/readme.md, remote_config/src/desktop/remote_config_desktop.cc
Currently, a value expressed in milliseconds is directly assigned to a variable
which is supposed to store seconds and it's later converted to mills again.
Thus, convert properly upon assignment
Currently, a value expressed in milliseconds is directly assigned to a variable
which is supposed to store seconds and it's later converted to mills again.
Thus, convert properly upon assignment
***
Setting different timeouts via RemoteConfig::SetConfigSettings(), calling RemoteConfig::FetchAndActivate() and verifying if an expected update was indeed fetched …
=> Properly convert milliseconds to seconds

app/src/invites/ios/invites_ios_startup.mm, release_build_files/readme.md
Don't call LogDebug during swizzling.
***
Can't repro the iOS 15 issue but this won't make things any worse...?
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request …
=> Change LogDebug to NSLog in app's swizzling code.

.github/workflows/update-dependencies.yml
The header files in the Analytics iOS SDK that we copy over into our SDK don't have a copyright line. Add one.
***
Run "Update Dependencies" workflow, which generated #781.
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase …
=> Add copyright line when importing Analytics iOS headers, if missing

.github/workflows/android.yml
Make sure to use xcode-select to choose the correct Xcode in the Android workflow as well.
While this doesn't affect the Android build itself, it can affect some of the prerequisites; we should ensure that the Xcode version doesn't change unless we explicitly change it.
***
Run android.yml workflow.
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk …
=> Also set Xcode version explicitly in Android workflow.

.github/workflows/integration_tests.yml, build_scripts/android/install_prereqs.sh
Install deps step can be flaky and break the build. [e.g.](https://github.com/firebase/firebase-cpp-sdk/runs/4392718616?check_suite_focus=true)
Add timeout & retry
***
See the comment section
***
***
=> Timeout & retry "install integration test deps" step

analytics/integration_test/src/integration_test.cc
Since updating to Firebase iOS 8.10.0, the Analytics integration test finishes too quickly for FTL. This adds a delay to the end of the app.
***
Integration tests run.
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs …
=> Add a delay to the Analytics test app.

scripts/gha/summarize_test_results.py
In the report, if test failed on all devices. Use [All test devices] instead of listing each devices
e.g.
[emulator_target, emulator_latest, android_target, android_latest, emulator_32bit]
-> [All 5 android_device]
[emulator_target,  android_target, android_latest, emulator_32bit]
-> [All 2 FTL Devices, emulator_target, emulator_32bit]
***
***
*** …
=> In the test report, if test failed on all devices. Mark [All x test devices] 

messaging/samples/AndroidManifest.xml, messaging/samples/src/java/com/google/firebase/messaging/cpp/samples/MyActivity.java
As of Firebase C++ SDK 7.1.0, we started using JobIntentService for scheduling jobs. This change requires a few additional modifications to AndroidManifest.xml and a new way of starting a background service.
These changes were done to the old repository, and need to be brought to GitHub.
***
***
*** …
=> Update public documentation for C++ FCM SDK.

admob/integration_test/src/integration_test.cc, admob/src/android/ad_request_converter.cc, admob/src/android/ad_request_converter.h, admob/src/android/ad_result_android.cc, admob/src/android/ad_result_android.h, admob/src/android/adapter_response_info_android.cc, admob/src/android/admob_android.cc, admob/src/common/ad_result_internal.h, admob/src/include/firebase/admob/types.h, admob/src/ios/FADInterstitialDelegate.mm, admob/src/ios/FADRequest.h, admob/src/ios/FADRequest.mm, admob/src/ios/FADRewardedAdDelegate.mm, admob/src/ios/ad_result_ios.h, admob/src/ios/ad_result_ios.mm, admob/src/ios/adapter_response_info_ios.mm, admob/src/ios/admob_ios.h, admob/src/ios/admob_ios.mm, admob/src/ios/banner_view_internal_ios.mm, admob/src/ios/interstitial_ad_internal_ios.mm, admob/src/ios/rewarded_ad_internal_ios.mm, admob/src/stub/ad_result_stub.cc, app/src/util_android.h, app/src/util_ios.h, app/src/util_ios.mm
Android and iOS GMA SDK implementations provide error codes which return only on FullScreen operation failures.  Android's code values overlap with those of the normal AdError space.
This change treats the FullScreenContent errors separately from AdResult operations, and maps them to the standard AdError enumerated codes.
Other notes:
- Coalesced platform-specific AdResultInternal structure definitions into a common implementation.
- Added enum to denote origin of AdResultInternal errors (AdErrors, LoadAds, SDK Wrapper & FullScreenContent errors). This replaced boolean flag identifiers.
- Updated Intergration Test:
- new tests for attempting to show an ad twice for Insterstitial and Rewarded ads.
- added …
=> AdMob 2021 return FullScreenContent errors

app/src/include/firebase/future.h, app/src/include/firebase/internal/future_impl.h
Replace `std::mutex` with `firebase::Mutex` in `future.h`.
This is the fourth, and last, PR (the previous ones being #751, #792, and #795) towards moving `firebase::Mutex` into the public-internal includes directory, so that it can be used by `future.h`. See #747 for the rationale.
Googlers can see b/206520921 for more details.
=> future.h: replace std::mutex with firebase::Mutex

.github/workflows/integration_tests.yml
Fixes integration test run issue.
***
Ran integration tests with a similar change in #800.
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can …
=> Change setup-gcloud to use @v0 instead of @master as per their readme.

scripts/gha/integration_testing/test_validation.py
NoneType Error when failed to find the test failure logs:
https://github.com/firebase/firebase-cpp-sdk/runs/4713493652?check_suite_focus=true#step:10:6797
See test below
***
=> Fix Log NoneType Error

gma/integration_test/src/integration_test.cc, gma/src/android/banner_view_internal_android.cc, gma/src/android/banner_view_internal_android.h, gma/src/android/gma_android.cc, gma/src/include/firebase/gma/banner_view.h, gma/src_java/com/google/firebase/gma/internal/cpp/BannerViewHelper.java
There were stability issues when calling a JNI method and then immediately removing the global reference.  This manifested in JNI corruption errors on simulators.  
The previous BannerView destructor attempted to protect developers from accidentally leaking resources if the BannerView's destructor was called before the Destroy() method was invoked.  Our protected caused JNI assertions in simulators where the JNI parameters were corrupted.  I assume this was due to the  JNI object reference being deleted admist an asynchronous operation.
Therefore this change removes the attempt o invoke the JNI Destroy() method in the destructor on Android.  BannerView's header comments are updated to explicitly state that …
=> GMA - Fix Error in JNI method invocation on BannerView destruction

.github/workflows/integration_tests.yml, scripts/gha/summarize_test_results.py
In the Test Summary Report, add "x/y" which means "x" out of "y" configs has errors.
See comment below
=> In the Test Summary Report, add "x/y" which means "x" out of "y" configs has errors.

build_scripts/android/build.sh, scripts/gha/build_testapps.py
Attempt to reduce Android CI build flake caused by network connection timeouts to the Maven repo.
Following instructions from the [GHA Github Repo Issues forum](https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080). The fix seems to be very popular with 34 other closed issues referencing it.
***
[Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1725527077)
[Packaging CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1725702547) -> [Integration Test …
=> Increase Maven Connection Stability in GHA Android Builds

app/src/util_ios.mm
Unsure if this will help, but it certainly won't hurt.
***
***
*** …
=> Get rid of more firebase::Log* calls, to help with objc initialization.

app/src/util.cc
This causes logging to initialize when static constructors are running.
On Xcode 13, this causes a crash when Firebase App is initialized in
the wrong order.
***
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING …
=> Disable logging during AddCallback, which initializes too early.

gma/integration_test/src/integration_test.cc, gma/src/android/gma_android.cc, gma/src/include/firebase/gma.h, gma/src/ios/gma_ios.mm, gma/src/stub/gma_stub.cc
Add a method for iOS Apps to toggle IsSameAppKeyEnabled.
***
[Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1746988331)
[Packaging CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1746989289) -> [Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1747429283)
***
***
=> firebase::gma::SetIsSameAppKeyEnabled

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml, scripts/gha/it_workflow.py
Separate **nightly** workflow run & report for firestore.
***
Nightly Report for firestore: https://github.com/firebase/firebase-cpp-sdk/issues/832
Nightly Report for the rest: https://github.com/firebase/firebase-cpp-sdk/issues/833
***
***
=> Create Integration Test Nightly Report for firestore

Android/firebase_dependencies.gradle
For some reason, having :gma:gma_resources missing from firebaseResourceDependenciesMap causes the Android build to hang on Windows, on the final linker step. Most likely, the error that this missing dependency causes is being lost due to a race condition, resulting in Gradle hanging. This step happens right before proguarding, so it's also possible that this race condition is causing Windows to wait indefinitely before starting proguarding.
Whatever the causes, fixing this issue fixes the Android build hang on Windows.
***
Ran Android integration …
=> Add missing :gma:gma_resources to firebaseResourceDependenciesMap

gma/integration_test/src/integration_test.cc, gma/src/android/ad_view_internal_android.cc, gma/src/android/ad_view_internal_android.h, gma/src/common/ad_view.cc, gma/src/common/ad_view_internal.h, gma/src/include/firebase/gma/ad_view.h, gma/src/ios/ad_view_internal_ios.h, gma/src/ios/ad_view_internal_ios.mm, gma/src/stub/ad_view_internal_stub.h
Add a method to retrieve the AdSize that was used to initialize the AdView.
***
[Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1786111124)
[Packaging CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1786111919) -> [Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1786633499)
***
***
=> GMA  AdView::ad_size()

.github/workflows/reviewer-roulette.yml
Add a label '**reviewer-roulette**', which randomly assigns a new Firebase C++ SDK code reviewer.
It won't assign the author of the PR as a reviewer, nor anyone already set as a reviewer, nor anyone who has previously reviewed the PR.
=> Add "reviewer roulette" workflow.

app/src/app_ios.h, app/src/app_ios.mm, app/src/log_ios.mm, app/src/util.cc, release_build_files/readme.md
Don't call FIRConfiguration setLoggerLevel: before FIRApp exists. 
Instead, cache the value, and call setLoggerLevel later, after the iOS FIRApp instance is created.
This should be a safer fix to prevent FIRApp from being automatically initialized when logging occurs too early in the Unity SDK, which is causing a crash on iOS 15 devices in certain cases (in particular in the Firebase Unity SDK).
***
@a-maurice to manually test in Firebase Unity SDK.
***
*** …
=> Don't call FIRConfiguration setLoggerLevel: before FIRApp exists.

scripts/gha/lint_commenter.py
Remove the "unapproved C++ header" lint warning.
(Also add a note explaining each lint warning we ignore.)
***
Ran lint_commenter.py script to ensure it doesn't fail.
***
***
=> Remove the "unapproved C++ header" lint warning.

.github/workflows/integration_tests.yml
[Yesterday's fix](https://github.com/firebase/firebase-unity-sdk/pull/183) causes an error, because certain GitHub variable doesn't exist with non-PR trigger:
https://github.com/firebase/firebase-unity-sdk/runs/5252098713?check_suite_focus=true
Now using this statement to ensure it works: `"${{ github.event.pull_request.merged == true}}" == "true"`
***
PR closed but not merged - workflow canceled: https://github.com/firebase/firebase-unity-sdk/actions/runs/1866039558
Manual  trigger - workflow running: https://github.com/firebase/firebase-unity-sdk/actions/runs/1866043270
Label trigger - workflow running: https://github.com/firebase/firebase-unity-sdk/actions/runs/1866063380
***
***
=> Fix cancel workflow run

auth/src/android/auth_android.cc, auth/src/auth.cc, auth/src/common.h, auth/src/desktop/auth_desktop.cc, auth/src/include/firebase/auth.h, auth/src/ios/auth_ios.mm
Update c++ GetAuth to always call native auth getters so that any logging internal to the native auth implementations will be triggered.
This is as described in the "How data is collected" section of
https://docs.google.com/document/d/1eVlEmjdxSsXsvnzGiRYYfb0RtfWRLi3yo9vHj0NhqE4/edit#heading=h.ohspo4gdlkj0 
This change is currently only for Auth, but similar changes will be done separately for Database, Firestore, Functions, Installation and Remote Config.
***
This is effectively no-op for now, since native SDKs do not yet log heartbeats.
Once …
=> Heartbeat logging passthrough for Auth on Mobile Platforms

.github/workflows/integration_tests.yml
1. Test timeout extend to 90 mins.
https://github.com/firebase/firebase-cpp-sdk/runs/5091186528?check_suite_focus=true
^ process timed out
2. Enable Firestore Emulator only when needed. 
https://github.com/firebase/firebase-cpp-sdk/runs/5092455184?check_suite_focus=true
^ SIGINT and seems like no tests ran
See comments.
***
=> Enable Firestore Emulator only when needed

installations/src/android/installations_android.cc, installations/src/android/installations_android.h, installations/src/include/firebase/installations.h, installations/src/installations.cc, installations/src/ios/installations_ios.h, installations/src/ios/installations_ios.mm, installations/src/stub/installations_stub.cc, installations/src/stub/installations_stub.h
Update c++ FIS GetInstance to always call native FIS getters so that any logging internal to the native implementations will be triggered.
This is as described in the "How data is collected" section of
https://docs.google.com/document/d/1eVlEmjdxSsXsvnzGiRYYfb0RtfWRLi3yo9vHj0NhqE4/edit#heading=h.ohspo4gdlkj0 
This is effectively the same as https://github.com/firebase/firebase-cpp-sdk/pull/846, but for FIS
***
This is effectively no-op for now, since native SDKs do not yet log heartbeats.
Once heartbeat logging from getters is supported, manual …
=> Heartbeat logging passthrough for FIS for mobile platforms.

scripts/gha/build_desktop.py
Installation of libsecret failed in https://github.com/firebase/firebase-cpp-sdk/runs/5473061295 due to GitHub runner environment change. The workaround now needs to manually specify i386 architecture when installing libsecret.
***
Running Desktop PR checks should suffice.
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING.md) …
=> Fix Linux x86 package installation on GH runners

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml
0. updated artifact related action version
1. If packaging workflow failed, don't run integeration test workflow. [e.g.](https://github.com/firebase/firebase-cpp-sdk/runs/5446230846?check_suite_focus=true)
2. If build testapps job failed (no testapp artifacts), don't report "missing log" test error. [e.g.](https://github.com/firebase/firebase-cpp-sdk/runs/5420852601?check_suite_focus=true#step:4:13)
Will have followup design about passing failure jobs info to next jobs.
***
See the comment below
***
***
- Changes to …
=> Don't report test error if it's indeed build errors

.github/workflows/android.yml, .github/workflows/checks.yml, .github/workflows/checks_secure.yml, .github/workflows/desktop.yml, .github/workflows/integration_tests.yml, .github/workflows/ios.yml, .github/workflows/lint.yml
To save the runner resource, use [concurrency](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency) to prevent previous workflows from running. This can occur in PRs where the author raises multiple commits in quick succession.
***
Previous commits cancelled:
https://github.com/firebase/firebase-cpp-sdk/actions/runs/1994908024
https://github.com/firebase/firebase-cpp-sdk/actions/runs/1994908021
https://github.com/firebase/firebase-cpp-sdk/actions/runs/1994908019
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING.md) …
=> Cancel workflows for previous commits in a PR when new commits are pushed

app/CMakeLists.txt
Since latest Xcode (13.3) and clang++ (apple 13.1.6) iOS apps can no longer compile as the linker complains about undefined symbols:
```
Undefined symbols for architecture arm64:
"firebase::AppDataDir(char const*, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
firebase::(anonymous namespace)::GetFilename(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in firebase(heartbeat_date_storage_desktop.cc.o)
```
Taking a deeper look it seems like there is indeed an undefined symbol in firebase.xcframework:
```
U __ZN8firebase10AppDataDirEPKcbPNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
``` 
While searching for this symbol in the repo it seems to be defined in a file called …
=> iOS: remove desktop sources that were mistakenly merged into app/CMakeLists.txt

.github/workflows/integration_tests.yml, scripts/gha/integration_testing/gameloop_android/app/src/androidTest/java/com/google/firebase/gameloop/GameLoopUITest.kt, scripts/gha/integration_testing/gameloop_apple/gameloopUITests/gameloopUITests.swift
For firestore testapp, each individual test runs in less than 1 second locally.
However, in GHA, the run times of the individual tests and some are taking 5-10 seconds EACH.  This excessive runtime could easily add up to surpass the original 10 mins limit.
e.g. https://github.com/firebase/firebase-cpp-sdk/runs/5769606818?check_suite_focus=true
***
See comment below
***
*** …
=> [Experimental] Increase Android Emulator Test timeout from 10 mins to 20 mins

cmake/external/leveldb.cmake, release_build_files/readme.md
LevelDb version 1.23 is the first LevelDb release to include the pinned commit, https://github.com/google/leveldb/commit/e0d5f83a4f80060fe5b5d80025f0ad049bca430e.
=> Upgrade LevelDb dependency from a pinned commit to 1.23

cmake/external/firestore_snappy.patch.txt
This is a follow-up to #885 and fixes the Snappy build on some older compilers (e.g. gcc-9.4.0 on linux).
This PR is based on this patch: https://github.com/google/snappy/pull/128
The build error looks like this:
```
snappy.cc:1017:8: warning: always_inline function might not be inlinable [-Wattributes]
1017 | size_t AdvanceToNextTag(const uint8_t** ip_p, size_t* tag) {
|        ^~~~~~~~~~~~~~~~
snappy.cc: In function ‘std::pair<const unsigned char*, long int> snappy::DecompressBranchless(const uint8_t*, const uint8_t*, ptrdiff_t, T, ptrdiff_t) [with T = char*]’:
snappy.cc:1017:8: error: inlining failed in call to always_inline ‘size_t snappy::AdvanceToNextTag(const uint8_t**, size_t*)’: function body can be overwritten at link time
snappy.cc:1097:43: note: called from here
1097 | …
```
=> firestore_snappy.patch.txt: fix linux gcc inlining build error

app/CMakeLists.txt, app/src/heartbeat/schemas/logged_heartbeats.fbs
Defines a LoggedHeartbeats flatbuffer schema which contains a string representing the date that a heartbeat was last logged, and a list of entries where each entry contains a user agent string and a list of dates in which heartbeats were logged.
=> Define flatbuffers schema for logged heartbeats

CMakeLists.txt
This won't have any effects until the iOS dependencies are updated to a version that includes https://github.com/firebase/firebase-ios-sdk/pull/9658.
Setting the cmake cache variable `FIRESTORE_INCLUDE_OBJC` to `NO` will work around the `unknown attribute 'swift_async'` build error introduced by https://github.com/firebase/firebase-ios-sdk/pull/9502, and that will be picked up the next time that the iOS dependencies in this repository are upgraded. This fixes the build error because the file with the problematic code is no longer included in the build.
See https://github.com/firebase/firebase-ios-sdk/pull/9658 for more details.
=> Set the FIRESTORE_INCLUDE_OBJC cmake cache var to NO

cmake/external/firestore.cmake
There were some major changes to `firestore.cmake` in #855, including replacing the line
```
set(version CocoaPods-8.12.1)
```
with
```
GetReleasedDep("CocoaPods-8.12.1")
```
However, the `update-dependencies.yml` workflow had the old syntax hardcoded: https://github.com/firebase/firebase-cpp-sdk/blob/fd054fa0163ab304f3f32e967112f62aa5fc3f54/.github/workflows/update-dependencies.yml#L81
This discrepancy caused the update of the Firestore SDK to be missed in #893.
This PR changes `firestore.cmake` back to the old syntax, and adds a comment so that this will be more difficult to mess up in the future.
=> firestore.cmake: go back to the old set(version X.Y.Z) syntax

scripts/gha/build_desktop.py
Replicate the fix from build_testapps into build_desktop.
***
***
*** …
=> Fix path to python on windows desktop build.

gma/integration_test/AndroidManifest.xml, gma/integration_test/Info.plist, gma/integration_test/src/integration_test.cc, scripts/gha/ui_testing/uitest_android/app/src/androidTest/java/com/google/firebase/uitest/UITest.java, scripts/gha/ui_testing/uitest_android/app/src/main/AndroidManifest.xml, scripts/gha/ui_testing/uitest_android/app/src/main/res/xml/file_paths.xml, scripts/gha/ui_testing/uitest_apple/FirebaseCppUITestApp/ViewController.swift, scripts/gha/ui_testing/uitest_apple/FirebaseCppUITestAppUITests/FirebaseCppUITestAppUITests.swift, testing/sample_framework/src/android/android_app_framework.cc, testing/sample_framework/src/android/java/com/google/firebase/example/LoggingUtils.java, testing/sample_framework/src/app_framework.h, testing/sample_framework/src/desktop/desktop_app_framework.cc, testing/sample_framework/src/ios/ios_app_framework.mm, testing/test_framework/src/firebase_test_framework.cc, testing/test_framework/src/firebase_test_framework.h
To support UI Test Automation,
1. Modified `app_framework` and `firebase_test_framework`. Now, we could skip non UI tests with Marco `TEST_NO_USER_INTERACTION `
2. Modified GMA testapps. Skip Android non UI tests with Intent `com.google.intent.action.UI_TEST`; skip iOS non UI tests with URI `firebase-ui-test`.
3. Modified helper apps (in `scripts/gha/ui_testing`). Now, we could run testapps and skip non UI tests with the script.
Will have a followup PR that modify GMA Integration Tests, and enables GMA UI Tests in CI.
***
Currently CI passed: https://github.com/firebase/firebase-cpp-sdk/actions/runs/2235993495
UI Tests were tested locally and work as expected.
***
***
- Bug fixes and feature changes …
=> Modify Test Framework to make it able to trigger only UI tests in testapps (skip non UI tests)

.github/workflows/android.yml, .github/workflows/cpp-packaging.yml, .github/workflows/desktop.yml, .github/workflows/integration_tests.yml, .github/workflows/ios.yml, .github/workflows/update-dependencies.yml, scripts/gha/print_matrix_configuration.py
Update macos runners to use macos-12 (public beta) instead of macos-latest (equivalent to macos-11).
This change requires updating to Xcode 13.1 as a stopgap solution; we will update to Xcode 13.2.1 or Xcode 13.3.1 in a subsequently-merged PR. Updating to Xcode 13 necessitates updating iOS simulator versions as well.
Note: skipping release notes check, because the subsequent PR (#915) updates the release notes with the new Xcode version requirement.
***
Integration test run in the PR.
C++ packaging step here: …
=> Change macos runners to macos-12. (requires updating xcode to 13.1)

gma/integration_test/src/integration_test.cc, gma/src/android/adapter_response_info_android.cc, gma/src/android/gma_android.cc, gma/src/common/gma_common.cc, gma/src/common/gma_common.h, gma/src/include/firebase/gma/ad_view.h, gma/src/include/firebase/gma/types.h, gma/src/ios/FADAdView.mm, gma/src/ios/ad_view_internal_ios.h, gma/src/ios/ad_view_internal_ios.mm, gma/src/ios/adapter_response_info_ios.mm, gma/src/ios/gma_ios.h, gma/src/ios/gma_ios.mm, gma/src/ios/interstitial_ad_internal_ios.mm, gma/src/ios/rewarded_ad_internal_ios.mm, gma/src_java/com/google/firebase/gma/internal/cpp/AdViewHelper.java, gma/src_java/com/google/firebase/gma/internal/cpp/InterstitialAdHelper.java, gma/src_java/com/google/firebase/gma/internal/cpp/RewardedAdHelper.java
The GMA ResponseInfo object can be obtained on any and result, whether it's an AdError or a successful AdLoad.  However, currently the C++ API only makes this accessible on error objects.
This will allow our customers to query which mediation adapter loaded an ad.
Additional Changes:
- [iOS] fixed a problem on Load Ad operations for all ad types if the parameters passed into the method were destroyed before the ayschronous ad load operation is scheduled.
- [iOS] Renamed the methods which complete ad load futures to clarify code paths which handle errors and successes.
- A few doxygen changes based on feedback from DevRel.
***
> Describe how you've tested these changes. Link any manually triggered …
=> GMA - Add ResponseInfo to AdResult

admob/integration_test/gradle/wrapper/gradle-wrapper.properties, analytics/integration_test/gradle/wrapper/gradle-wrapper.properties, app/integration_test/gradle/wrapper/gradle-wrapper.properties, auth/integration_test/gradle/wrapper/gradle-wrapper.properties, database/integration_test/gradle/wrapper/gradle-wrapper.properties, dynamic_links/integration_test/gradle/wrapper/gradle-wrapper.properties, firestore/integration_test/gradle/wrapper/gradle-wrapper.properties, firestore/integration_test_internal/gradle/wrapper/gradle-wrapper.properties, functions/integration_test/gradle/wrapper/gradle-wrapper.properties, gradle/wrapper/gradle-wrapper.properties, installations/integration_test/gradle/wrapper/gradle-wrapper.properties, messaging/integration_test/gradle/wrapper/gradle-wrapper.properties, remote_config/integration_test/gradle/wrapper/gradle-wrapper.properties, scripts/gha/integration_testing/gameloop_android/gradle/wrapper/gradle-wrapper.properties, storage/integration_test/gradle/wrapper/gradle-wrapper.properties
Update from a very old Gradle version (4.10.1) to a slightly less old version (5.6.4) to fix some Android build errors, as new Firebase Android dependencies require a newer version.
Gradle 6.x and up cause a build error in our Proguard generator that will need to be addressed before updating further.
***
***
*** …
=> update gradle version

gma/src/android/gma_android.cc, gma/src/common/gma_common.cc, gma/src/common/gma_common.h, gma/src/ios/ad_view_internal_ios.mm, gma/src/ios/gma_ios.mm, gma/src/ios/interstitial_ad_internal_ios.mm, gma/src/ios/rewarded_ad_internal_ios.mm
- Renamed Internal methods to be more descriptive as to whether they complete the AdResult futures successfully or with an error. 
***
- Manually testing on iOS and Android
- [Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2276799851)
***
***
- …
=> GMA - rename AdResult error/success future-completion methods

scripts/gha/build_testapps.py
Pass in "-j <number_of_cpus>" to cmake --build when building desktop testapps.
This should speed up the desktop testapp build. Linux improves from ~50min to ~35min. MacOS improves from ~140min to ~90min. Windows does not change (probably ignores the -j parameter).
***
Run integration tests in this PR.
***
*** …
=> Pass in -j N to cmake  to speed up desktop testapp build.

release_build_files/CMakeLists.txt
Check whether -m32 was specified in the c++ flags, and if so, link against the i386 version of the Linux libraries.
***
Tested in #931 along with other cross-architecture changes.
***
*** …
=> Fix building integration tests against packaged SDK on Linux x86

scripts/gha/print_matrix_configuration.py
iOS 12.4 simulator is not playing nicely with Xcode 13.3.1. Update to use iOS 13.7 instead to unbreak the tests. We still test on iOS 12.x on FTL so this is low risk.
***
Can only be tested in the expanded matrix.
***
*** …
=> Update simulator min version

.github/workflows/cpp-packaging.yml, .github/workflows/desktop.yml, .github/workflows/integration_tests.yml, scripts/gha/build_desktop.py, scripts/gha/install_prereqs_desktop.py, scripts/gha/utils.py
Move x86 Linux setup to prereqs - this lets us add a retry to the Linux package installation, which can sometimes fail due to network connectivity.
(The setup is still present in the build script, but won't do anything if it determines that the required packages are installed.)
***
Desktop checks and integration tests in this PR.
***
*** …
=> Move x86 Linux setup to prereqs script

.github/ISSUE_TEMPLATE/feature-request.md
Hey wonderful Firebase folks,
I'd noticed that the Feature Request template added [FR] to the title but then asked that the title instead start with "FR:". So, I figured I'd toss up a quick PR as a concrete proposal of one way to fix the inconsistency.
Figured you all would at least want a friendly heads. [FR] and no further description seemed more consistent with the other templates, so that's what I did in the PR. But of course, it doesn't matter to me what you choose. 
Cheers!
Chris
(ex-Googler)
=> Fix inconsistent feature request issue prefix

cmake/external_rules.cmake
In CMake, if the caller has set CMAKE_POSITION_INDEPENDENT_CODE, that needs to be propagated to the special early build of the dependencies like boringssl, so that the libraries can link together properly.
***
Building the Unity SDK on Linux with boringssl enabled.
***
***
- …
=> Propagate the Position Independent Code flag

scripts/gha/build_testapps.py
Some of the build artifacts on Windows end up as read-only files, which shutil.rmtree doesn't handle by default. Pass in an onerror handler to make the files writable and try again.
This causes the disk space usage of build_testapps on Windows desktop to drop from 11GB+ to 2.5GB.
***
Tested in #959 and in this PR's integration tests.
***
*** …
=> Handle Access Denied error when cleaning up build directory on Windows

.github/workflows/desktop.yml, .github/workflows/integration_tests.yml
The Firebase CLI tools require a java version 11+.  The default GHA runner Java version did not meet this standard.
This change adds an extra workflow step to install a JRE of v17.
***
[Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2358886238)
[Desktop CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2358635902)
***
***
=> Update GHA CI Java Version

app/src/util_android.cc, app/src/util_android.h, functions/integration_test/src/integration_test.cc, functions/src/android/functions_android.cc, functions/src/android/functions_android.h, functions/src/common/functions.cc, functions/src/desktop/callable_reference_desktop.cc, functions/src/desktop/callable_reference_desktop.h, functions/src/desktop/functions_desktop.cc, functions/src/desktop/functions_desktop.h, functions/src/include/firebase/functions.h, functions/src/ios/functions_ios.h, functions/src/ios/functions_ios.mm, release_build_files/readme.md
Adds GetHttpsCallableFromURL to the Functions SDK. This was recently added to both the Android and iOS SDKs.
***
Running the testapps on mobile and desktop locally with the changes.
***
*** …
=> Add GetHttpsCallableFromURL to Functions

.github/workflows/integration_tests.yml
Fix a problem where the Firestore integration tests were flakily failing in GitHub Actions runners due to the Firestore emulator failing to start.
If the GitHub Actions runner selected for integration testing had JDK 8 installed then the Firestore emulator would fail to start because recent releases of the Firestore emulator require JDK 11 or newer. This would cause the tests that attempt to communicate with the Firestore emulator to understandably fail.
The fix is to explicitly install JDK 11 (or newer) on GitHub Actions runners using the `setup-java` action, instead of relying on the java version that happened to be installed on the runner.
Googlers can see b/233751585 for details.
=> Run setup-java for Firestore emulator in GitHub Actions

build_scripts/desktop/package.sh, firestore/integration_test/CMakeLists.txt, release_build_files/readme.md
The PR https://github.com/firebase/firebase-ios-sdk/pull/9488 in the firebase-ios-sdk added a dependency on a new third-party library, "re2". This was picked up by the firebase-cpp-sdk in https://github.com/firebase/firebase-cpp-sdk/pull/977.
All of the CI builds and tests worked fine; however, the "blastdoor" post-processing step renamed the `re2` namespace that caused linking error when linking against the packaged SDK (e.g. https://github.com/firebase/firebase-cpp-sdk/runs/6701070693).
This PR fixes the linking error by configuring blastdoor to properly handle re2. This was 100% based on the same thing for the snappy dependency in https://github.com/firebase/firebase-cpp-sdk/pull/885.
Also, in the same PR the versions of grpc and absl were updated, which on Windows requires linking …
=> Add RE2 library to desktop packaging & Update MSVC dependencies

.github/workflows/android.yml, .github/workflows/integration_tests.yml
=> Use NDK r21e (installed by prereqs script) for Android builds.

scripts/gha/restore_secrets.py
Whenever I do local development I run restore_secrets, which updates all of the Google Services data for all of the products. This pollutes my local branch since normally I'm only working on one product.
This change adds an optional `api` flag so that you can checkout the secrets for only one product at a time.
***
- Local testing.
- [Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2502019096)
***
***
=> Add an API flag to restore_secrets script

messaging/src/ios/messaging.mm
Remove unnecessary error for FCM
There is no need to log and error when the API returns the existing future.
***
Integration test workflow
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your …
=> Fix #994 Remove unnecessary error for FCM

messaging/src/android/java/com/google/firebase/messaging/cpp/RegistrationIntentService.java, release_build_files/readme.md
Make sure all FileStream and FileLock are closed using AutoClose pattern.
Make sure all the resource are closed RegistrationIntentService using AutoClose and try-with-resources statement.
***
Using integration test workflow (pending)
***
***
- Changes to the public API require …
=> Fix #973 Make sure all resources are closed in RegistrationIntentService

app/src/filesystem_desktop_linux.cc, database/src/desktop/core/repo.cc, release_build_files/readme.md
On Linux, if the XDG_DATA_HOME directory doesn't exist, RTDB disk persistence will fail to initialize. This fixes ensures that if the directory doesn't exist, the app will create it. (Fix for #913.)
Previously, only the last part of the path would be created; but if the user did not have a `.local/share` directory this would still silently fail. This change modifies the behavior to create any missing components from the full app data path.
***
Manually run integration test on Linux with $XDG_DATA_HOME set to an arbitrary directory. Confirmed that …
=> In RTDB, create app data directory if it doesn't exist. Modify AppDataDir to create the whole path if needed.

cmake/external/firestore.cmake
In the Firestore iOS SDK, the usage of patch.exe crashes on Windows due to CRLF issues. This is fixed in that repo by https://github.com/firebase/firebase-ios-sdk/pull/9941; use that commit in the C++ SDK, since it was not included in the 9.2.0 release. (The commit was branched off of the CocoaPods-9.2.0 tag.)
***
[Running C++ Packaging workflow.](https://github.com/firebase/firebase-cpp-sdk/actions/workflows/cpp-packaging.yml?query=branch%3Abugfix%2Fwindows-patch-exe)
***
***
- Bug fixes and feature changes require …
=> Change Firestore external ref to one with patch.exe bugfix

.github/workflows/integration_tests.yml
The nightly SDK builds are hardcoded into the workflow. This change updates the list of the nightly builds to include the new GMA SDK.
***
Ran the[ Integration Test Workflow](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2612125641) to ensure that the syntax of the workflow file is correct.  Firestore failed on tvOS but everything else worked correctly.
***
***
=> Add GMA to the list of cron SDKs to build nightly

firestore/integration_test_internal/CMakeLists.txt
The removed logic is completely broken. It calls `set(${ADDITIONAL_LIBS}` but should be `set(ADDITIONAL_LIBS`. It's effectively setting some variable that's never used. Therefore, just remove the code since its presence is confusing.
=> Firestore: Remove broken absl flags logic from CMakeLists.txt

app/src/semaphore.h, release_build_files/readme.md
This fixes a latent bug where [`Future::Wait(int timeout_milliseconds)`](https://github.com/firebase/firebase-cpp-sdk/blob/c722ca77e4cbfd38f530f51c205a55d1c76bb212/app/src/include/firebase/future.h#L213) would occasionally return prematurely, when neither the timeout had expired nor the Future been completed. This was due to the implementation of [`Semaphore::TimedWait(int milliseconds)`](https://github.com/firebase/firebase-cpp-sdk/blob/c722ca77e4cbfd38f530f51c205a55d1c76bb212/app/src/semaphore.h#L165-L177) which calls [`sem_timedwait()`](https://linux.die.net/man/3/sem_timedwait) on Linux and Android and neglected to check if the `errno` was `EINTR`, in which case the wait should be restarted. 
This bug surfaced as the integration tests for Firestore's `TransactionTest.TestMaxAttempts` …
=> semaphore.h: handle spurious wakeups in TimedWait() on Linux

.github/workflows/integration_tests.yml
Fix fixes the following error:
```
D:\a\_temp\06929eb0-6b9b-4afe-ae47-9ae8117d8f0e.sh: line 2: [: missing `]'
```
e.g. https://github.com/firebase/firebase-cpp-sdk/runs/7301198906
=> Fix bash typo in integration_tests.yml

app/tests/semaphore_test.cc
With the fix to Semaphore::TimedWait() in https://github.com/firebase/firebase-cpp-sdk/pull/1021, the MultithreadedStressTest can now be re-enabled.
=> semaphore_test.cc: re-enable MultithreadedStressTest

app/tests/semaphore_test.cc
Add a unit test for the Semaphore::TimedWait() spurious wakeup fix in https://github.com/firebase/firebase-cpp-sdk/pull/1021.
=> semaphore_test.cc: add TimedWaitSpuriousWakeupLinux

gma/integration_test/Podfile, gma/src/ios/ad_view_internal_ios.mm, ios_pod/Podfile, release_build_files/readme.md
Update the Google Mobile Ads dependency to `9.7.0`.
Fixed an ambiguous selector to in the AdView implementation on iOS.
***
Tested manually on simulator and iOS device.
[Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2782925220)
[Packaged CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2782978740) -> [Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2783951512)
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING …
=> Update GMA iOS Dependency to 9.7.0

app/src/time.h, app/tests/time_test.cc, release_build_files/readme.md
This PR fixes a long-standing bug in `MsToAbsoluteTimespec(int milliseconds)` which would result in an integer overflow if invoked with a sufficiently-large "milliseconds". The bug manifested on 32-bit architectures because the `tv_sec` and `tv_nsec` members of `timespec` are 4 bytes each (32 bits), where on 64-bit architectures they are 8 bytes each (64 bits), and did not suffer from the overflow.
The problem was that in `MsToAbsoluteTimespec(int milliseconds)` it would add the given milliseconds, after converting to nanoseconds, to the `tv_nsec` member, and then call a helper function to normalize the values; however, when being invoked with a `milliseconds` value of `10000` (10 seconds) this would cause `tv_nsec` to overflow and wrap around to a negative value. When this malformed …
=> time.h: fix integer overflow in MsToAbsoluteTimespec() on 32-bit architectures

app/src/pthread_condvar.h, app/src/time.h, app/tests/time_test.cc
Fix the templated overload of `ConditionVariable::TimedWait()`, which suffers from the same integer overflow bug on 32-bit architectures as `Semaphore::TimedWait(int)` did (which was fixed by https://github.com/firebase/firebase-cpp-sdk/pull/1042). Also, delete `NormalizeTimespec()` since it is no longer used anywhere.
=> pthread_condvar.h: Fix ConditionVariable::TimedWait() on 32-bit platforms

firestore/integration_test_internal/src/write_batch_test.cc
The assertion checks in `write_batch_test.cc` have been improved in this PR to provide better information upon test failure. 
For example,
```
EXPECT_TRUE(0 == initial_snapshot.size());
```
was changed to
```
EXPECT_EQ(initial_snapshot.size(), 0);
```
so that the _actual_ size would be included in the failure message.
This will help debug test failures in the future.
=> Firestore: write_batch_test.cc: clean up assertion checks

firestore/integration_test_internal/src/firestore_test.cc
This additional assertions will help debug future test failures. Also, some EXPECT_EQ were changed to ASSERT_EQ if they were checking the length of a result size, so that if the size is too small then it will avoid dereferencing non-existing elements from the result set.
=> firestore_test.cc: add assertions for snapshots existing

firestore/src/main/create_firebase_metadata_provider_desktop.cc, firestore/src/main/firebase_metadata_provider_desktop.cc, firestore/src/main/firebase_metadata_provider_desktop.h
Send GMP App Id along with Firestore requests for desktop platform similar to for Apple platform.
https://github.com/firebase/firebase-ios-sdk/blob/eb30b6fdd809cbfe3a9eb7f3ccf1dd46326bef2d/Firestore/core/src/remote/firebase_metadata_provider_apple.mm#L66.
This is required for the backend to process heartbeat properly for desktop usage.
**
The test was done manually by checking backend log and verified that app id was received properly after this patch.
***
***
- Bug fixes and feature changes require an update to the …
=> Send App Id when Firestore SDK delivers heartbeat

firestore/integration_test_internal/src/firestore_integration_test.cc, firestore/integration_test_internal/src/firestore_integration_test.h
This will help debug test failures to point more closely to the line of code on which a timeout occurred.
=> Firestore: Add SCOPED_TRACE to Await() calls in firestore_integration_test.h/cc

.github/workflows/desktop.yml, .github/workflows/integration_tests.yml
Installing firebase-tools requires network connectivity - thus we should retry if it fails.
***
Run integration tests, ensure no issues installing firebase-tools
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs …
=> Add retry to npm installation of firebase-tools

.github/workflows/desktop.yml, .github/workflows/integration_tests.yml
Upgrade `node-version` to 16 (was 14) in GitHub Actions workflows (`desktop.yml` and `integration_tests.yml`).
Node version 16 is the "long term support" version.
This may also fix intermittent failures of `npm install -g firebase-tools` with the error "npm ERR! cb() never called!"
=> Upgrade node-version to 16 (was 14) in GitHub Actions workflows

.github/workflows/android.yml, .github/workflows/cpp-packaging.yml, .github/workflows/desktop.yml, scripts/gha/build_desktop.py
vcpkg keeps giving errors when trying to update, so disabling it for now.  Likewise homebrew is repeatedly failing to update, and based on the comments about it, it should no longer be needed, as it was working around an issue that was fixed a year ago.
***
Tests via workflows
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING …
=> Disable vcpkg and remove homebrew update

scripts/gha/build_testapps.py
vcpkg has been having errors finding the toolchain files, and should not be necessary for the build, so remove it from the testapp builder logic.
***
https://github.com/firebase/firebase-cpp-sdk/actions/runs/3099919285
***
*** …
=> Remove vcpkg from testapp builder

.gitignore
When doing the Android build, native builds end up in .externalNativeBuild, so we should ignore that in the gitignore.
***
***
*** …
=> Ignore Android native build folder

app/src/app_desktop.cc, app/src/heartbeat/heartbeat_controller_desktop.h, app/src/include/firebase/app.h, app/tests/heartbeat_controller_desktop_test.cc, auth/src/desktop/auth_desktop.cc, auth/tests/desktop/rpcs/auth_request_heartbeat_test.cc
On desktop, call LogHeartbeat after App is created. This should mean that heartbeats are consistently logged regardless of whether or not auth or firestore is included.
Also define a method called LogHeartbeat in App so that Unity SDK can call that to trigger heartbeat logging without having to interact with the HeartbeatController.
***
Updated heartbeat controller and auth request unit tests to rely on this automatic call to LogHeartbeat instead of explicitly calling LogHeartbeat in those test cases.
***
- [x ] New …
=> Desktop Heartbeat - Log a heartbeat after app is created, and add LogHeartbeat method

auth/src/desktop/auth_providers/google_auth_provider.cc, auth/src/desktop/rpcs/verify_assertion_request.cc, auth/tests/desktop/fakes.cc, firestore/integration_test_internal/src/util/integration_test_util.cc
The linter does not like the std::string{} brace initialization syntax and spits out errors. This fixes those errors.
***
PR checks run to ensure the build has not broken.
***
***
=> Fix lint error by removing brace initialization syntax from strings.

firestore/src/android/field_value_android.cc, firestore/src/android/field_value_android.h, release_build_files/readme.md
In `field_value_android.h`, change the `std::vector<FieldValue>` and `MapFieldValue` constructors to take const references, instead of values. This reduces by half the number of global references needed when `DocumentReference::Set()`, `DocumentReference::Update()`, and `CollectionReference::Add()` are called on Android.
Since these 3 methods are part of the public interface and take const references as their arguments, they are not able to `std::move` these values into the `FieldValueInternal` constructor, thus requiring copies. On Android, these copies necessitate doubling the number of JNI global references in use, making it much easier to hit the 51,200 hard limit.
This is the first part of a proper fix for the global refs exhaustion issue reported in …
=> Firestore: Remove copies in FieldValueInternal to reduce global refs consumption.

app_check/CMakeLists.txt, app_check/src/android/debug_provider_android.cc, app_check/src/android/debug_provider_android.h, app_check/src/common/debug_provider_common.cc, app_check/src/desktop/debug_provider_desktop.cc, app_check/src/desktop/debug_provider_desktop.h, app_check/src/include/firebase/app_check/debug_provider.h, app_check/src/ios/debug_provider_ios.h
Make the App Check debug provider use an internal class, so that each platform can add privates without affecting the others.
***
Locally building and
https://github.com/firebase/firebase-cpp-sdk/actions/runs/3317166856/jobs/5479887578
***
***
- Changes to the public API require …
=> Make the app check debug provider use an internal class

storage/integration_test/src/integration_test.cc
Disables FirebaseStorageTest.TestPutFileAndGetFile on iOS
Changes FirebaseStorageTest.TestLargeFileCancelUpload on iOS to expect error code unknown instead of cancelled
These are temporary changes since the underlying cause of failures are unintended changes in iOS SDK 10.0.0
These will be reverted once iOS SDK functionality is restored to normal.
The cause of the TestPutFileAndGetFile error is here: [https://github.com/firebase/firebase-ios-sdk/issues/10353](https://www.google.com/url?q=https://github.com/firebase/firebase-ios-sdk/issues/10353&sa=D&source=buganizer&usg=AOvVaw26Q1fQKcmRdHVgGwF1gRCB), which is set to be fixed by the iOS 10.1.0 release.
The cause of TestLargeFileCancelUpload is less clear, but iOS SDK appears to be returning error code unknown.
***
Built and ran storage …
=> Disable failing iOS storage integration test cases 

storage/integration_test/src/integration_test.cc
Temporarily disable a couple tests that are broken due for tvos as a side effect of the ios 10.0 sdk
This is the same as #1123 but for tvos as well, since tvos is failing in the same way due to using the same iOS SDK.
***
Not manually tested on tvos, but this fix worked for iOS and the cause of the issue is the same
Example failure: FirebaseStorageTest.TestPutFileAndGetFile
https://github.com/firebase/firebase-cpp-sdk/actions/runs/3340116284/jobs/5530848566
***
*** …
=> Temporarily disable broken ios tests on tvos as well

app/rest/request.cc
The desktop rest request has a ToString method used for debugging, but it reads to the end of the body, causing the request to fail when trying to send it.  Fix by resetting the buffer offset afterwards.
***
***
***
- Changes to the public API require an internal API review. If …
=> Fix error with request ToString

release_build_files/readme.md
Adding a line to v 10.1.0 release notes to mention the known issue of linux x86 builds being broken
***
N/A
***
***
=> Update release notes to mention x86 linux issue

gma/build.gradle, gma/gma_resources/build.gradle, gma/integration_test/build.gradle, scripts/gha/ui_testing/uitest_android/build.gradle
jcenter has been deprecated, and mavenCentral should be used instead. The other products were already updated, but gma missed the update, which might be causing some of the flakes on building the Android testapp.  Also remove the unnecessary android stl flag.
***
***
***
- …
=> Update gma to use mavenCentral

scripts/gha/build_testapps.py
Building the testapps from source also needs to use the new toolchain logic to correctly specify 32 bit linux.
***
***
*** …
=> Use the new linux32 logic when building the testapps from source

messaging/integration_test/src/integration_test.cc
This tests have been failing for a while now. We have an internal ticket to track down the issue but it hasn't been prioritized. I'm disabling the test for now so that we can get to CI green.
***
[Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/3440535812/jobs/5739380663)
***
*** …
=> Disable failing Messaging tests in our Android CI

.github/workflows/integration_tests.yml
Removes the installation and initialization of the Firestone Emulator CI step which interfered with the testing. The test had assumed it was talking to production and would timeout when it was actually pointing at the emulator.
***
[Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/3431579830) - failures are due to messaging only, which will be fixed in a different PR.
[Updated Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/3439596673) - after removing Java 17 installation and Firebase …
=> Remove Firestore Emulator initilaization in CI

.github/workflows/integration_tests.yml
Remove the steps to install node.js from `test_android`. Its only purpose was to enable installation of the Firestore emulator, whose usage was removed in https://github.com/firebase/firebase-cpp-sdk/pull/1143. This _should_ have been part of that PR, but was overlooked.
=> integration_tests.yml: remove unnecessary node setup

scripts/gha/install_prereqs_desktop.py
=> On Linux, install and use GCC 10 if currently not using 9 or 10.

firestore/integration_test_internal/src/query_test.cc, firestore/src/main/query_main.cc
> Replace OrderByList by std::vector<OrderBy>
***
***
=> Replace OrderByList by std::vector<OrderBy> and Skip nested structure inside IN filter test case

scripts/gha/install_prereqs_desktop.py
Strawberry Perl can cause conflicts when searching for and resolving libraries, specifically zlib. By removing the directory, this will also prevent other possible libraries from having the same issue, which is a common Strawberry problem.
***
***
*** …
=> Remove Strawberry Perl as part of GHA setup

scripts/git/patches/boringssl/0001-disable-warnings.patch
Due to some Windows compiler setting changing, the warning C5264 is coming up in boringssl builds on some Windows runners, which breaks due to the treat-warnings-as-errors flag. This PR adds that warning to the "ignore warnings" list.
***
C++ Packaging run: https://github.com/firebase/firebase-cpp-sdk/actions/runs/3586408287
***
*** …
=> Ignore C5264 ('const' variable is not used) warning in boringssl.

gma/integration_test/CMakeLists.txt
This should resolve the following failure when building testapps on windows:
unresolved external symbol .. IsRunningOnEmulator ... referenced in function FirebaseGmaTest_TestAdViewLoadAd
Example: https://github.com/firebase/firebase-cpp-sdk/actions/runs/3628003197/jobs/6118528835
IsRunningOnEmulator is implemented in desktop_firebase_test_framework, so this adds that as a source file for the gma integration test (which is how the same source file is used in messaging and dynamic links integration tests)
Triggered integration test workflow to build gma integration test on windows
https://github.com/firebase/firebase-cpp-sdk/actions/runs/3651337419/jobs/6168441033
***
*** …
=> Fix for unresolved symbol IsRunningOnEmulator 

cmake/external/uWebSockets.cmake, scripts/git/patches/uWebSockets/0001-fix-want-write-and-sprintf-deprecation.patch
The latest Xcode tools have deprecated the use of `sprintf`. Use of that functions now produces warnings, and our builds treat such warnings as errors.
uWebSockets uses `sprintf` in one location.
This change updates the git patch that we already apply to uWebSockets sources to also update its use of `sprintf` to use `snprintf` instead. Thankfully, the size of the buffer that sprintf was writing into was readily available.
Note: we can't push this change back to uWebSockets as they've since rewritten the library.
***
[Integration …
=> Patch sprintf in uWebsockets to use snprintf

gma/integration_test/src/integration_test.cc
The GMA backend doesn't whitelist iOS devices running in CI which means number of ads that can be served to iOS in CI is restricted. This is true even when using the prescribed [Demo Ad Unit Id](https://developers.google.com/admob/ios/test-ads). 
This PR reduces the number of ads we load on iOS in an attempt to minimize the chance of encountering NoFillErrors and push our CI to green.
Notes:
- Test a subset of RewardedAds behavior on iOS in GHA CI.
- We no longer test successful RewardedAd loads.
- Rewarded Ads stress tests are disabled on iOS.
- Added a NoFill error as an acceptable result on stress tests for other platforms. The tests were meant to stress the SDK though ad object creation and destruction. …
=> Reduce number of RewardedAd loads on iOS in CI

scripts/update_android_ios_dependencies.py
Requires some custom code to handle the old 'admob' iOS SDK.
***
Ran manually, it updated everything correctly and skipped the old admob SDK.
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose …
=> Auto update GMA deps on iOS.

analytics/integration_test/src/integration_test.cc
=> Disable getSessionId test on emulators.

storage/integration_test/src/integration_test.cc
Occasionally, an Android FTL device will run the Storage tests really slowly. See if reducing the size down to 25% on Android fixes this.
***
Running integration tests.
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase …
=> Change storage download size on Android, to prevent FTL flake.

dynamic_links/integration_test/src/integration_test.cc
Sometimes the various GetShortLink* functions can fail with a network error, SSL error, etc. Add a retry to these operations in case they fail.
***
Run integration tests in this PR.
***
*** …
=> Add flaky retry to all network requests in Dynamic Links.

analytics/src/include/firebase/analytics.h, auth/src/include/firebase/auth.h, auth/src/include/firebase/auth/credential.h, auth/src/include/firebase/auth/types.h, auth/src/include/firebase/auth/user.h, database/src/include/firebase/database/query.h, firestore/src/include/firebase/firestore/settings.h, functions/src/include/firebase/functions/common.h, messaging/src/include/firebase/messaging.h, performance/src/include/firebase/performance.h
Update the reference docs to refer to tvOS when discussing particular methods and classes.
***
[Packaging Build for docs push](https://github.com/firebase/firebase-cpp-sdk/actions/runs/3750654704)
***
***
=> tvOS Reference Docs Changes

build_scripts/android/build.sh
When `NDK_ROOT` is set, this script would still set it to `/tmp/android-ndk-r21e`, which does not normally contains NDK unless `NDK_ROOT` is NOT set and `install_prereqs.sh` is called before.
Fix that line so that the if statement would properly exit when `NDK_ROOT` is set.
***
Ran locally. 
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/ma …
=> Fix build script when `NDK_ROOT` is set

firestore/integration_test_internal/src/validation_test.cc
Firestore implementation has been updated such that the validation no longer rejects use of multiple array-contains filters.
https://github.com/firebase/firebase-ios-sdk/pull/10449/files#diff-e11c1c8fc02726cb87283757008e935497911ea74a41f0efa93c4d2d6517d050
So this PR removes a test that expected this to throw an exception.
Example of a failure of the test before this change:
https://github.com/firebase/firebase-cpp-sdk/actions/runs/4242014548/jobs/7373657438
***
***
***
- Read the …
=> Remove obsolete Firestore validation tests

app_check/src/common/app_check.cc, app_check/src/common/common.h, app_check/src/desktop/app_check_desktop.cc, app_check/src/desktop/app_check_desktop.h, app_check/src/include/firebase/app_check.h, storage/src/desktop/storage_reference_desktop.cc
Change the internal call logic to return the token as just a string, instead of the struct. This prevents the need for the products using the function registry to include the App Check header for the struct definition. Also, use a new future, instead of reusing the public one, which might have lead to confusion with the LastResult functionality. 
***
Local testing of the desktop implementation.
***
*** …
=> Refactor the App Check internal call logic used by other products

app_check/integration_test/src/integration_test.cc, app_check/src/android/app_check_android.cc, app_check/src/android/app_check_android.h, app_check/src_java/com/google/firebase/appcheck/internal/cpp/JniAppCheckListener.java
Defines a Java AppCheckListener to pass to the Android SDK.
Maintains a vector of C++ AppCheckListeners that are called when android reports a token change.
Enabled token-change listener integration test cases on Android. Ran integration tests locally.
***
***
=> Implement AppCheck Android token-changed listeners

analytics/integration_test/src/integration_test.cc
The SessionID test is failing on Android due to problems with the test runner, not the product itself. Disable the tests for now, until we can fix the problem.
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs …
=> Disable SessionID test on Android

analytics/integration_test/src/integration_test.cc, testing/test_framework/src/android/android_firebase_test_framework.cc, testing/test_framework/src/android/java/com/google/firebase/example/TestHelper.java, testing/test_framework/src/desktop/desktop_firebase_test_framework.cc, testing/test_framework/src/firebase_test_framework.h, testing/test_framework/src/ios/ios_firebase_test_framework.mm
Check the GMSCore version in the Analytics test - this allows us to simply skip the GetSessionId test on devices that don't support it.
Also force an event to be logged before getting the session ID, so we are sure to have an Analytics session.
***
***
*** …
=> Check Google Play services version in Analytics test

analytics/integration_test/src/integration_test.cc, testing/test_framework/src/android/java/com/google/firebase/example/TestHelper.java, testing/test_framework/src/firebase_test_framework.h
Some tests don't have play services enabled, which makes GoogleApiAvailbility not available. Use reflection to handle this case.
The previous change #1235 broke a few tests, because they added a dependency to GoogleApiAvailability that some integration tests (e.g. admob) don't have.
This modifies the previous change so that it uses reflection to access GoogleApiAvailability, so it can handle the case where the play-services-base dependency is not included.
***
***
***
- Bug fixes and …
=> Change GetGooglePlayServices to use reflection to avoid build errors

admob/src/include/firebase/admob.h, analytics/src/include/firebase/analytics.h, app/CMakeLists.txt, app/src/include/firebase/app.h, app/src/include/firebase/cpp_version_warning.h, app/src/include/firebase/cpp_warning.h, app_check/src/include/firebase/app_check.h, auth/src/include/firebase/auth.h, database/src/include/firebase/database.h, dynamic_links/src/include/firebase/dynamic_links.h, firestore/src/include/firebase/firestore.h, functions/src/include/firebase/functions.h, gma/src/include/firebase/gma.h, installations/src/include/firebase/installations.h, messaging/src/include/firebase/messaging.h, performance/src/include/firebase/performance.h, release_build_files/readme.md, remote_config/src/include/firebase/remote_config.h, storage/src/include/firebase/storage.h, testlab/src/include/firebase/testlab.h
> Add compile time warning for C++14 upgrade.
***
> Compile with C++11 and make sure the warning present.
***
***
=> Add compile time warning for C++14 upgrade

auth/integration_test/src/integration_test.cc, auth/src/auth.cc, auth/src/common.cc, auth/src/common.h, auth/src/data.h, auth/src/desktop/user_desktop.h, auth/src/include/firebase/auth.h, auth/src/include/firebase/auth/credential.h, auth/src/include/firebase/auth/types.h, auth/src/include/firebase/auth/user.h, auth/src/ios/auth_ios.mm, auth/src/ios/common_ios.h, auth/src/ios/credential_ios.mm, auth/src/ios/user_ios.mm, auth/src/user.cc
Update auth internals to support returning Future<User> object for the new API while also support returning Future<User*> objects for the deprecated API on iOS.
Changes does not include the new Future<User> methods.
***
Locally run integration test on device.
***
***
- Changes …
=> iOS support for multiple User objects

auth/integration_test/src/integration_test.cc, auth/src/android/auth_android.cc, auth/src/android/common_android.cc, auth/src/android/common_android.h, auth/src/android/credential_android.cc, auth/src/android/user_android.cc, auth/src/auth.cc, auth/src/common.cc, auth/src/common.h, auth/src/data.h, auth/src/desktop/user_desktop.cc, auth/src/include/firebase/auth/types.h, auth/src/include/firebase/auth/user.h, auth/src/ios/auth_ios.mm, auth/src/ios/common_ios.h, auth/src/ios/credential_ios.mm, auth/src/ios/user_ios.mm
Removes the need for User objects to be stored in AuthData, unlocking ability for there to be more than one User object at a time.
Continues to store a User in Auth, though, to maintain the implementation of the newly deprecated methods which return a User*.
Added a RetainUser integration test.
***
Locally tested on an iOS and Android device.
***
***
=> Android Auth Google I/O rework

app_check/integration_test/src/integration_test.cc, auth/integration_test/src/integration_test.cc, auth/src/android/credential_android.cc, auth/src/common.cc, auth/src/desktop/auth_providers/phone_auth_provider.cc, auth/src/include/firebase/auth/credential.h, auth/src/ios/credential_ios.mm
Add a new `PhoneAuthProvider::VerifyPhoneNumber` method that takes a `PhoneAuthOptions` structure.
For the C++ implementation on Android, update the current `VerifyPhoneNumber` method to call into the new offering. The older Android SDK `VerifyPhoneNumber` method is deprecated and will probably be removed from the Android SDK at Google I/O, so let's fix this before it becomes a problem.
It's a known issue that the desktop builds fail on this PR. This is due to some SDKs currently using `current_user_DEPRECATED` in the Auth API. The toolchains throw warnings for using a deprecated API, and the toolchains are configured to error-out on warnings. This will be fixed in subsequent PR.
***
> Describe how you've …
=> [Auth] PhoneAuthOptions struct for VerifyPhoneNumber

app_check/integration_test/src/integration_test.cc, auth/tests/auth_test.cc, database/integration_test/src/integration_test.cc, firestore/integration_test/src/integration_test.cc, firestore/integration_test_internal/src/firestore_test.cc, firestore/integration_test_internal/src/integration_test.cc, functions/integration_test/src/integration_test.cc, storage/integration_test/src/integration_test.cc
Numerous product SDKs have iTests which interact with Auth. In a previous feature branch change these tests were changed to use `Future<User*> Auth::current_user_DEPRECATED()`, for instance, as the new Auth API wasn't yet written.
This PR updates the tests to use the new APIs, such as `Future<AuthResult> Auth::current_user()`.
***
[Integration Test Run](https://github.com/firebase/firebase-cpp-sdk/actions/runs/4689751055)
***
*** …
=> Auth I/O '23 - update other SDK iTests to use new API

firestore/integration_test_internal/src/util/integration_test_util.cc, firestore/integration_test_internal/src/validation_test.cc, firestore/src/common/firestore.cc, firestore/src/include/firebase/firestore.h, firestore/src/main/firestore_main.cc, firestore/src/main/firestore_main.h
Passing database_id as an additional parameter all the way down to iOS `CreateFirestore` function.
Passing the database_id parameter only, no implementation change yet.
=> Pass database_id from GetInstance() down to CreateFirestore()

auth/src/include/firebase/auth/credential.h
`Listener::OnVerificationCompleted(Credential)` is going to be deprecated and should not be required to implement in the derived class.
***
Integration test.
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, …
=> Default no-op for deprecated virtual function

scripts/merge_libraries.py, scripts/merge_libraries_test.py
Add support for symbols like this one, which is referenced by the Firestore iOS SDK on Linux:
`grpc_slice_malloc_large::{lambda(grpc_slice_refcount*)#1}::_FUN(grpc_slice_refcount*)`
***
C++ packaging run: https://github.com/firebase/firebase-cpp-sdk/actions/runs/4756815007
***
*** …
=> Add support for symbols with {lambda...#1} to merge_libraries.py

app_check/integration_test/build.gradle, app_check/integration_test/src/integration_test.cc, app_check/src/android/app_check_android.cc
Contains a couple fixes for the App Check Android testapp:
- Turn on multidex support and off lint warnings in the gradle file, because of firestore
- Change the database test to handle that Android doesn't complete tasks with a bad app check
- Clean the Android App Check state on cleanup of the C++ App Check, to prevent it from calling up to C++ afterwards
***
Building and running the testapp locally
***
*** …
=> Fixes for the App Check Android testapp

app_check/src/ios/debug_provider_ios.h, app_check/src/ios/debug_provider_ios.mm, app_check/src/ios/device_check_provider_ios.h, app_check/src/ios/device_check_provider_ios.mm
We need to make sure the sizeof objects are the same regardless of definitions, so wrap the Obj C objects with a pointer than can always be present.
***
Running tests locally
***
*** …
=> Wrap the App Check Obj C pointers to fix memory issues

auth/integration_test/src/integration_test.cc, auth/src/android/user_android.cc, auth/src/data.h, auth/src/desktop/user_desktop.cc, auth/src/include/firebase/auth/user.h, auth/src/ios/user_ios.mm, auth/src/user.cc, auth/tests/desktop/user_desktop_test.cc
No need a DEPRECATED suffix for `LinkAndRetrieveDataWithCredential()` since there's no conflict in a new overloaded version of the method.
***
GA
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please …
=> Remove "_DEPRECATED" from LinkAndRetrieveDataWithCredential

app_check/src/ios/app_check_ios.mm
GetAppCheckToken on iOS was using a pointer for a local variable, which could be deleted by the time it is used. Instead, use the handle directly in the block, which should keep it alive as expected.
***
Running the Unity testapp locally
***
*** …
=> Fix use of handle in AppCheck block

auth/integration_test/src/integration_test.cc, auth/src/ios/auth_ios.mm, auth/src/ios/common_ios.h, auth/src/ios/user_ios.mm, release_build_files/readme.md
- null check `Credential.impl_` in `CredentialFromImpl()` and `PhoneAuthCredentialFromImpl()`
- Check if Auth API received an invalid Credential
- Add a basic test to just verify if `Credential.is_valid()` crashes. More comprehensive test should be added through b/281590792
***
GHA
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIB …
=> Fix `credential.is_valid()` crash on iOS

app/rest/request_file.cc, app/src/log.cc
App has two places it writes to files: in the rest library's FileRequest class (used by Storage's UploadFile), and the log code when logging to file. Update both of these to use a UTF16 path on Windows. For FileRequest, we convert the path (UTF8) into UTF16 before loading it on Windows. For log, we just store the log filename as a wide string as well.
***
***
***
- Read …
=> Support international paths on Windows in app

app/src/app_desktop.cc, app/src/filesystem_desktop_windows.cc, app/src/heartbeat/heartbeat_storage_desktop.cc, app/src/heartbeat/heartbeat_storage_desktop.h, app/tests/heartbeat_storage_desktop_test.cc
Two changes in this PR:
- Add Windows international path support to the heartbeat storage library.
- Ensure that multiple desktop apps don't write to the same heartbeat file by adding the package name to the heartbeat filename. Previously, only the app name (which is usually "__FIRAPPDEFAULT") was used, so if there were multiple apps installed on a machine (even completely unrelated apps), they would all use the same heartbeat file.
***
The integration test in this PR was run with added international characters in the path. (That test change has …
=> Modify heartbeat local storage to use wide strings on Windows.

cmake/external/flatbuffers.cmake, scripts/git/patches/flatbuffers/0001-remove-unused-var.patch
Add a patch to the flatbuffers version that we are pinned to that fixes an unused-variable warning.
Without this, after updating to xcode 14.3 a newer c compiler fails the build due to this warning about flatbuffers source.
In the flatbuffers repo this unused variable is not removed until much later when the relevant code is basically completely rewritten. So pinning to a newer version of flatbuffers can have other side effects. (Including requiring a newer version of cmake) 
The content of the cmake/external/flatbuffers file is basically copied from the similar websockets file which also applies a patch.
***
Verified that local builds fail without this patch and succeed with this patch.
***
***
- Bug fixes and feature changes require an update to the …
=> Patch flatbuffers to fix a warning that occurs with some compiler versions

scripts/gha/print_matrix_configuration.py
This is a followup to #1326.
That change updated from 16.1, 16.2 to 15.2, 15.4
This change updates ios simulator versions to 16.1, 16.1
Previously it was only the test that required 16.2 that was [failing](https://github.com/firebase/firebase-cpp-sdk/actions/runs/5001905633/jobs/8962904059) due to no simulator, and now there has also been a test run that [failed](https://github.com/firebase/firebase-cpp-sdk/actions/runs/5014197576/jobs/8989088252) because 15.x was unavailable. So stick to 16.1 as a version that is known to work.
Also note that ios 16.1 is associated with [xcode 14.1](https://developer.apple.com/documentation/xcode-release-notes/xcode-14_1-release-notes), and the two failing runs linked above both mention xcode 14.1 as available.
***
Integration test run: …
=> Update ios and tvos simulator versions for GitHub runners (a second time)

app/src_java/com/google/firebase/app/internal/cpp/JniResultCallback.java, release_build_files/readme.md
JniResultCallback was using two separate locks, with no guarantee on which will be grabbed first. This could cause a deadlock, leading to ANRs.  Fix this by just using a single lock.
Addresses issues like: https://github.com/firebase/quickstart-unity/issues/1286
***
Building locally, plus GHA tests
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/ …
=> Fix for a deadlock in JniResultCallback

app/src/include/firebase/app.h, app_check/src/include/firebase/app_check/app_attest_provider.h, app_check/src/include/firebase/app_check/debug_provider.h, app_check/src/include/firebase/app_check/device_check_provider.h, app_check/src/include/firebase/app_check/play_integrity_provider.h
Doxygen is having problems with the deleted constructors, so ignore them when running doxygen.
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we …
=> Fix App and App Check headers for doxygen

.github/workflows/build-report.yml, scripts/gha/it_workflow.py, scripts/gha/report_build_status.py, scripts/gha/update_issue_comment.py
This contains two parts: a script that fetches and analyzes GitHub nightly run results to see if they passed, and if not, what failed. And a script that posts that into the nightly build summary (along with the workflow to run it each morning).
***
Tested via manual run: https://github.com/firebase/firebase-cpp-sdk/actions/workflows/build-report.yml
Which updated the nightly report: https://github.com/firebase/firebase-cpp-sdk/issues/1179
***
***
- Bug fixes and feature changes require an update to the `Release …
=> Add a dashboard of build/test status to the nightly build page.

app_check/src/desktop/app_check_desktop.cc, release_build_files/readme.md
App Check on 32 bit desktop systems was incorrectly calculating the current time as negative, leading to tokens never being expired.  Fixed by converting the time to 64 bit earlier.
***
Running locally.
***
*** …
=> Fix App Check on 32 bit desktop

.gitignore
Ignore `CMakeUserPresets.json`, as documented at https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#build-preset. This allows developers to use their own CMake "presets" without having them show up as "modified" files in Git.
=> .gitignore: add CMakeUserPresets.json

release_build_files/readme.md, remote_config/src/android/remote_config_android.cc
ConfigUpdateListenerRegistration is missing from the proguard file for Remote Config, causing it to potentially be stripped when building with minification.  Add the necessary parts so that it gets added to the generated proguard file.
***
Building locally and verifying the lines get added to the proguard file.
***
***
https://github.com/firebase/firebase-unity-sdk/issues/753 …
=> Add missing Remote Config classes to proguard

firestore/integration_test_internal/build.gradle
Improve the local development build times for the Firestore integration tests on Android by (a) specifying `targets` to only build the required cmake targets and (b) specifying `abiFilters` conveniently in `local.properties` to only compile the ABI that is actually needed for local development (e.g. "x86", "x86_64", "arm64-v8a").
=> Firestore: integration_test_internal/build.gradle: improvements for local dev: targets and abiFilters

scripts/format_code.py
This PR fixes an apparent copy/paste error in `format_code.py` in the `list_files_from_directory()` function where it uses a local variable named `line`, that doesn't exist. The _correct_ local variable name is `filename`.
The result of this bug is that when `--d` is specified as a command-line argument the app crashes with a `NameError`:
```
$ python3 scripts/format_code.py --verbose --d firestore/src --r
Searching files in directory: "firestore/src"
Traceback (most recent call last):
File "scripts/format_code.py", line 276, in <module>
app.run(main)
File "site-packages/absl/app.py", line 308, in run
_run_main(main, args)
File "site-packages/absl/app.py", line 254, in _run_main
sys.exit(main(argv))
File "scripts/format_code.py", line 223, in main
filenames += …
```
=> format_code.py: fix NameError when --d is specified

firestore/integration_test_internal/src/android/firestore_integration_test_android.cc, firestore/integration_test_internal/src/android/firestore_integration_test_android.h, firestore/integration_test_internal/src/android/firestore_integration_test_android_test.cc, firestore/integration_test_internal/src/android/geo_point_android_test.cc, firestore/integration_test_internal/src/android/jni_runnable_android_test.cc, firestore/integration_test_internal/src/android/promise_android_test.cc, firestore/integration_test_internal/src/android/promise_factory_android_test.cc, firestore/integration_test_internal/src/android/settings_android_test.cc, firestore/integration_test_internal/src/android/snapshot_metadata_android_test.cc, firestore/integration_test_internal/src/android/timestamp_android_test.cc, firestore/integration_test_internal/src/android/transaction_options_android_test.cc, firestore/integration_test_internal/src/firestore_test.cc, firestore/integration_test_internal/src/jni/task_test.cc
Many of the Firestore integration tests for Android need an instance of `jni::Env`. The usual solution is create an instance as a local variable by simply declaring `jni::Env env`. This is a bit annoying because it adds clutter to the source code. Additionally, `jni::Env` instances are not allowed to be shared between threads, and having a local variable makes it easy to accidentally share instances with other threads.
To fix this, `FirestoreAndroidIntegrationTest` gains a new static member function named `env()` that returns a reference to an instance of `jni::Env`. By using a `thread_local` variable, it ensures that each thread gets its own instance. Then, (almost) all occurrences of `jni::Env env` have been removed from the tests, and where an instance was needed it just calls the …
=> Firestore: Improve Android tests to use the new env() helper function rather than creating an Env on the stack

auth/src/android/credential_android.cc, release_build_files/readme.md
On some platforms there was previously an issue with the code to convert TimeoutMilliseconds from uint32_t to java long, causing it to become a negative value and then getting rejected by Android validation.
Example: https://github.com/firebase/firebase-unity-sdk/issues/764
I was able to reproduce the original issue with the Unity Auth testapp, which calls VerifyPhoneNumber with a PhoneAuthOptions.
The visible error was: "VerifyPhoneNumber: builder faild to create PhoneAuhtOptions"
Looking into the android logcat, the internal error was: "We only support 0-120 seconds for sms-auto-retrieval timeout"
This change should fix this by having an explicit cast from uint32_t to jlong before passing the timeout into the java long constructor. This should make the code work regardless of whether …
=> Fix PhoneAuthOptions Timeout overflow on some platforms

gma/integration_test/src/integration_test.cc
Fixes gma integration tests to handle nofill error on loadAd.
***
None.
***
***
None.
=> Fix gma flaky tests caused by nofill error

remote_config/integration_test/src/integration_test.cc
Increase the wait time for FirebaseRemoteConfigTest.TestAddOnConfigUpdateListener from 10s to 30s to reduce test flakiness.
As shown on https://github.com/firebase/firebase-cpp-sdk/issues/1179, the realtime integration test is flaky.
I looked into the logs and all of the failures fail at the point of waiting 10s for the promise to indicate that an updated config has been fetched ([example](https://github.com/firebase/firebase-cpp-sdk/actions/runs/5332119405/jobs/9662903098)). I looked into a number of other logs and see that even though most runs of this test finish in less than 3 seconds, around 10% of the successes take 5-10 seconds, so the flaky failures are likely just taking slightly longer than normal due to slow network or other delays. 30 seconds should be enough to significantly …
=> Increase the wait time for realtime integration test from 10s to 30s

scripts/gha/test_simulator.py
Add logic to check which versions of iOS/tvOS are available, and fallback to the latest if the requested one isn't available. Also change to using xcodes to install iOS simulators, since xcode-install has been deprecated in favor of it.
This is the same change as https://github.com/firebase/firebase-unity-sdk/pull/774, but for the C++ repo.
***
***
*** …
=> Improve the iOS simulator install logic

CMakeLists.txt, cmake/external/boringssl.cmake, cmake/external_rules.cmake, scripts/git/patches/boringssl/0001-disable-warnings.patch
In this release, the "src" directory is removed from boringssl, so there are some CMake and patch changes necessary for compatibility.
There are a number of issues with newer Xcode and other compilers that are fixed in newer boringssl releases. This updates to the last 2022 release (from a 2019 version used before).
***
Running expanded integration tests in this PR. Also running packaging [workflow](https://github.com/firebase/firebase-cpp-sdk/actions/runs/5381916010) and [tests](https://github.com/firebase/firebase-cpp-sdk/actions/runs/5384312567) …
=> Update to June 2022 release of boringssl.

app/src/util.cc, app/src/util.h, app/tests/util_test.cc, app_check/src/android/app_check_android.cc, app_check/src/android/app_check_android.h, app_check/src/android/common_android.cc, app_check/src/android/common_android.h, auth/src/auth.cc, database/src/android/database_android.cc, database/src/android/database_android.h, database/src/android/database_reference_android.cc, database/src/android/disconnection_android.cc, functions/src/android/callable_reference_android.cc, functions/src/android/functions_android.cc, functions/src/android/functions_android.h, installations/src/android/installations_android.cc, installations/src/android/installations_android.h, remote_config/src/android/remote_config_android.cc, remote_config/src/android/remote_config_android.h, storage/src/android/storage_android.cc, storage/src/android/storage_android.h, storage/src/android/storage_reference_android.cc
Add logic to the products that use objects to clean any pending Task listeners on destruction of that object.  Refactor the string creation logic from Auth to a utility function so all the products can use the same.
***
***
*** …
=> Clean up JNI task listeners per object

scripts/gha/test_simulator.py
Adds a GitHub warning to the iOS simulator logic, as a follow up to https://github.com/firebase/firebase-cpp-sdk/pull/1368
***
***
*** …
=> Add a GitHub warning to the iOS simulator logic

gma/integration_test/src/integration_test.cc
Adds missing future release on some of the gma integration tests.
***
None.
***
***
None.
=> Release load_ad futures in flaky gma tests

firestore/src/main/aggregate_query_main.cc, firestore/src/main/aggregate_query_snapshot_main.cc
=> Use core implementation of aggregate query equality operator.

firestore/integration_test_internal/src/android/firestore_integration_test_android.cc, firestore/integration_test_internal/src/android/firestore_integration_test_android_test.cc, firestore/integration_test_internal/src/jni/task_test.cc
For a description of each individual change, see the commit messages of the individual commits.
=> Firestore: Various small improvements to the Android integration tests

firestore/CMakeLists.txt, firestore/integration_test_internal/CMakeLists.txt, firestore/integration_test_internal/src/android/arena_ref_android_test.cc, firestore/integration_test_internal/src/document_reference_test.cc, firestore/integration_test_internal/src/field_value_test.cc, firestore/src/android/document_reference_android.cc, firestore/src/android/field_value_android.cc, firestore/src/android/field_value_android.h, firestore/src/android/firestore_android.cc, firestore/src/android/query_android.cc, firestore/src/android/util_android.cc, firestore/src/android/util_android.h, firestore/src/android/wrapper.cc, firestore/src/android/wrapper.h, firestore/src/android/write_batch_android.cc, firestore/src/android/write_batch_android.h, firestore/src/jni/arena_ref.cc, firestore/src/jni/arena_ref.h, firestore/src/jni/env.h, firestore/src/jni/loader.h, firestore/src_java/com/google/firebase/firestore/internal/cpp/ObjectArena.java, release_build_files/readme.md
Properly fix the the global refs exhaustion issue tracked by https://github.com/firebase/firebase-unity-sdk/issues/569, and reported in https://github.com/firebase/quickstart-unity/issues/1303 and https://github.com/firebase/quickstart-unity/issues/1193#issuecomment-1242203289 (Googlers see b/251869890 for more details). Part 1, a partial mitigation, was https://github.com/firebase/firebase-cpp-sdk/pull/1111.
This PR supersedes, and builds upon the work done by @cherylEnkidu in, https://github.com/firebase/firebase-cpp-sdk/pull/1176.
=> Firestore: Fix global refs exhaustion issue in Android

scripts/gha/test_simulator.py
The xcodes install can fail when not run as root, so do so.
***
***
***
=> Run iOS simulator install as root

scripts/gha/build_testapps.py
Update the build_testapps script to additionally log the generated files so that users of this script don't need to search in the generated folders to find the output.
Example:
python scripts/gha/build_testapps.py --p Desktop,Android --t auth,remote_config --output_directory build_folder
TRIED TO BUILD: auth,remote_config
ON PLATFORMS: Desktop,Android
ALL BUILDS SUCCEEDED
GENERATED FILES:
/Users/almostmatt/Documents/GitHub/firebase-cpp-sdk/build_folder/testapps-local-build/auth/integration_test
/Users/almostmatt/Documents/GitHub/firebase-cpp-sdk/build_folder/testapps-local-build/auth/integration_test-debug.apk
/Users/almostmatt/Documents/GitHub/firebase-cpp-sdk/build_folder/testapps-local-build/remote_config/integration_test
/Users/almostmatt/Documents/GitHub/firebase-cpp-sdk/build_folder/ …
=> Update build_testapps script to log generated files.

app/src/locale.cc
This file is usually located in /etc/timezone and contains something like "America/Los Angeles" rather than "PDT" or "GMT", which is less preferred.
***
Unit test on Linux shows the new time zone name returned.
***
***
- Changes to the public API require an internal API review. …
=> On Ubuntu, GetTimezone should return the long time zone name.

gma/integration_test/src/integration_test.cc, gma/src/android/gma_android.cc, gma/src/ios/native_ad_internal_ios.mm
Fix for gma android failing assert
***
None.
***
***
NativeAd's getIcon() for android and icon() for iOS are nullable API methods and this indicates that ads returned will not always guarantee the availability of an icon asset. This PR relaxes the restriction which expects an icon asset at all times and processes the contents of an icon asset, only when a valid icon image asset is returned by andriod/iOS layers.
Ref: https://developers.google.com/admob/ios/api/reference/Classes/GADNativeAd#icon
Also updates the integration test to look for a large image asset rather than an icon asset, as the test ad unit ids are always expected to return a valid large image asset on a successful ad load.
=> Fix for gma android failing assert

external/pip_requirements.txt, scripts/gha/integration_testing/ftl_gha_validator.py, scripts/gha/python_requirements.txt
This should fix the flaky GMA iOS "crash/timeout" test, as the error is often just that it's unable to fetch the test results (possibly because that test runs so quickly). [Example log](https://github.com/firebase/firebase-cpp-sdk/actions/runs/5541140566/jobs/10115711281#step:13:309)
***
Ran GMA integration test on iOS a [number of times](https://github.com/firebase/firebase-cpp-sdk/actions/workflows/integration_tests.yml?query=branch%3Aadd-retry-to-ftl-log-load+event%3Aworkflow_dispatch+is%3Acompleted) without issues. Considering this usually …
=> Add a retry decorator to the GitHub log downloader.

release_build_files/readme.md
In #1364 I accidentally put the release notes entry under the "11.2.0" heading, when it should have gone under the "Upcoming Release" heading.
=> Fix readme.md for version of android global refs fix release notes entry

scripts/gha/integration_testing/ftl_gha_validator.py
This should help with flaky FTL tests.
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we …
=> Increase retry for GS log fetch.

.github/workflows/build-report.yml, scripts/gha/report_build_status.py
Added Firestore test history to the nightly report.
***
https://github.com/firebase/firebase-cpp-sdk/actions/runs/5650617856
***
*** …
=> Add Firestore test history report

.github/workflows/cpp-packaging.yml
Run the nightly packaging an hour earlier, so that it can be ready on time for the summary, and EST timezones.
***
***
*** …
=> Kick off nightly packaging an hour earlier

cmake/external_rules.cmake
When building the subproject, we would invoke `cmake` directly, relying on the path lookup of the tool, which may or may not match the currently executing CMake.  Use `CMAKE_COMMAND` which gives us the path to the current CMake executable ensuring that we use the same CMake for building the dependencies.
***
Local run of the CMake configure step.
***
***
=> build: pass along the CMake path

scripts/gha/integration_testing/ftl_gha_validator.py
Some of our iOS test runs are failing due to gsutil errors, even with retry. Add logs for the error output.
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase …
=> Add log to gsutil fetch.

.github/workflows/update-feature-branches.yml
Don't merge directly from main, as this can introduce merge commits directly into the main branch, which we don't want.
Instead, branch main and then merge it.
***
***
***
- Changes to the public API require an internal …
=> Update merge-main-into-feature-branch script

gma/src/android/native_ad_image_android.cc
Remove query parameters from native image urls that may download a webp image
***
None.
***
***
Remove query parameters from native image urls that may download a webp image
=> Internal Updates.

analytics/integration_test/src/integration_test.cc, analytics/src/analytics_android.cc, analytics/src/analytics_ios.mm, analytics/src/analytics_stub.cc, analytics/src/include/firebase/analytics.h, analytics/src_ios/fake/FIRAnalytics.h, analytics/src_ios/fake/FIRAnalytics.mm, analytics/tests/analytics_test.cc, release_build_files/readme.md
Exposes the iOS-only feature InitiateOnDeviceConversionMeasurementWithPhoneNumber, which improves observable conversions for your app, which was recently added to the iOS SDK.
***
***
*** …
=> Add Analytics function for on-device conversion

scripts/gha/print_matrix_configuration.py
iOS 16.5 is deprecated on FTL. This updates the "ios_latest" device to 16.6.
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your …
=> Fix iOS test version from deprecated 16.5 to 16.6.

gma/integration_test/src/integration_test.cc
The OperationInProgress test fails on iOS simulator due to the LoadAndShow method being too quick, so disable it on that platform.
***
***
***
- Changes to the public API require an internal API review. If you'd like to …
=> Skip a UMP test that doesn't work on iOS simulator.

.github/workflows/integration_tests.yml, scripts/gha/print_matrix_configuration.py, scripts/gha/summarize_test_results.py, scripts/gha/test_simulator.py
Distributing the load will help prevent issues with a single FTL device type from bottlenecking the tests.
Depends on https://github.com/FirebaseExtended/github-actions/pull/7 being merged and a new release of the firebase-test-lab action created.
***
Running expanded tests on this PR.
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CON …
=> Distribute FTL tests amongst different device models

firestore/integration_test_internal/src/validation_test.cc
Android and iOS SDKs added multiple inequality support recently https://github.com/firebase/firebase-ios-sdk/pull/11626, https://github.com/firebase/firebase-android-sdk/pull/5194, where 2 restrictions get lifted on inequality queries:
- All inequality filters must reference the same field.
- The first ordering must be the same field as an inequality filter
The validation tests on above restrictions can be removed now.
=> Remove validation tests on inequality restrictions

.github/workflows/desktop.yml, .github/workflows/integration_tests.yml
Firebase CLI (and Firestore emulator) now require Node 18 minimum, so install that on our runners instead of 16.
***
Tests in this PR, this should also fix the Firestore desktop nightlies.
***
***
- Changes to the public API require an internal API review. If you'd like to help …
=> Switch to node 18, node 16 no longer works with Firebase CLI.

Android/firebase_dependencies.gradle, app/app_resources/build.gradle, app/google_api_resources/build.gradle, app/invites_resources/build.gradle, app_check/app_check_resources/build.gradle, auth/auth_resources/build.gradle, database/database_resources/build.gradle, firestore/firestore_resources/build.gradle, gma/gma_resources/build.gradle, messaging/messaging_java/build.gradle, release_build_files/Android/firebase_dependencies.gradle, release_build_files/readme.md, remote_config/remote_config_resources/build.gradle, storage/storage_resources/build.gradle
=> Update Android dependencies to BoM 32.7.0.

auth/CMakeLists.txt, auth/src/desktop/get_account_info_result.cc, auth/src/desktop/rpcs/sign_up_request.cc, auth/src/desktop/rpcs/sign_up_request.h, auth/src/desktop/user_desktop.cc, auth/tests/desktop/user_desktop_test.cc, auth/tests/user_test.cc, release_build_files/readme.md
Changes to email enumeration protection broke some functionality on the backend with email accounts. One of those is upgrading anonymous accounts to have email and password.  This can be fixed by using a slightly different rest call, so this makes that change for desktop, mobile platforms will be fixed in the underlying mobile SDKs.
***
Testing locally with a custom project that has email enumeration protection turned on.
***
*** …
=> Fix issue with linking email to anonymous accounts on desktop

gma/integration_test/src/integration_test.cc
It turns out that occasionally LoadConsentForm will still return Success when AoC = true, although the form itself won't do anything. So we should include that in the possible result.
***
In this PR.
***
*** …
=> UMP: Fix TestUmpLoadFormUnavailableDueToAgeOfConsent flaky test.

firestore/src/include/firebase/firestore/aggregate_source.h, firestore/src/include/firebase/firestore/query.h
Apply the feedback to the count API documentation as suggested in https://github.com/firebase/firebase-js-sdk/pull/6608. This is a port of https://github.com/firebase/firebase-js-sdk/pull/7933.
=> Firestore: Small Count API documentation improvements

auth/integration_test/src/integration_test.cc
=> Add retry to SignInAnonymously to avoid network issues.

storage/integration_test/src/integration_test.cc
Some FTL devices have slow network connections, and so the large file download can occasionally take a long time. This causes a flaky failure in Storage tests, as the tests time out after 10 minutes and are marked as crash/timeout.
This PR adds a 2-minute timeout to the large file download operations to make them more resilient to slow network connectivity.
***
Tested locally with timeout temporarily set to 5 seconds.
***
*** …
=> Fix storage large download timeout.

gma/integration_test/src/integration_test.cc, gma/src/ios/ump/consent_info_internal_ios.mm
Also fix the "Wrong Instance" test to be simpler and handle non-UI mode.
This should fix one of the most common test flakes in this repo.
***
***
*** …
=> UMP iOS: Add extra locks around async operations.

.github/workflows/checks.yml, .github/workflows/integration_tests.yml
Per recommendation here: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs …
=> Reference untrusted git branch names via environment variables.

gma/integration_test/src/integration_test.cc
Clean up handling of NoFill errors in two ways:
1. Use the new WaitForCompletion syntax to allow both error codes.
2. Add NoFill handling to InterstitialAd tests.
***
***
***
- Changes to the public API require an …
=> Clean up handling of GMA NoFill errors.

messaging/messaging_java/build.gradle, release_build_files/readme.md
Since updating Gradle, omitting this sets the minimum SDK to 1 instead of 14, and adds a host of other issues.
***
Manually tested receiving notification in the integration_test app on Android emulator.
***
*** …
=> Add explicit SDK version to messaging AAR.

.github/workflows/cpp-packaging.yml, scripts/gha/retry_test_failures.py
Add a retry for scheduled cpp-packaging similar to integration-tests, for transient errors only.
***
Temporarily allowed for non-scheduled runs and tested here: https://github.com/firebase/firebase-cpp-sdk/actions/runs/7632039407/attempts/1
***
*** …
=> Add retry to C++ packaging step.

analytics/integration_test/src/integration_test.cc
On Android, once SetConsent is called denying consent, calling it again allowing consent doesn't always take affect until the app restarts.
So move SetConsent to the end of the tests, and ensure that if it's  run earlier (due to test order being randomized), skip the tests that can fail.
***
***
*** …
=> Move SetConsent test to the end to not break GetAnalyticsInstanceId tests.

messaging/CMakeLists.txt
In the Messaging CMake we expose the path of the messaging aar for the Unity build to use. Because of the gradle update, the path changed slightly, so we need to update the path.
***
Building the Unity SDK locally, and on GHA.
***
***
- Changes to the public API require an …
=> Update messaging aar path for Unity in CMake

gma/integration_test/src/integration_test.cc, gma/src/android/gma_android.cc, gma/src/common/native_ad.cc, gma/src/common/native_ad_internal.cc, gma/src/common/native_ad_internal.h, gma/src/include/firebase/gma/internal/native_ad.h, gma/src/ios/FADNativeDelegate.mm, gma/src_java/com/google/firebase/gma/internal/cpp/NativeAdHelper.java
Adds AdListener support for NativeAd.
***
N/A
***
***
Internal Updates only.
=> Internal Updates

Android/firebase_dependencies.gradle, scripts/gha/print_matrix_configuration.py
If Android/firebase_dependencies.gradle and ios_pod/Podfile only have changed lines referencing GMA or UMP packages, then allow auto_diff to only specify GMA.
This should greatly speed up "quick" tests when updating only GMA dependencies.
***
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk …
=> Improve --auto_diff mode for when GMA is the only changed SDK.

app/rest/request_options.h, release_build_files/readme.md, storage/src/desktop/storage_reference_desktop.cc
Our REST implementation has a default timeout of 5 minutes. This overrides this timeout with 0, which tells libcurl to have no timeout for the connection.
***
***
***
- Changes to the public API require an internal API review. If you'd like to help …
=> Set Storage Desktop REST requests to have no timeout.

auth/src/include/firebase/auth.h, database/src/include/firebase/database.h, database/src/include/firebase/database/mutable_data.h, firestore/src/include/firebase/firestore/aggregate_query_snapshot.h, firestore/src/include/firebase/firestore/document_change.h, firestore/src/include/firebase/firestore/document_snapshot.h, firestore/src/include/firebase/firestore/query.h, firestore/src/include/firebase/firestore/query_snapshot.h
Hide some private friend methods from swig, since it is trying to generate C# based on them, when it shouldn't be.  This is because a new version of SWIG came out that does this.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/8563655507
***
***
- Changes to the …
=> Hide some private friend functions from swig

release_build_files/readme.md, storage/src/ios/storage_reference_ios.mm
As reported in #1570, if `StorageReference::GetFile()` is called from a non-UI thread, the `const char* path` passed in is not preserved and could have been deleted by the calling code once the `FIRStorage` native call occurs in the main thread later.
Fix this by creating the URL from the local file path outside outside of the thread dispatch block. (Similar to what `PutFile()` already does.)
***
***
*** …
=> Fix Storage usage of invalid pointers.

scripts/gha/print_matrix_configuration.py
Runners only have 17.4 on the the 10th-gen iPad by default.
***
***
*** …
=> Fix iOS simulator device to use the one that's available

.github/workflows/cpp-packaging.yml, build_scripts/desktop/package.sh
Packaging was failing on Windows Debug due to disk space limitations, this PR reduces the space required for packaging.
https://github.com/firebase/firebase-cpp-sdk/actions/runs/9504804792
***
***
***
- Changes to the …
=> Reduce the Windows packaging task size by deleting the .tgz and not building tests.

gma/src/include/firebase/gma.h, gma/src/include/firebase/gma/ad_view.h, gma/src/include/firebase/gma/interstitial_ad.h, gma/src/include/firebase/gma/rewarded_ad.h, release_build_files/readme.md
=> Add GMA C++ deprecation notice

gma/src/include/firebase/gma.h, gma/src/include/firebase/gma/ad_view.h, gma/src/include/firebase/gma/interstitial_ad.h, gma/src/include/firebase/gma/rewarded_ad.h
=> Modify deprecation notice.

messaging/src/include/firebase/messaging.h
Messaging now only supports receiving downstream messages, so the comments specifying that fields are only used for downstream messages aren't necessary anymore.
***
***
***
- Changes to the public API require an internal …
=> Remove comments specifying downstream messages

cmake/external_rules.cmake
The GHA machines updated cmake versions, which seems to have a problem when passing in the CMAKE_OSX_ARCHITECTURES with quotes, so remove them.  Note that normally when we do the call from scripts, we don't have the quotes, this is just in the part where we have cmake trigger itself for downloads.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/9882221217
***
*** …
=> Remove unnecessary cmake quotes

messaging/src/common.cc, release_build_files/readme.md
Preserve the Messaging token if one is received when a Listener isn't set, and then send that token to the Listener when it is set.  Normally we recommend setting the Listener with Initialize, which avoids this issue, but there are some use cases, like the Unity SDK, where there is a gap of time between Initialize and SetListener.
***
Running the Unity testapp locally
***
*** …
=> Preserve Messaging token until a Listener is set

release_build_files/readme.md, remote_config/src/android/remote_config_android.cc, remote_config/src/include/firebase/remote_config.h, remote_config/src/ios/remote_config_ios.mm
On Android, handle the underlying SDK returning a negative fetch time. On iOS, fix throttled_time initialization issues.
Fixes this Unity issue, since the incorrect values were getting added to TimeSpans, which caused exceptions to be thrown: https://github.com/firebase/firebase-unity-sdk/issues/1058
***
Testing locally
***
*** …
=> Fix RemoteConfig info initialization issues

.github/workflows/cpp-packaging.yml, .github/workflows/integration_tests.yml
This reverts commit 2a2330455b83d8512d0c6cc575a865fb1de1cfee.
***
***
*** …
=> Revert "Bump actions/download-artifact from 3 to 4.1.7 (#1638)"

auth/integration_test/src/integration_test.cc, auth/src/android/user_android.cc, release_build_files/readme.md
On iOS and Desktop, setting photo_url to nullptr resulted in no change to the user, and empty string resulted in clearing the field on user.  On Android, both resulted in no change in the user.  Make it consistently clear the field with an empty string, and do no change with nullptr.  And added tests to verify.
***
***
*** …
=> Make UpdateUserProfile consistent on clearing fields on Android

app_check/integration_test/functions/functions/index.js, messaging/integration_test/functions/functions/index.js
Firebase Functions now defaults to v2, but the test ones we have are still v1, so add the v1 suffix to keep them as working examples.
***
***
***
- Changes to the public API require an internal API review. If you'd like …
=> Specify using v1 Cloud Functions

.github/workflows/cpp-packaging.yml, .github/workflows/desktop.yml, .github/workflows/integration_tests.yml, scripts/gha/report_build_status.py
Update the GitHub actions for upload and download artifacts to v4.
***
Packaging Run: https://github.com/firebase/firebase-cpp-sdk/actions/runs/11733979480
Test Run: https://github.com/firebase/firebase-cpp-sdk/actions/runs/11736048885
***
***
- Changes to the public API require …
=> Update upload download artifacts to v4

.github/workflows/update-dependencies.yml
Running into permission problems with the token, so changing the logic to use the default token when making the PR. Every other step still uses the previous token though, since that works for the other steps.
***
https://github.com/firebase/firebase-cpp-sdk/actions/runs/13643145191
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIB …
=> Use the default token when updating dependencies

.github/workflows/android.yml, .github/workflows/checks.yml, .github/workflows/cpp-packaging.yml, .github/workflows/desktop.yml, .github/workflows/integration_tests.yml, .github/workflows/ios.yml
GitHub runners updated CMake to CMake 4, which breaks our build. Install an explicit version of CMake instead.
***
Tests/checks here and packaging workflow [here](https://github.com/firebase/firebase-cpp-sdk/actions/runs/14225991890).
***
***
- Changes to the public API require …
=> Downgrade CMake to 3.31.x on our runners.

messaging/src/android/cpp/messaging.cc, release_build_files/readme.md
If the messaging token is received via Installations, which can happen if it is cached, it wasn't setting the flags to allow subscriptions to work correctly, causing them to hang. Set the flags, and resolve any pending subscriptions when the token is received via that mechanic.
***
Running locally.
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/ …
=> [Messaging] Fix subscription not completing sometimes

Jules.md
This experimental document is meant for consumption by AI agents and will be maintained by them as a way to remember repo standards and conventions across tasks.
***
***
***
- Changes to the public API require an internal …
=> Add an experimental doc as a repository for AI agent knowledge

scripts/gha/get_pr_review_comments_standalone.py, scripts/print_github_reviews.py
=> Create standalone version of Get PR Comments script for use in other repos, with added features.

app/src/util_ios.mm, release_build_files/readme.md
=> iOS: Allow specifying your AppDelegate class's name in the Info.plist file.

analytics/generate_windows_stubs.py, analytics/src/analytics_desktop.cc, analytics/src/analytics_desktop_dynamic.c, analytics/src/analytics_desktop_dynamic.h, analytics/src/analytics_windows.cc
=> Update Analytics to use new options struct.

scripts/print_github_reviews.py
If GITHUB_TOKEN environment variable is not set and --token argument is not provided, the script will now attempt to read the GitHub token from the `~/.github_token` file.
The order of precedence for token retrieval is:
1. --token command-line argument
2. GITHUB_TOKEN environment variable
3. ~/.github_token file
***
***
***
- Bug fixes and feature changes require an update to the `Release Notes` section …
=> Update print_github_reviews.py to read token from ~/.github_token

scripts/print_github_reviews.py
This change allows the script to find a pull request based on a specified branch name, in addition to the existing methods of using a pull request number or the current git branch.
The --branch argument is mutually exclusive with --pull_number. If neither --pull_number nor --branch is provided, the script defaults to finding the latest PR for the current git branch.
***
***
***
- Bug fixes and feature …
=> Add --branch argument to print_github_reviews.py

.github/workflows/integration_tests.yml, scripts/gha/firebase_github.py, scripts/gha/report_build_status.py
Handle 401 Gone errors, and also increase retention time so logs last 90 days.
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose …
=> Fix build status report

auth/integration_test/src/integration_test.cc, auth/src/android/user_android.cc, auth/src/desktop/user_desktop.cc, auth/src/include/firebase/auth/user.h, auth/src/ios/user_ios.mm, auth/src/user.cc, auth/tests/desktop/user_desktop_test.cc, auth/tests/user_test.cc, release_build_files/readme.md
=> Remove deprecated cpp auth function

scripts/gha/report_build_status.py
The log files name changed several months, so update the script to handle it.
***
https://github.com/firebase/firebase-cpp-sdk/actions/runs/16457849624
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please …
=> Fix the build report status script

scripts/gha/print_matrix_configuration.py
The GHA runners no longer have tvOS 16.1 available by default, so change to 17.2 instead.
https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#installed-simulators
***
***
***
- Changes to …
=> Update the tvOS simulator version used by tests
