README.md

Added a Unit Test section to the readme, including known unit test issues on Mac OS.

updated the readme with unit test section.

---

firestore/integration_test/Info.plist

To test via FTL, we must adding configuration in the project’s Info.plist file.
https://firebase.google.com/docs/test-lab/game-loop#register-url

Fix firestore plist

---

app/tests/heartbeat_info_desktop_test.cc
app/tests/util_test.cc
database/CMakeLists.txt
testing/util_android_test.cc

- fixed gmock include paths for files in app/tests directory.
- removed util_desktop_windows, util_desktop_linux, and util_desktop_maco from CMakefiles.

Build fixes for dev branch

---

build_scripts/desktop/package.sh

Fixes building and running integration tests against the packaged SDK binary.

Fix the packaged build to have the correct generated headers, and also include instance ID impl.

---

.github/workflows/cpp-packaging.yml

Accidentally merged a bad conditional into the workflow - this fixes it.

Fix a bad conditional in packaging workflow.

---

app/instance_id/instance_id_desktop_impl.cc
app/src/locale.cc
app/tests/locale_test.cc
auth/src/desktop/rpcs/error_codes.cc
firestore/src/android/firestore_android.cc
firestore/src/android/firestore_android.h
firestore/src/jni/env.cc
firestore/src/jni/env.h
firestore/src/jni/loader.h
firestore/src/jni/object.cc
firestore/src/jni/object.h
firestore/src/jni/string.cc
firestore/src/jni/string.h
firestore/src/tests/field_value_test.cc
firestore/src/tests/firestore_integration_test.cc
firestore/src/tests/jni/env_test.cc
firestore/src/tests/jni/object_test.cc
storage/src/common/storage_uri_parser.cc

Manually cherrypick+merge Firestore changes and bug fixes from internal git repo.

Merge Firestore changes

---

admob/integration_test/Podfile
analytics/integration_test/Podfile
app/integration_test/Podfile
auth/integration_test/Podfile
database/integration_test/Podfile
dynamic_links/integration_test/Podfile
firestore/integration_test/Podfile
functions/integration_test/Podfile
installations/integration_test/Podfile
instance_id/integration_test/Podfile
messaging/integration_test/Podfile
remote_config/integration_test/Podfile
storage/integration_test/Podfile

Update the integration test Podfile versions to match the versions in ios_pod/Podfile.

Change Podfile version for integration tests to 7.0.0.

---

testing/sample_framework/src/desktop/desktop_app_framework.cc

Because this is desktop only, C++11 is available and std::mutex can be used cross-platform.

Add a mutex to the integration test log methods, to avoid a rare crash.

---

release_build_files/readme.md

A few bits of cleanup in the readme.

Update C++ readme.

---

scripts/gha/print_matrix_configuration.py

separated out config (string) parameters from matrix (list) parameters. New flag "-c" or "--config" specifies which parameters we are trying to query.
"--overrides" flag changed to "--override" now accepts just the value for queried flag.

separate config and matrix parameters.

---

.github/workflows/integration_tests.yml

Integration Test Result: https://github.com/firebase/firebase-cpp-sdk/actions/runs/709015656

disable test on simulator

---

analytics/integration_test/src/integration_test.cc
analytics/src/analytics_android.cc
analytics/src/analytics_ios.mm
analytics/src/analytics_stub.cc
analytics/src/include/firebase/analytics.h
analytics/src_ios/fake/FIRAnalytics.h
analytics/src_ios/fake/FIRAnalytics.mm
analytics/src_java/fake/com/google/firebase/analytics/FirebaseAnalytics.java
analytics/tests/analytics_test.cc
release_build_files/readme.md

Syncing with the removal from underlying native mobile SDKs.

Removed SetCurrentScreen method from Analytics

---

scripts/gha/print_matrix_configuration.py

fix bug here: https://github.com/firebase/firebase-cpp-sdk/runs/2850975360?check_suite_focus=true

Fix Linux OS is "ubuntu" not "linux"

---

.github/workflows/checks.yml
scripts/gha/check_copyright.sh

Currently fails on a whole bunch of files - these will be fixed on a subsequent PR. (The check is not "required" yet so won't block PRs.)

Add copyright check to PR checks.

---

firestore/src/common/field_value.cc
firestore/src/common/firestore.cc
firestore/src/jni/env.cc
firestore/src/jni/env.h

This covers all mentions of b/163140650

Address STLPort-specific workarounds

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Create a PR template

---

messaging/integration_test/src/integration_test.cc
testing/test_framework/src/firebase_test_framework.h

Add retry logic to FirebaseMessagingTest.TestSendMessageToToken.

Fix flaky test

---

.github/workflows/checks.yml
app/src/include/firebase/app.h
docs/Doxyfile
scripts/gha/pr_file_commenter.py

Adds a generic pr_file_commenter.py script that takes warnings/errors from stdin and posts them as file comments in the PR.
Use this script to add comments for errors in generated docs.

Add generic PR file comment script, and use it to show docs errors.

---

README.md

Updated README with instructions on building for tvOS.

updated docs for tvos

---

scripts/gha/desktop_tester.py

Request by @wu-hui . Print out integration test result. Mobile platforms already printed out.

Print out integration test result for desktop platform

---

.github/workflows/update-dependencies.yml

This needs to be in the main branch to use workflow_dispatch for testing the *actual* workflow.

Add placeholder workflow for updating dependencies.

---

.github/workflows/update-dependencies.yml

Was accidentally including both iOS and Android logs in both sections - this filters out the correct one for each section.

Fix log file for when both Android and iOS are present.

---

.github/workflows/update-dependencies.yml
scripts/update_android_ios_dependencies.py

Fix a bug in the Python script that outputs the logfile of dependency changes. Also make the workflow script a little more robust in the case where the logfile doesn't exist or is malformed (it should still create the PR, just without the details in the description).
***
https://github.com/firebase/firebase-cpp-sdk/actions/runs/1284791796
***
*** …

Fix bug in dependency update workflow.

---

.github/workflows/desktop.yml

Add sanity check to desktop workflow
***

Run linux integration test in desktop workflow

---

scripts/update_android_ios_dependencies.py

Fix script to use Firebase/ subspecs.
***
Run Update dependencies workflow
***
***

Fix script to use Firebase/ subspecs.

---

app/src/include/firebase/internal/mutex.h

Prevent Doxyen warnings/errors from caring about Mutex.
***
***
*** …

Remove Mutex class from Doxygen docs.

---

Android/firebase_dependencies.gradle

Small fix for release mode integration test builds on Android. (They currently build in debug, just not in release - this fixes that.)
***
Manually built an integration test in release mode via `gradlew assembleRelease` on Windows and Mac.
***
*** …

Fix a typo in the firebase_dependencies.gradle file.

---

gma/integration_test/src/integration_test.cc
gma/src/android/ad_view_internal_android.cc
gma/src/android/ad_view_internal_android.h
gma/src/android/gma_android.cc
gma/src/android/gma_android.h
gma/src/common/ad_view_internal.cc
gma/src/common/ad_view_internal.h
gma/src/common/gma_common.cc
gma/src/common/gma_common.h
gma/src/include/firebase/gma/types.h
gma/src/ios/FADAdSize.mm
gma/src/ios/FADAdView.mm
gma/src/ios/ad_view_internal_ios.h
gma/src/ios/ad_view_internal_ios.mm
gma/src/stub/ad_view_internal_stub.h
gma/src_java/com/google/firebase/gma/internal/cpp/AdViewHelper.java

Add inline adaptive AdSize type, and four static methods to AdSize to construct them.
***
- Local Testing on devices.
- [Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1841784074)
- [Packaging CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1841788773) -> [Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/1842292339)
***
***

GMA Inline Adaptive AdSizes

---

scripts/gha/build_desktop.py

This reverts commit d0416114824b5a7b7a11eb6deb47a52bb6d5d590.
***
***
*** …

Revert "Change workaround"

---

gma/src/include/firebase/gma.h
gma/src/include/firebase/gma/types.h

Updates to the GMA headers to reflect changes that DevRel wanted within our reference docs.
***
Docs regeneration in internal cl.
***
***

GMA Reference Doc fixes based on DevRel feedback.

---

app/CMakeLists.txt
app/src/heartbeat/heartbeat_storage_desktop.cc
app/src/heartbeat/heartbeat_storage_desktop.h
app/src/heartbeat/schemas/logged_heartbeats.fbs
app/tests/CMakeLists.txt
app/tests/heartbeat_storage_desktop_test.cc

This is an initial implementation of storage for heartbeat desktop implementation
There are a number of TODOs for details that I am still working on, but the rough outline is there

Heartbeat desktop - implementation of heartbeat storage

---

scripts/gha/integration_testing/gameloop_android/gradle/wrapper/gradle-wrapper.properties

Set game loop gradle version back to 6.1.1, minimum supported.

---

build_scripts/android/package.sh

(Actually just use a wildcard in case it changes again.)
***
***
*** …

Fix packaging workflow to use new name for messaging_java.aar.

---

.github/workflows/desktop.yml
.github/workflows/integration_tests.yml

Update the nodejs version to 14, since the Firebase CLI seems to require it now.
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose …

Update the nodejs version to 14, for Firebase CLI

---

.github/workflows/desktop.yml
.github/workflows/integration_tests.yml
Android/firebase_dependencies.gradle
gma/src/ios/adapter_response_info_ios.mm
release_build_files/Android/firebase_dependencies.gradle

Update the GMA Feature branch to include CI changes from main.
Additionally update the iOS AdapterResponseInfo impl to fix querying a string on a non-existent object.
***
Local hardware
Local Simulator
[Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2379410834)
***
***

Merge Main into GMA Feature Branch 5/24

---

Android/firebase_dependencies.gradle
gma/gma_resources/build.gradle
release_build_files/Android/firebase_dependencies.gradle

Update Android depdencies to the release of the GMA 21.0.0 SDK.
***
- Local testing on phones and simulators.
- [Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2495952020)
- [Packaging CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2495968819) -> [Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2496975943)
***
***

updated Android gma version to 21.0.0

---

admob/admob_resources/build.gradle
app/app_resources/build.gradle
app/google_api_resources/build.gradle
app/invites_resources/build.gradle
auth/auth_resources/build.gradle
database/database_resources/build.gradle
firestore/firestore_resources/build.gradle
messaging/messaging_java/build.gradle
release_build_files/readme.md
storage/storage_resources/build.gradle

There were places where we were still using the older BOM version 30.0.0.  Update those places so that we're consistently using BOM 30.1.0.
***
Triggered Intergration Tests on this PR.
***
***

Update Android BOM to 30.1.0 in integration tests and readme

---

release_build_files/readme.md

Updates to release notes including:
- Releases notes entry for the GMA SDK
- Updates to Desktop (stub), Android and iOS depdenency lists to add a `Firebase Google Mobile Ads` entry.
***
None.  Changes to the readme only.
***
***

GMA updates to release notes

---

.github/workflows/checks_secure.yml
.github/workflows/cpp-packaging.yml

File name change result in packaging workflow failing. https://github.com/firebase/firebase-cpp-sdk/runs/7291430951?check_suite_focus=true#step:6:1
Fixed the file name.
***
Packaging workflow running: https://github.com/firebase/firebase-cpp-sdk/actions/runs/2652715644
***
***

Fix python requirement file name

---

gma/src/android/ad_request_converter.cc
gma/src/android/response_info_android.cc
gma/src/include/firebase/gma/types.h
gma/src/ios/response_info_ios.mm

Fixes documentation and code for `medation` typos.
***
[Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/2693019481)
***
***

GMA mediation typos

---

app/CMakeLists.txt
app/src/heartbeat/heartbeat_controller_desktop.cc
app/src/heartbeat/heartbeat_controller_desktop.h
app/tests/CMakeLists.txt
app/tests/heartbeat_controller_desktop_test.cc

Fetch heartbeats from storage, clear storage, create and return an encoded string payload of the heartbeats.
***
Added unit testing of the controller class, as well as unit tests for the payload construction and encoding methods.
Also added a test to verify that the backend can handle the generated header.
https://critique.corp.google.com/cl/460999804
***
*** …

Heartbeat Controller - Desktop Implementation - GetPayload

---

release_build_files/readme.md

Received feedback when publishing the release notes to the devsite that the platform series `(Android,iOS,Linux,macOS 32-bit)` should be `(Android, iOS, Linux, macOS 32-bit)`.  Additionally removed mac from the list as there's no 32-bit support for that platform.
***
None, only a release notes change.
***
***

Release notes format fixes for platform series

---

scripts/gha/it_workflow.py

Add [C++] description to the nightly test report

---

scripts/gha/utils.py

The dependency installation on Ubuntu i386 keeps having issues because of conflicting dependencies. Aptitude does a better job of correctly resolving those without needing us to keep adding separate workarounds for each conflict, so use that instead.
***
The standard GHA tests
***
***
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING …

Use aptitude for Ubuntu 86 dependencies

---

app/src/include/firebase/app.h

…be defined. this way integration tests dont need to depend on it.
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us …

Fix integration test build on heartbeat branch

---

build_scripts/ios/package.sh
build_scripts/tvos/package.sh

Use the product list when pulling iOS and tvOS libraries into the final package.
***
https://github.com/firebase/firebase-cpp-sdk/actions/runs/3146322849
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, …

Make the ios tvos packaging use the product list

---

gma/integration_test/Podfile
ios_pod/Podfile
release_build_files/readme.md

Update our dependency to iOS GMA SDK 9.11.0.
***
- Locally executed integration test app on iPhone.
- [Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/3151986918)
- [Packaging CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/3151988176) -> [Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/3153236799)
***
***

Update GMA iOS dependency to 9.11.0

---

app_check/src/common/app_check.cc
app_check/src/include/firebase/app_check.h

The abstract virtual classes like the factory still need to define their destructors, so add them.
***
Local testing, plus automated tests.
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your …

Add missing virtual destructors for App Check

---

auth/src/include/firebase/auth/credential.h

remove @ref after @deprecated to bypass devsite check

---

.gitignore

Add files that are generated when building the integration tests to the gitignore file
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can …

Update gitignore for integration test files

---

.github/workflows/integration_tests.yml
scripts/gha/print_matrix_configuration.py
scripts/gha/summarize_test_results.py

Use FTL Virtual Android devices, instead of local emulators. (It could save testing time. And hopefully, less flaky.)
***
https://github.com/firebase/firebase-cpp-sdk/actions/runs/3397055951/jobs/5648808778
Also, see the comments.
***
***

Use FTL Virtual Android devices to run tests

---

cmake/external/firestore.cmake
firestore/src/main/query_main.cc

Nanopb has an issue with different versions of python that is causing problems on the build machines. This was fixed on the iOS SDK side, so pin to that version until a release is out with it.
***
***
***
- Changes to the public API require an internal API review. If you'd like …

Pin to a version of iOS with nanopb fix

---

admob/integration_test/CMakeLists.txt
analytics/integration_test/CMakeLists.txt
app/integration_test/CMakeLists.txt
app_check/integration_test/CMakeLists.txt
auth/integration_test/CMakeLists.txt
database/integration_test/CMakeLists.txt
dynamic_links/integration_test/CMakeLists.txt
firestore/integration_test/CMakeLists.txt
firestore/integration_test_internal/CMakeLists.txt
functions/integration_test/CMakeLists.txt
gma/integration_test/CMakeLists.txt
installations/integration_test/CMakeLists.txt
messaging/integration_test/CMakeLists.txt
remote_config/integration_test/CMakeLists.txt
storage/integration_test/CMakeLists.txt

Firestore improve cmake file error message
***
Compile the changes locally
***
***

Firestore improve cmake file error message

---

storage/integration_test/src/integration_test.cc

Fix Storage test errors on iOS.

---

admob/integration_test/CMakeLists.txt
analytics/integration_test/CMakeLists.txt
app/integration_test/CMakeLists.txt
app_check/integration_test/CMakeLists.txt
auth/integration_test/CMakeLists.txt
database/integration_test/CMakeLists.txt
dynamic_links/integration_test/CMakeLists.txt
firestore/integration_test/CMakeLists.txt
firestore/integration_test_internal/CMakeLists.txt
functions/integration_test/CMakeLists.txt
gma/integration_test/CMakeLists.txt
installations/integration_test/CMakeLists.txt
messaging/integration_test/CMakeLists.txt
remote_config/integration_test/CMakeLists.txt
storage/integration_test/CMakeLists.txt

Python should be found using find_program, so that it will accept either python3 or python. We already updated the SDK build with this, this change updates the integration tests with the same logic.
***
***
*** …

Update integration tests to find python smarter

---

.allstar/binary_artifacts.yaml

Exempt from go/allstar check #1171 because the binary file is part of the onboarding tool.
***
N/A
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we …

Exempt from go/allstar check

---

gma/integration_test/Podfile
ios_pod/Podfile
release_build_files/readme.md

Update the GMA SDK underlying dependency to release v9.14.0.
***
[Integration Test CI](https://github.com/firebase/firebase-cpp-sdk/actions/runs/3997151625).
***
***

Update iOS GMA dependency to 9.14.0

---

analytics/src/include/firebase/analytics.h

Change the GetSessionId docs to match GetAnalyticsInstanceId's phrasing.

---

gma/integration_test/src/integration_test.cc

GMA stress tests are causing cascading GMA test failures on nightly builds. Let's turn off those stress tests except for manually-executed tests.
***
***
***
- Changes to the public API require an internal API review. If …

Mark GMA stress tests as requiring user interaction on Android as well.

---

gma/integration_test/src/integration_test.cc
scripts/update_android_ios_dependencies.py

Handle NoFill errors in TestRewardedAdLoad tests.

---

.github/workflows/checks_secure.yml

Previously was only allowing admin permission to keep their approvals.
***
***
***
- Changes to the public API require an internal API review. If you'd like to …

Don't dismiss stale approvals on users with write permission either.

---

auth/samples/src/doc_samples.cc

Update auth user doc examples to use the new Auth API.
***
***
*** …

Auth Google I/0 23 - Update doc examples to use new API

---

cmake/external/firestore.cmake

This branch fixes a failing unit test in the iOS SDK: https://github.com/firebase/firebase-ios-sdk/tree/release-10.9.0-with-patch
***
***
***
- Changes to the public API require an internal API review. If you'd like to …

Update Firestore dependency to use patched SDK.

---

remote_config/src/include/firebase/remote_config.h

Reorganize the RemoteConfigError enum to prevent confusion on what value each is.
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can discuss it …

Fix RemoteConfigError enum values

---

release_build_files/readme.md

Fix capitalization of AddOnConfigUpdateListener in release notes. Also mention Android/iOS.
***
N/A
***
***

Fix Realtime RC release notes

---

auth/src/include/firebase/auth.h
auth/src/include/firebase/auth/user.h

Removed @ref flags that are messing up internal doc generation.

---

scripts/gha/print_matrix_configuration.py

Update the ios and tvos simulator versions used by GitHub actions.
Previously ios_simulator_latest was failing.
Example of past failure:
https://github.com/firebase/firebase-cpp-sdk/actions/runs/5001905633/jobs/8962904059
***
Test run: https://github.com/firebase/firebase-cpp-sdk/actions/runs/5006266427
***
***

Update ios and tvos simulator versions for GitHub runners

---

.gitignore
app/integration_test/src/integration_test.cc
app/src/app_android.cc
app/src/app_common.cc
app/src/app_common.h
app/src/app_desktop.cc
app/src/app_ios.mm
app/src/app_stub.cc
app/src/include/firebase/app.h
app/src/util_android.h

add api to get allApps

---

gma/integration_test/src/integration_test.cc
gma/src/android/gma_android.cc
gma/src/android/native_ad_image_android.cc
gma/src/android/native_ad_image_android.h
gma/src/common/gma_common.cc
gma/src/common/gma_common.h
gma/src/common/native_ad.cc
gma/src/common/native_ad_image_internal.h
gma/src/common/native_ad_internal.h
gma/src/include/firebase/gma/internal/native_ad.h
gma/src/include/firebase/gma/types.h
gma/src/ios/gma_ios.h
gma/src/ios/gma_ios.mm
gma/src/ios/native_ad_image_ios.mm
gma/src/stub/native_ad_image_stub.cc
gma/src_java/com/google/firebase/gma/internal/cpp/DownloadHelper.java

Experimental changes.
***
None.
***
***
Stacked PR on top of #1300

Internal updates 4

---

gma/CMakeLists.txt
gma/integration_test/src/integration_test.cc
gma/src/android/gma_android.cc
gma/src/android/native_ad_image_android.cc
gma/src/android/native_ad_image_android.h
gma/src/common/gma_common.cc
gma/src/common/gma_common.h
gma/src/common/native_ad.cc
gma/src/common/native_ad_image_internal.h
gma/src/common/native_ad_internal.cc
gma/src/common/native_ad_internal.h
gma/src/include/firebase/gma/internal/native_ad.h
gma/src/include/firebase/gma/types.h
gma/src/ios/gma_ios.h
gma/src/ios/gma_ios.mm
gma/src/ios/native_ad_image_ios.h
gma/src/ios/native_ad_image_ios.mm
gma/src/ios/native_ad_internal_ios.mm
gma/src/stub/native_ad_image_stub.cc
gma/src_java/com/google/firebase/gma/internal/cpp/DownloadHelper.java
gma/src_java/com/google/firebase/gma/internal/cpp/NativeAdHelper.java

Experimental changes.
***
None.
***
***
Stacked PR on top of #1269

Internal updates 3

---

gma/CMakeLists.txt
gma/integration_test/src/integration_test.cc
gma/src/android/gma_android.cc
gma/src/android/native_ad_image_android.cc
gma/src/android/native_ad_image_android.h
gma/src/common/gma_common.cc
gma/src/common/gma_common.h
gma/src/common/native_ad.cc
gma/src/common/native_ad_image_internal.h
gma/src/common/native_ad_internal.cc
gma/src/common/native_ad_internal.h
gma/src/include/firebase/gma/internal/native_ad.h
gma/src/include/firebase/gma/types.h
gma/src/ios/FADNativeDelegate.h
gma/src/ios/FADNativeDelegate.mm
gma/src/ios/gma_ios.h
gma/src/ios/gma_ios.mm
gma/src/ios/native_ad_image_ios.h
gma/src/ios/native_ad_image_ios.mm
gma/src/ios/native_ad_internal_ios.h
gma/src/ios/native_ad_internal_ios.mm
gma/src/stub/native_ad_image_stub.cc
gma/src_java/com/google/firebase/gma/internal/cpp/DownloadHelper.java
gma/src_java/com/google/firebase/gma/internal/cpp/NativeAdHelper.java

Experimental changes. iOS implementation only. 
***
None
***
Stacked PR on top of https://github.com/firebase/firebase-cpp-sdk/pull/1251

Internal updates 2

---

.github/workflows/build-report.yml
.gitignore
scripts/gha/report_build_status.py

Add a table of the failures/flakes that occur most often to the build summary.
***
Example: #1179 (unless it's been overridden)
***
*** …

Add a summary of the most often failing tests to the daily build report

---

firestore/src/jni/env.cc

Avoid calling `ok()` in `Env::~Env()` if there is no exception handler registered. The only reason to call `ok()` at all is to pass a pending exception to the registered exception handler; therefore, there is no need to call it if there is no registered exception handler. This also fixes an annoying crash when the destructor is run _after_ the current thread has detacted from the JVM, such as when stored in a variable with `thread_local` storage duration.

Firestore: env.cc: avoid calling ok() in the destructor if there is no exception handler

---

.github/workflows/cpp-packaging.yml

***
Packaging workflow runs [here](https://github.com/firebase/firebase-cpp-sdk/actions/workflows/cpp-packaging.yml?query=branch%3Aadd-windows-only-package).
***
*** …

Add step to C++ packaging to create Windows package.

---

scripts/gha/print_matrix_configuration.py

Update the iOS version used by FTL, since the previous one was removed.
Version determined by following these instructions: https://firebase.google.com/docs/test-lab/ios/available-testing-devices
***
***
*** …

Update the iOS version used by FTL

---

messaging/messaging_java/build.gradle

Some compiler versions complain about an unused variable in Flatbuffers - this patch (which we already use on desktop) fixes the issue.
This PR adds the patch to Android builds.
***
***
***
- Changes to the public API require an internal API review. …

Apply unused variables patch to Flatbuffers on Android as well.

---

.github/workflows/integration_tests.yml

Add a matrix label to FTL test runs, to make sorting them easier.

---

.github/workflows/integration_tests.yml
.github/workflows/retry-test-failures.yml
scripts/gha/firebase_github.py
scripts/gha/print_matrix_configuration.py
scripts/gha/retry_test_failures.py
scripts/gha/trigger_workflow.py

On nightly tests, if any builds or tests failed, trigger a workflow that runs a script to retry failed jobs in the integration test run if appropriate.
The jobs will NOT be retried if:
- They are already in progress or queued (e.g. a retry is already happening)
- They have already been attempted 3 times 
- They contain a real compiler error
Otherwise, failed jobs WILL be retried if:
- They failed on mobile
- On desktop, the logs match retryable error text (e.g. "timed out", "network error")
This PR also includes some small fixes in trigger_workflow.py to fix issues brought up by the workflow changes:
- Don't try to start a workflow run at 'HEAD', use 'main' instead.
- Fix exit codes to actually work
- If git …

Retry nightly test failures

---

.github/workflows/integration_tests.yml

npm -g is failing on Windows due to file access issues. Instead, install npm packages locally and add the local module paths to the system PATH.
***
Integration test in this PR, tests on all 3 platforms.
***
***
- Changes to the public API require an internal API review. If …

Install Firebase tools locally, and skip if unneeded in desktop tests.

---

firestore/CMakeLists.txt

Update a path in the Firestore CMake to point to the internal pod path, which changed with the 10.17 dependency.
***
***
*** …

Update Firestore core header path

---

gma/integration_test/src/integration_test.cc

Fix test failures with non-EEA debug tests on iOS.

---

analytics/integration_test/src/integration_test.cc
analytics/src/analytics_android.cc
analytics/src/analytics_ios.mm
analytics/src/include/firebase/analytics.h
release_build_files/readme.md

The underlying mobile SDKs have a couple new Analytics ConsentTypes, so update the C++ SDK with them.
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so …

Add new Analytics consent types

---

dynamic_links/src/include/firebase/dynamic_links.h
release_build_files/readme.md

Mark the Dynamic Links SDK as deprecated.

---

scripts/gha/install_prereqs_desktop.py

This fixes some missing symbols in the Firestore build caused by grpc:
* SSL_get1_peer_certificate
* EVP_DigestSignUpdate
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us …

Pin OpenSSL version to 3.1.1 on Windows runners.

---

scripts/gha/print_matrix_configuration.py

FTL removed ipadmini4 from the supported devices, so remove it from our list.
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can discuss it …

Remove invalid iOS device from test list

---

.github/workflows/retry-test-failures.yml

> remove empty condition, the current workflow is invalid
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can …

ci: remove empty condition, the current workflow is invalid

---

storage/integration_test/readme.md

I just fixed a small typo which was bothering me.
I just fixed a small typo which was bothering me.
***
Eyes testing ;)
***
*** …

Fix typo in storage/integration_test/readme.md

---

analytics/src/include/firebase/analytics.h

Remove some extra swig logic that is unnecessarily in the C++ header file.  The logic to add the unsafe tag was already in the Unity SDK's swig file, and it will be going away soon anyway.
***
***
***
- Changes to the …

Remove unnecessary swig logic from Analytics

---

.github/workflows/integration_tests.yml

Make the video log names more unique
***
***
***
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we …

Update video log names

---

.github/workflows/build-report.yml
.github/workflows/checks.yml
.github/workflows/checks_secure.yml
.github/workflows/update-feature-branches.yml

Add write permission to nightly report workflow.

---

scripts/gha/print_matrix_configuration.py

Update iOS FTL versions.
